package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.AccessClassModel;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.RoleModel;

/**
 * Emits one {@link HasAccessControl} implementation per {@link AccessClassModel}.
 *
 * <p>Each generated class lives in {@code configPackage} and implements
 * {@code getGrants()} by building a {@link SetMultimap} of {@code UserRole} to
 * {@link Permission} values derived from the CRUD letter strings in the model.
 *
 * <p>Generated by ccd-definition-converter from AuthorisationCaseField — do not edit by hand.
 */
public class AccessClassEmitter implements SourceEmitter {

  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    String configPkg = context.configPackage();
    List<JavaFile> files = new ArrayList<>();

    // UserRole is always generated fresh (retrofit decision 3), so this is the generated enum in
    // the model package in both modes.
    ClassName userRoleClass = context.userRoleClass();

    // Build a map from role id -> javaConstant for lookup
    Map<String, String> roleIdToConstant = buildRoleIndex(model);

    String banner = context.banner(model.getCaseTypeId(), "AuthorisationCaseField");
    for (AccessClassModel acm : model.getAccessClasses()) {
      JavaFile jf = emitAccessClass(acm, configPkg, userRoleClass, roleIdToConstant, banner);
      files.add(jf);
    }
    return files;
  }

  private JavaFile emitAccessClass(
      AccessClassModel acm,
      String configPkg,
      ClassName userRoleClass,
      Map<String, String> roleIndex,
      String banner) {

    ClassName hasRoleClass = ClassName.get(HasRole.class);
    ClassName permClass = ClassName.get(Permission.class);
    TypeName multimapType = ParameterizedTypeName.get(
        ClassName.get(SetMultimap.class), hasRoleClass, permClass);

    MethodSpec.Builder getGrantsBuilder = MethodSpec.methodBuilder("getGrants")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .returns(multimapType);

    getGrantsBuilder.addStatement(
        "$T<$T, $T> grants = $T.create()",
        SetMultimap.class, hasRoleClass, permClass, HashMultimap.class);

    for (Map.Entry<String, String> entry : acm.getGrants().entrySet()) {
      String roleId = entry.getKey();
      String crud = entry.getValue();
      String constant = roleIndex.get(roleId);
      if (constant == null) {
        // Skip roles not in the model (should not happen in a well-linked model)
        continue;
      }
      List<CodeBlock> permCodes = crudToPermissions(crud, permClass);
      for (CodeBlock perm : permCodes) {
        getGrantsBuilder.addStatement(
            "grants.put($T.$L, $L)", userRoleClass, constant, perm);
      }
    }

    getGrantsBuilder.addStatement("return grants");

    TypeSpec classSpec = TypeSpec.classBuilder(acm.getClassName())
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get(HasAccessControl.class))
        .addJavadoc(banner)
        .addMethod(getGrantsBuilder.build())
        .build();

    return JavaFile.builder(configPkg, classSpec)
        .skipJavaLangImports(true)
        .indent("    ")
        .build();
  }

  private List<CodeBlock> crudToPermissions(String crud, ClassName permClass) {
    List<CodeBlock> result = new ArrayList<>();
    if (crud == null) {
      return result;
    }
    String upper = crud.toUpperCase();
    for (char ch : upper.toCharArray()) {
      switch (ch) {
        case 'C':
          result.add(CodeBlock.of("$T.C", permClass));
          break;
        case 'R':
          result.add(CodeBlock.of("$T.R", permClass));
          break;
        case 'U':
          result.add(CodeBlock.of("$T.U", permClass));
          break;
        case 'D':
          result.add(CodeBlock.of("$T.D", permClass));
          break;
        default:
          break;
      }
    }
    return result;
  }

  private Map<String, String> buildRoleIndex(CaseTypeModel model) {
    Map<String, String> index = new java.util.LinkedHashMap<>();
    for (RoleModel role : model.getRoles()) {
      index.put(role.getId(), role.getJavaConstant());
    }
    return index;
  }
}
