package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.FieldModel;

/**
 * Emits the generated {@code CaseData} class for a case type.
 *
 * <p>Each CaseField row in the model (except Label-type fields and overlay-tagged rows) becomes a
 * private field annotated with {@code @CCD} and optionally {@code @JsonProperty}.
 *
 * <p>Generated by ccd-definition-converter from CaseDataEmitter — do not edit by hand.
 */
public class CaseDataEmitter implements SourceEmitter {

  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    String pkg = context.modelPackage();
    FieldEmitHelper helper = new FieldEmitHelper(pkg, context.accessPackage());

    List<FieldSpec> fields = new ArrayList<>();
    for (FieldModel field : model.getCaseFields()) {
      // Skip overlay-tagged fields (they go to passthrough)
      if (field.getOverlayTags() != null && !field.getOverlayTags().isEmpty()) {
        continue;
      }
      // Label-type fields are emitted as real members (String with @CCD(typeOverride=Label)) so
      // their CaseField row, Searchable flag and AuthorisationCaseField access classes round-trip
      // like any other field, rather than being reconstructed only where a tab or event happens to
      // reference them.
      fields.add(helper.buildField(field));
    }

    TypeSpec.Builder classBuilder = TypeSpec.classBuilder("CaseData")
        .addModifiers(Modifier.PUBLIC)
        .addJavadoc(context.banner(model.getCaseTypeId(), "CaseField"));
    LombokAnnotations.applyDataClass(classBuilder, fields.size());
    classBuilder.addFields(fields);

    JavaFile jf = JavaFile.builder(pkg, classBuilder.build())
        .skipJavaLangImports(true)
        .indent("    ")
        .build();
    return List.of(jf);
  }
}
