package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.ComplexTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.FieldModel;

/**
 * Emits one generated class per {@link ComplexTypeModel} in the case type.
 *
 * <p>Each class is annotated {@code @ComplexType(generate = true)} so the SDK's
 * CaseFieldGenerator recognises it as a complex type and writes the corresponding JSON.
 *
 * <p>Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
public class ComplexTypeEmitter implements SourceEmitter {

  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    String pkg = context.modelPackage();
    FieldEmitHelper helper = new FieldEmitHelper(pkg, context.configPackage(),
        context.getOptions().getRetrofitTypeFqnOverrides());
    List<JavaFile> files = new ArrayList<>();

    for (ComplexTypeModel ct : model.getComplexTypes()) {
      List<FieldSpec> fields = new ArrayList<>();
      for (FieldModel member : ct.getMembers()) {
        if (member.getOverlayTags() != null && !member.getOverlayTags().isEmpty()) {
          continue;
        }
        fields.add(helper.buildField(member));
      }

      TypeSpec.Builder classBuilder = TypeSpec.classBuilder(ct.getId())
          .addModifiers(Modifier.PUBLIC)
          .addJavadoc(
              "Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.");
      LombokAnnotations.applyDataClass(classBuilder, fields.size());
      classBuilder.addAnnotation(AnnotationSpec.builder(ClassName.get(ComplexType.class))
          .addMember("generate", "$L", true)
          .build());
      classBuilder.addFields(fields);

      JavaFile jf = JavaFile.builder(pkg, classBuilder.build())
          .skipJavaLangImports(true)
          .indent("    ")
          .build();
      files.add(jf);
    }
    return files;
  }
}
