package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.ComplexTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.FieldModel;

/**
 * Emits one generated class per {@link ComplexTypeModel} in the case type.
 *
 * <p>Each class is annotated {@code @ComplexType(generate = true)} so the SDK's
 * CaseFieldGenerator recognises it as a complex type and writes the corresponding JSON.
 *
 * <p>Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
public class ComplexTypeEmitter implements SourceEmitter {

  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    String pkg = context.modelPackage();
    FieldEmitHelper helper = new FieldEmitHelper(pkg, context.configPackage(),
        context.getOptions().getRetrofitTypeFqnOverrides());
    List<JavaFile> files = new ArrayList<>();

    for (ComplexTypeModel ct : model.getComplexTypes()) {
      List<FieldSpec> fields = new ArrayList<>();
      for (FieldModel member : ct.getMembers()) {
        if (member.getOverlayTags() != null && !member.getOverlayTags().isEmpty()) {
          continue;
        }
        fields.add(helper.buildField(member));
      }

      // The class is named with the Java-conventional PascalCase name (finding #3); the CCD-facing
      // type ID is preserved as the wire ID via @ComplexType(name = id) whenever it differs, which
      // the SDK's ComplexTypeGenerator/CaseFieldGenerator read for the emitted ComplexTypes ID and
      // every referencing field's FieldType/FieldTypeParameter, so the rename round-trips exactly.
      String className = ct.getJavaClassName() != null ? ct.getJavaClassName() : ct.getId();
      TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
          .addModifiers(Modifier.PUBLIC)
          .addJavadoc(context.banner(model.getCaseTypeId(), "ComplexTypes"));
      LombokAnnotations.applyDataClass(classBuilder, fields.size());
      AnnotationSpec.Builder complexTypeAnn = AnnotationSpec.builder(ClassName.get(ComplexType.class));
      if (!className.equals(ct.getId())) {
        complexTypeAnn.addMember("name", "$S", ct.getId());
      }
      complexTypeAnn.addMember("generate", "$L", true);
      classBuilder.addAnnotation(complexTypeAnn.build());
      classBuilder.addFields(fields);

      JavaFile jf = JavaFile.builder(pkg, classBuilder.build())
          .skipJavaLangImports(true)
          .indent("    ")
          .build();
      files.add(jf);
    }
    return files;
  }
}
