package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.ComplexTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.FieldModel;

/**
 * Emits one generated class per {@link ComplexTypeModel} in the case type.
 *
 * <p>Each class is annotated {@code @ComplexType(generate = true)} so the SDK's
 * CaseFieldGenerator recognises it as a complex type and writes the corresponding JSON.
 *
 * <p>Generated by ccd-definition-converter from ComplexTypes — do not edit by hand.
 */
public class ComplexTypeEmitter implements SourceEmitter {

  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    String pkg = context.modelPackage();
    FieldEmitHelper helper = new FieldEmitHelper(pkg, context.accessPackage(),
        context.getOptions().getRetrofitTypeFqnOverrides());
    List<JavaFile> files = new ArrayList<>();

    for (ComplexTypeModel ct : model.getComplexTypes()) {
      List<FieldSpec> fields = new ArrayList<>();
      for (FieldModel member : ct.getMembers()) {
        if (member.getOverlayTags() != null && !member.getOverlayTags().isEmpty()) {
          continue;
        }
        fields.add(helper.buildField(member));
      }

      // The class is named with the Java-conventional PascalCase name (finding #3); the CCD-facing
      // type ID is pinned as the wire ID via @ComplexType(name = id) ALWAYS, not only when the two
      // differ, because the SDK reads the name for two distinct purposes and only one of them can
      // fall back to the class name.
      //
      // ComplexTypeGenerator and CaseFieldGenerator.resolveFieldType both default to the simple
      // class name when name is absent, so on a same-named type a pinned name is inert there. But
      // CaseFieldGenerator.withNamedComplexType — which resolves the FieldType of a field carrying
      // @CCD(typeParameterClass = <companion>) — has no such fallback: it returns the DECLARED
      // type's ID unless the named companion supplies a name, since the whole point of that path is
      // that the field is typed as something other than the companion. An absent name there is
      // indistinguishable from "this class names no CCD type", so the column silently keeps the
      // declared class's ID.
      //
      // That path is reached whenever RetrofitPatchEmitter.withComplexCompanion covers a refused
      // retype, and it is the common case for a family of types whose IDs are ALREADY legal
      // PascalCase and so would never trip an inequality test — CIVIL's *LRspec/*GAspec types
      // (HearingLRspec, HomeDetailsLRspec, UserDetails, OtherRemedyFee). respondent1DQHearingFast-
      // Claim declares Hearing and is addressed by the definition's HearingLRspec; its accessors
      // have callers, so the retype is refused and the field is covered by
      // @CCD(typeParameterClass = HearingLRspec.class). With the name conditional the field emitted
      // FieldType=Hearing while the ComplexTypes rows were already correct under HearingLRspec.
      String className = ct.getJavaClassName() != null ? ct.getJavaClassName() : ct.getId();
      TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
          .addModifiers(Modifier.PUBLIC)
          .addJavadoc(context.banner(model.getCaseTypeId(), "ComplexTypes"));
      LombokAnnotations.applyDataClass(classBuilder, fields.size());
      AnnotationSpec.Builder complexTypeAnn = AnnotationSpec.builder(ClassName.get(ComplexType.class));
      complexTypeAnn.addMember("name", "$S", ct.getId());
      complexTypeAnn.addMember("generate", "$L", true);
      classBuilder.addAnnotation(complexTypeAnn.build());
      classBuilder.addFields(fields);

      JavaFile jf = JavaFile.builder(pkg, classBuilder.build())
          .skipJavaLangImports(true)
          .indent("    ")
          .build();
      files.add(jf);
    }
    return files;
  }
}
