package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.fasterxml.jackson.annotation.JsonValue;
import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.FixedListModel;
import uk.gov.hmcts.ccd.sdk.converter.model.RoleModel;
import uk.gov.hmcts.ccd.sdk.converter.model.StateModel;

/**
 * Emits generated enums for fixed lists, states, and user/case roles.
 *
 * <p>Three shapes are produced:
 * <ul>
 *   <li>FixedList enums implementing {@link HasLabel}: one per {@link FixedListModel}.</li>
 *   <li>State enum: constants named exactly by state ID, {@code @CCD} per constant.</li>
 *   <li>UserRole enum implementing {@link HasRole}: one constant per role.</li>
 * </ul>
 *
 * <p>Generated by ccd-definition-converter from FixedLists/States/Roles — do not edit by hand.
 */
public class EnumEmitter implements SourceEmitter {

  // Lombok ClassName constants — string-based so Lombok need not be on the converter runtime.
  private static final ClassName GETTER = ClassName.get("lombok", "Getter");
  private static final ClassName ALL_ARGS = ClassName.get("lombok", "AllArgsConstructor");
  private static final ClassName REQ_ARGS = ClassName.get("lombok", "RequiredArgsConstructor");

  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    String pkg = context.modelPackage();
    List<JavaFile> files = new ArrayList<>();

    for (FixedListModel fl : model.getFixedLists()) {
      files.add(emitFixedList(fl, pkg, context.banner(model.getCaseTypeId(), "FixedLists")));
    }
    // In retrofit mode the team's own State enum is reused (its IDs all resolve — proposal decision
    // 3), so no fresh State enum is generated; the config references the team's enum via
    // EmitContext.stateClass(). When there is no reusable enum, generate fresh as in generate mode.
    if (context.getOptions().getRetrofitStateClass() == null) {
      files.add(emitState(model.getStates(), pkg, context.banner(model.getCaseTypeId(), "State")));
    }
    files.add(emitUserRole(model.getRoles(), pkg,
        context.banner(model.getCaseTypeId(), "AuthorisationCaseType/CaseRoles")));

    return files;
  }

  // -----------------------------------------------------------------------
  // Fixed list enums
  // -----------------------------------------------------------------------

  private JavaFile emitFixedList(FixedListModel fl, String pkg, String banner) {
    // Determine whether any constant requires a @JsonValue code field.
    // FixedListGenerator puts the enum constant object directly as "ListElementCode" value,
    // which is then serialised by Jackson. When a @JsonValue method is present Jackson
    // calls it; otherwise it uses toString() == name(). When javaConstant != code the
    // original code must be preserved via @JsonValue on the code field.
    boolean needsCodeField = fl.getItems().stream()
        .anyMatch(item -> !item.getJavaConstant().equals(item.getCode()));

    // The enum is named with the Java-conventional PascalCase name (finding #4, FL_ prefix dropped);
    // the CCD-facing list ID is preserved as the wire ID via @ComplexType(name = id) whenever it
    // differs, which the SDK's FixedListGenerator reads for the emitted FixedLists ID and file name
    // and CaseFieldGenerator reads for referencing fields' FieldTypeParameter, so the rename
    // round-trips exactly.
    String enumClassName = fl.getJavaClassName() != null ? fl.getJavaClassName() : fl.getId();
    TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder(enumClassName)
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get(HasLabel.class))
        .addJavadoc(banner);
    if (!enumClassName.equals(fl.getId())) {
      // generate = true is required: the SDK's FixedListGenerator and CaseFieldGenerator only treat
      // an enum as a generated fixed list when it has no @ComplexType or one with generate() true.
      // (An enum with no @ComplexType at all defaults to "generate"; adding name= flips generate to
      // its false default unless we set it explicitly.)
      enumBuilder.addAnnotation(AnnotationSpec.builder(ClassName.get(ComplexType.class))
          .addMember("name", "$S", fl.getId())
          .addMember("generate", "$L", true)
          .build());
    }

    if (needsCodeField) {
      // Two-arg constructor: label + code. @JsonValue on code field.
      enumBuilder
          .addAnnotation(AnnotationSpec.builder(GETTER).build())
          .addAnnotation(AnnotationSpec.builder(ALL_ARGS).build());

      enumBuilder.addField(FieldSpec.builder(
              ClassName.get("java.lang", "String"), "label", Modifier.PRIVATE, Modifier.FINAL)
          .build());

      enumBuilder.addField(FieldSpec.builder(
              ClassName.get("java.lang", "String"), "code", Modifier.PRIVATE, Modifier.FINAL)
          .addAnnotation(AnnotationSpec.builder(ClassName.get(JsonValue.class)).build())
          .build());
    } else {
      // Simple shape: single label arg, no separate code needed.
      enumBuilder
          .addAnnotation(AnnotationSpec.builder(REQ_ARGS).build())
          .addAnnotation(AnnotationSpec.builder(GETTER).build());

      enumBuilder.addField(FieldSpec.builder(
              ClassName.get("java.lang", "String"), "label", Modifier.PRIVATE, Modifier.FINAL)
          .build());
    }

    // Constants sorted by displayOrder
    List<FixedListModel.Item> sorted = new ArrayList<>(fl.getItems());
    sorted.sort(Comparator.comparingInt(item -> item.getDisplayOrder() != null
        ? item.getDisplayOrder() : 0));

    for (FixedListModel.Item item : sorted) {
      TypeSpec.Builder constantBuilder = TypeSpec.anonymousClassBuilder(
          needsCodeField ? "$S, $S" : "$S",
          needsCodeField ? new Object[]{item.getLabel(), item.getCode()}
              : new Object[]{item.getLabel()});
      enumBuilder.addEnumConstant(item.getJavaConstant(), constantBuilder.build());
    }

    // getLabel() is generated by @Getter on the "label" field in both shapes.
    // getCode() is also generated by @Getter when needsCodeField is true.

    TypeSpec enumSpec = enumBuilder.build();
    return JavaFile.builder(pkg, enumSpec)
        .skipJavaLangImports(true)
        .indent("    ")
        .build();
  }

  // -----------------------------------------------------------------------
  // State enum
  // -----------------------------------------------------------------------

  private JavaFile emitState(List<StateModel> states, String pkg, String banner) {
    TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder("State")
        .addModifiers(Modifier.PUBLIC)
        .addJavadoc(banner);

    for (StateModel state : states) {
      boolean hasLabel = state.getName() != null && !state.getName().isEmpty();
      boolean hasTitleDisplay =
          state.getTitleDisplay() != null && !state.getTitleDisplay().isEmpty();
      // The SDK's StateGenerator defaults a state's Description to its Name unless @CCD(description)
      // overrides it; emit description only when the input's Description genuinely differs from the
      // Name (or the ID when there is no Name), so a defaulted Description stays absent — matching
      // the STATE_DESCRIPTION comparator rule. Replaces the former overwrite-graft passthrough.
      String effectiveName = hasLabel ? state.getName() : state.getId();
      boolean hasDescription = state.getDescription() != null && !state.getDescription().isEmpty()
          && !state.getDescription().equals(effectiveName);

      TypeSpec.Builder constantBuilder = TypeSpec.anonymousClassBuilder("");
      if (hasLabel || hasTitleDisplay || hasDescription) {
        AnnotationSpec.Builder ccdAnn = AnnotationSpec.builder(CCD.class);
        if (hasLabel) {
          ccdAnn.addMember("label", "$S", state.getName());
        }
        if (hasTitleDisplay) {
          ccdAnn.addMember("hint", "$S", state.getTitleDisplay());
        }
        if (hasDescription) {
          ccdAnn.addMember("description", "$S", state.getDescription());
        }
        constantBuilder.addAnnotation(ccdAnn.build());
      }
      enumBuilder.addEnumConstant(state.getId(), constantBuilder.build());
    }

    TypeSpec enumSpec = enumBuilder.build();
    return JavaFile.builder(pkg, enumSpec)
        .skipJavaLangImports(true)
        .indent("    ")
        .build();
  }

  // -----------------------------------------------------------------------
  // UserRole enum
  // -----------------------------------------------------------------------

  private JavaFile emitUserRole(List<RoleModel> roles, String pkg, String banner) {
    TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder("UserRole")
        .addModifiers(Modifier.PUBLIC)
        .addSuperinterface(ClassName.get(HasRole.class))
        .addJavadoc(banner)
        .addAnnotation(AnnotationSpec.builder(GETTER).build())
        .addAnnotation(AnnotationSpec.builder(ALL_ARGS).build());

    enumBuilder.addField(FieldSpec.builder(
            ClassName.get("java.lang", "String"), "role", Modifier.PRIVATE, Modifier.FINAL)
        .build());
    enumBuilder.addField(FieldSpec.builder(
            ClassName.get("java.lang", "String"),
            "caseTypePermissions", Modifier.PRIVATE, Modifier.FINAL)
        .build());

    for (RoleModel role : roles) {
      String perms = role.getCaseTypePermissions() != null ? role.getCaseTypePermissions() : "";
      TypeSpec.Builder constantBuilder =
          TypeSpec.anonymousClassBuilder("$S, $S", role.getId(), perms);
      // Case roles carry a Name/Description on the CaseRoles sheet. The SDK's CaseRoleGenerator
      // reads them from @CCD(label=Name, hint=Description) on the enum constant, defaulting Name to
      // the role ID and Description to "" when absent — so emit @CCD only when the input supplies a
      // Name that differs from the ID, or a non-empty Description, to reproduce the CaseRoles row.
      boolean hasName = role.getName() != null && !role.getName().isEmpty()
          && !role.getName().equals(role.getId());
      boolean hasDescription = role.getDescription() != null && !role.getDescription().isEmpty();
      if (hasName || hasDescription) {
        AnnotationSpec.Builder ccdAnn = AnnotationSpec.builder(CCD.class);
        if (hasName) {
          ccdAnn.addMember("label", "$S", role.getName());
        }
        if (hasDescription) {
          ccdAnn.addMember("hint", "$S", role.getDescription());
        }
        constantBuilder.addAnnotation(ccdAnn.build());
      }
      enumBuilder.addEnumConstant(role.getJavaConstant(), constantBuilder.build());
    }

    // getRole() and getCaseTypePermissions() provided by @Getter on fields above.

    TypeSpec enumSpec = enumBuilder.build();
    return JavaFile.builder(pkg, enumSpec)
        .skipJavaLangImports(true)
        .indent("    ")
        .build();
  }
}
