package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.TypeName;
import java.util.ArrayList;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.converter.model.FieldModel;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Shared helper for building JavaPoet {@link FieldSpec} from a {@link FieldModel}.
 *
 * <p>Used by both {@link CaseDataEmitter} and {@link ComplexTypeEmitter}.
 *
 * <p>Generated by ccd-definition-converter from FieldEmitHelper — do not edit by hand.
 */
final class FieldEmitHelper {

  private final JavaTypeParser typeParser;
  private final String configPackage;

  FieldEmitHelper(String modelPackage, String configPackage) {
    this(modelPackage, configPackage, java.util.Map.of());
  }

  FieldEmitHelper(String modelPackage, String configPackage,
      java.util.Map<String, String> typeFqnOverrides) {
    this.typeParser = new JavaTypeParser(modelPackage, typeFqnOverrides);
    this.configPackage = configPackage;
  }

  /**
   * Builds a {@link FieldSpec} for the given {@link FieldModel}.
   *
   * @param field the field model to emit
   * @return the constructed FieldSpec
   */
  FieldSpec buildField(FieldModel field) {
    TypeName typeName = typeParser.parse(field.getJavaType());
    FieldSpec.Builder fb = FieldSpec.builder(typeName, field.getJavaName(), Modifier.PRIVATE);

    // A synthetic cluster-parent field: emit @JsonUnwrapped(prefix=...) so the SDK flattens the
    // member complex type back to prefixed CCD field IDs. Such a field has no flat CaseField of
    // its own, so it carries neither @JsonProperty nor @CCD.
    if (field.getUnwrapPrefix() != null) {
      fb.addAnnotation(AnnotationSpec.builder(ClassName.get(JsonUnwrapped.class))
          .addMember("prefix", "$S", field.getUnwrapPrefix())
          .build());
      return fb.build();
    }

    // @JsonProperty when javaName differs from CCD id (the linker lower-cases an upper-case leading
    // letter so the member is a resolvable JavaBean property — see buildFieldModel — and sanitises
    // illegal characters; either makes javaName != id).
    if (!field.getJavaName().equals(field.getId())) {
      fb.addAnnotation(AnnotationSpec.builder(ClassName.get(JsonProperty.class))
          .addMember("value", "$S", field.getId())
          .build());
    }

    AnnotationSpec ccdAnnotation = buildCcdAnnotation(field);
    if (ccdAnnotation != null) {
      fb.addAnnotation(ccdAnnotation);
    }

    return fb.build();
  }

  private AnnotationSpec buildCcdAnnotation(FieldModel field) {
    AnnotationSpec.Builder ab = AnnotationSpec.builder(CCD.class);
    boolean hasAny = false;

    if (field.getLabel() != null && !field.getLabel().isEmpty()) {
      ab.addMember("label", "$S", field.getLabel());
      hasAny = true;
    }
    if (field.getHint() != null && !field.getHint().isEmpty()) {
      ab.addMember("hint", "$S", field.getHint());
      hasAny = true;
    }
    if (field.getShowCondition() != null && !field.getShowCondition().isEmpty()) {
      ab.addMember("showCondition", "$S", field.getShowCondition());
      hasAny = true;
    }
    if (field.getRegex() != null && !field.getRegex().isEmpty()) {
      ab.addMember("regex", "$S", field.getRegex());
      hasAny = true;
    }
    if (field.getCategoryId() != null && !field.getCategoryId().isEmpty()) {
      ab.addMember("categoryID", "$S", field.getCategoryId());
      hasAny = true;
    }
    if (Boolean.FALSE.equals(field.getSearchable())) {
      ab.addMember("searchable", "$L", false);
      hasAny = true;
    }
    if (Boolean.TRUE.equals(field.getRetainHiddenValue())) {
      ab.addMember("retainHiddenValue", "$L", true);
      hasAny = true;
    }
    if (field.getMin() != null) {
      ab.addMember("min", "$L", field.getMin());
      hasAny = true;
    }
    if (field.getMax() != null) {
      ab.addMember("max", "$L", field.getMax());
      hasAny = true;
    }
    if (field.getTypeOverride() != null && !field.getTypeOverride().isEmpty()) {
      ab.addMember("typeOverride", "$T.$L",
          ClassName.get(FieldType.class), field.getTypeOverride());
      hasAny = true;
    }
    if (field.getTypeParameterOverride() != null && !field.getTypeParameterOverride().isEmpty()) {
      ab.addMember("typeParameterOverride", "$S", field.getTypeParameterOverride());
      hasAny = true;
    }
    if (field.getGate() != null && !field.getGate().isEmpty()) {
      // The field came from a per-environment overlay fragment: emit @CCD(gate = "[!]ENV_VAR:value")
      // so the SDK includes its rows only when the predicate matches at generation time,
      // reproducing the overlay-only field per environment.
      ab.addMember("gate", "$S", field.getGate());
      hasAny = true;
    }
    if (field.getAccessClassNames() != null && !field.getAccessClassNames().isEmpty()) {
      List<CodeBlock> classRefs = new ArrayList<>();
      for (String cn : field.getAccessClassNames()) {
        classRefs.add(CodeBlock.of("$T.class", ClassName.get(configPackage, cn)));
      }
      CodeBlock arrayBlock = CodeBlock.join(classRefs, ", ");
      ab.addMember("access", "{$L}", arrayBlock);
      hasAny = true;
    }

    return hasAny ? ab.build() : null;
  }

  private FieldEmitHelper() {
    this.typeParser = null;
    this.configPackage = null;
  }
}
