package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import java.util.ArrayList;
import java.util.List;

/**
 * Parses a source-level Java type string into a JavaPoet {@link TypeName}.
 *
 * <p>Handles the subset produced by the linker:
 * <ul>
 *   <li>Primitive wrapper names (String, Integer, …) — qualified from java.lang</li>
 *   <li>Fully-qualified class names (uk.gov.hmcts.ccd.sdk.type.YesOrNo)</li>
 *   <li>Unqualified simple names (Party, ClaimType) — qualified into modelPackage</li>
 *   <li>Generic types with one or more type arguments (java.util.List&lt;X&gt;)</li>
 *   <li>Nested generics (java.util.List&lt;uk.gov.hmcts.ccd.sdk.type.ListValue&lt;Party&gt;&gt;)</li>
 * </ul>
 *
 * <p>Generated by ccd-definition-converter from JavaTypeParser — do not edit by hand.
 */
final class JavaTypeParser {

  private static final java.util.Set<String> JAVA_LANG_TYPES = java.util.Set.of(
      "String", "Integer", "Long", "Double", "Float", "Boolean",
      "Byte", "Short", "Character", "Number", "Object", "Enum");

  private final String modelPackage;

  /**
   * Retrofit: simple name → real FQN for types living outside {@link #modelPackage}.
   */
  private final java.util.Map<String, String> fqnOverrides;

  JavaTypeParser(String modelPackage) {
    this(modelPackage, java.util.Map.of());
  }

  JavaTypeParser(String modelPackage, java.util.Map<String, String> fqnOverrides) {
    this.modelPackage = modelPackage;
    this.fqnOverrides = fqnOverrides != null ? fqnOverrides : java.util.Map.of();
  }

  /**
   * Parses the given source-level type string into a JavaPoet TypeName.
   *
   * @param typeStr the source-level type string, e.g. "String" or
   *     "java.util.List&lt;uk.gov.hmcts.ccd.sdk.type.ListValue&lt;Party&gt;&gt;"
   * @return the corresponding TypeName
   */
  TypeName parse(String typeStr) {
    String trimmed = typeStr.trim();
    int ltIdx = trimmed.indexOf('<');
    if (ltIdx < 0) {
      return rawType(trimmed);
    }
    // Has generics: split into rawPart and args
    String rawPart = trimmed.substring(0, ltIdx).trim();
    String argsStr = trimmed.substring(ltIdx + 1, trimmed.lastIndexOf('>')).trim();
    ClassName raw = toClassName(rawPart);
    List<String> argStrings = splitTopLevelArgs(argsStr);
    TypeName[] args = new TypeName[argStrings.size()];
    for (int ii = 0; ii < argStrings.size(); ii++) {
      args[ii] = parse(argStrings.get(ii));
    }
    return ParameterizedTypeName.get(raw, args);
  }

  private TypeName rawType(String name) {
    return toClassName(name);
  }

  private ClassName toClassName(String name) {
    if (name.contains(".")) {
      // Fully qualified
      int lastDot = name.lastIndexOf('.');
      String pkg = name.substring(0, lastDot);
      String simple = name.substring(lastDot + 1);
      return ClassName.get(pkg, simple);
    }
    // Unqualified — java.lang, then a retrofit FQN override for a type outside modelPackage, else
    // default into modelPackage (generate mode, or a companion type emitted there).
    if (JAVA_LANG_TYPES.contains(name)) {
      return ClassName.get("java.lang", name);
    }
    String override = fqnOverrides.get(name);
    if (override != null) {
      int lastDot = override.lastIndexOf('.');
      return lastDot < 0 ? ClassName.get("", override)
          : ClassName.get(override.substring(0, lastDot), override.substring(lastDot + 1));
    }
    return ClassName.get(modelPackage, name);
  }

  /**
   * Splits a comma-separated generic argument list respecting angle-bracket nesting.
   *
   * @param args the type argument string (without enclosing angle brackets)
   * @return list of individual type argument strings
   */
  static List<String> splitTopLevelArgs(String args) {
    List<String> result = new ArrayList<>();
    int depth = 0;
    int start = 0;
    for (int ii = 0; ii < args.length(); ii++) {
      char ch = args.charAt(ii);
      if (ch == '<') {
        depth++;
      } else if (ch == '>') {
        depth--;
      } else if (ch == ',' && depth == 0) {
        result.add(args.substring(start, ii).trim());
        start = ii + 1;
      }
    }
    String last = args.substring(start).trim();
    if (!last.isEmpty()) {
      result.add(last);
    }
    return result;
  }

  private JavaTypeParser() {
    this.modelPackage = "";
    this.fqnOverrides = java.util.Map.of();
  }
}
