package uk.gov.hmcts.ccd.sdk.bundling.api;

import java.nio.file.Path;
import java.util.List;

/**
 * The PDF representation of one source document, produced by a {@link DocumentHandler}.
 */
public record HandledDocument(Path pdfFile, List<BundleWarning> warnings, boolean generated) {

  public HandledDocument(Path pdfFile, List<BundleWarning> warnings) {
    this(pdfFile, warnings, false);
  }

  public HandledDocument {
    Validate.requireNonNull(pdfFile, "HandledDocument.pdfFile");
    warnings = List.copyOf(Validate.requireNonNull(warnings, "HandledDocument.warnings"));
  }

  /** Creates a handled document with no warnings. */
  public static HandledDocument of(Path pdfFile) {
    return new HandledDocument(pdfFile, List.of(), false);
  }

  /**
   * Creates a handled document whose PDF was generated by the handler rather than converted from
   * the source: the assembler treats it as a generated page (no watermark, no source bookmarks).
   */
  public static HandledDocument generated(Path pdfFile) {
    return new HandledDocument(pdfFile, List.of(), true);
  }
}
