package uk.gov.hmcts.ccd.sdk.ts;

import static java.util.stream.Collectors.joining;
import static uk.gov.hmcts.ccd.sdk.FieldUtils.getCaseFields;
import static uk.gov.hmcts.ccd.sdk.FieldUtils.getFieldId;

import cz.habarta.typescript.generator.Input;
import cz.habarta.typescript.generator.JsonLibrary;
import cz.habarta.typescript.generator.Settings;
import cz.habarta.typescript.generator.TypeScriptGenerator;
import cz.habarta.typescript.generator.TypeScriptOutputKind;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.ResolvedCCDConfig;
import uk.gov.hmcts.ccd.sdk.api.Event;

@Component
public class TypeScriptBindingsGenerator {

  private static final String DTO_TYPES_FILE = "dto-types.ts";
  private static final String CONTRACTS_FILE = "event-contracts.ts";
  private static final String CLIENT_FILE = "client.ts";
  private static final String INDEX_FILE = "index.ts";

  public void writeBindings(File outputFolder, ResolvedCCDConfig<?, ?, ?> config, String moduleName) {
    List<DtoEventContract> contracts = extractContracts(config);
    if (contracts.isEmpty()) {
      return;
    }

    Map<String, Class<?>> dtoTypeNames = indexDtoTypeNames(contracts);
    writeDtoTypes(outputFolder, dtoTypeNames.values());
    writeContracts(outputFolder, contracts, dtoTypeNames, moduleName);
    writeClient(outputFolder);
    writeIndex(outputFolder);
  }

  private List<DtoEventContract> extractContracts(ResolvedCCDConfig<?, ?, ?> config) {
    List<DtoEventContract> result = new ArrayList<>();
    for (Event<?, ?, ?> event : config.getEvents().values()) {
      if (!event.isDtoEvent()) {
        continue;
      }
      List<String> fields = getCaseFields(event.getDtoClass()).stream()
          .map(field -> getFieldId(field))
          .sorted()
          .toList();

      result.add(new DtoEventContract(event.getId(), event.getDtoClass(), event.getDtoPrefix(), fields));
    }
    return result.stream()
        .sorted(Comparator.comparing(DtoEventContract::eventId))
        .toList();
  }

  private Map<String, Class<?>> indexDtoTypeNames(List<DtoEventContract> contracts) {
    Map<String, Class<?>> dtoTypeNames = new LinkedHashMap<>();
    for (DtoEventContract contract : contracts) {
      Class<?> dtoClass = contract.dtoClass();
      Class<?> existing = dtoTypeNames.putIfAbsent(dtoClass.getSimpleName(), dtoClass);
      if (existing != null && !existing.equals(dtoClass)) {
        throw new IllegalStateException(
            "TS bindings cannot emit duplicate DTO type names '%s' from %s and %s. "
                + "Rename one of the DTO classes."
                .formatted(dtoClass.getSimpleName(), existing.getName(), dtoClass.getName()));
      }
    }
    return dtoTypeNames;
  }

  private void writeDtoTypes(File outputFolder, Iterable<Class<?>> dtoClasses) {
    Settings settings = new Settings();
    settings.outputKind = TypeScriptOutputKind.module;
    settings.jsonLibrary = JsonLibrary.jackson2;
    settings.noFileComment = true;

    TypeScriptGenerator generator = new TypeScriptGenerator(settings);
    Set<Type> types = new LinkedHashSet<>();
    dtoClasses.forEach(types::add);
    String generated = generator.generateTypeScript(Input.from(types.toArray(new Type[0])));

    writeFile(outputFolder, DTO_TYPES_FILE, generated);
  }

  private void writeContracts(File outputFolder,
                              List<DtoEventContract> contracts,
                              Map<String, Class<?>> dtoTypeNames,
                              String moduleName) {
    String imports = dtoTypeNames.keySet().stream()
        .sorted()
        .collect(joining(", "));

    String eventDtoMappings = contracts.stream()
        .map(contract -> "  \"" + contract.eventId() + "\": "
            + Objects.requireNonNull(contract.dtoClass()).getSimpleName() + ";")
        .collect(joining("\n"));

    String contractEntries = contracts.stream()
        .map(contract -> "  \"" + contract.eventId() + "\": {\n"
            + "    prefix: \"" + contract.prefix() + "\",\n"
            + "    fields: [" + quotedList(contract.fields()) + "],\n"
            + "  },")
        .collect(joining("\n"));

    String contents = """
        // Generated by CCD SDK. Do not edit manually.
        // Module: %s
        import type { %s } from "./dto-types";

        export interface EventDtoMap {
        %s
        }

        export type EventId = keyof EventDtoMap;

        export const eventContracts = {
        %s
        } as const;
        """.formatted(moduleName, imports, eventDtoMappings, contractEntries);

    writeFile(outputFolder, CONTRACTS_FILE, contents);
  }

  private void writeClient(File outputFolder) {
    String contents = """
        // Generated by CCD SDK. Do not edit manually.
        import { eventContracts, type EventDtoMap, type EventId } from "./event-contracts";

        export interface CcdTransport {
          get(url: string, headers: Record<string, string>): Promise<unknown>;
          post(url: string, data: unknown, headers: Record<string, string>): Promise<unknown>;
        }

        export interface CcdClientConfig {
          baseUrl: string;
          caseTypeId: string;
          getAuthHeaders: () => Promise<Record<string, string>> | Record<string, string>;
          transport: CcdTransport;
        }

        export interface EventFlow<K extends EventId> {
          readonly eventId: K;
          readonly data: EventDtoMap[K];
          submit(data: EventDtoMap[K]): Promise<unknown>;
        }

        interface EventTriggerResponse {
          token?: string;
          case_details?: {
            case_data?: Record<string, unknown>;
          };
        }

        type EventAccessor = {
          [K in EventId]: {
            start(caseId?: string | number): Promise<EventFlow<K>>;
          };
        };

        export class GeneratedCcdClient {
          readonly events: EventAccessor;

          constructor(private readonly config: CcdClientConfig) {
            this.events = this.buildEvents();
          }

          private buildEvents(): EventAccessor {
            const entries = Object.keys(eventContracts).map(eventId => [
              eventId,
              {
                start: (caseId?: string | number) => this.start(eventId as EventId, caseId),
              },
            ]);
            return Object.fromEntries(entries) as EventAccessor;
          }

          private async start<K extends EventId>(eventId: K, caseId?: string | number): Promise<EventFlow<K>> {
            const headers = await this.config.getAuthHeaders();
            const triggerUrl = this.buildEventTriggerUrl(eventId, caseId);
            const triggerResponse = (await this.config.transport.get(triggerUrl, headers)) as EventTriggerResponse;
            const token = triggerResponse.token;
            if (!token) {
              throw new Error(`Missing event token for ${String(eventId)}`);
            }

            const data = this.unmarshal(eventId, triggerResponse.case_details?.case_data ?? {});

            return {
              eventId,
              data,
              submit: (updatedData: EventDtoMap[K]) => this.submit(eventId, token, updatedData, headers, caseId),
            };
          }

          private async submit<K extends EventId>(
            eventId: K,
            eventToken: string,
            data: EventDtoMap[K],
            headers: Record<string, string>,
            caseId?: string | number
          ): Promise<unknown> {
            const payload = {
              data: this.marshal(eventId, data),
              event: { id: eventId },
              event_token: eventToken,
              ignore_warning: false,
            };
            return this.config.transport.post(this.buildEventSubmitUrl(caseId), payload, headers);
          }

          private buildEventTriggerUrl(eventId: EventId, caseId?: string | number): string {
            if (caseId) {
              return `${this.config.baseUrl}/cases/${caseId}/event-triggers/${eventId}?ignore-warning=false`;
            }
            return `${this.config.baseUrl}/case-types/${this.config.caseTypeId}/event-triggers/${eventId}`;
          }

          private buildEventSubmitUrl(caseId?: string | number): string {
            if (caseId) {
              return `${this.config.baseUrl}/cases/${caseId}/events`;
            }
            return `${this.config.baseUrl}/case-types/${this.config.caseTypeId}/cases`;
          }

          private marshal<K extends EventId>(eventId: K, data: EventDtoMap[K]): Record<string, unknown> {
            const { prefix, fields } = eventContracts[eventId];
            const source = data as unknown as Record<string, unknown>;
            const marshalled: Record<string, unknown> = {};
            for (const field of fields) {
              if (Object.prototype.hasOwnProperty.call(source, field)) {
                marshalled[prefix + capitalise(field)] = source[field];
              }
            }
            return marshalled;
          }

          private unmarshal<K extends EventId>(eventId: K, ccdData: Record<string, unknown>): EventDtoMap[K] {
            const { prefix, fields } = eventContracts[eventId];
            const unmarshalled: Record<string, unknown> = {};
            for (const field of fields) {
              const prefixedField = prefix + capitalise(field);
              if (Object.prototype.hasOwnProperty.call(ccdData, prefixedField)) {
                unmarshalled[field] = ccdData[prefixedField];
              }
            }
            return unmarshalled as unknown as EventDtoMap[K];
          }
        }

        function capitalise(value: string): string {
          return value.length === 0 ? value : value[0].toUpperCase() + value.slice(1);
        }
        """;

    writeFile(outputFolder, CLIENT_FILE, contents);
  }

  private void writeIndex(File outputFolder) {
    String contents = """
        // Generated by CCD SDK. Do not edit manually.
        export * from "./dto-types";
        export * from "./event-contracts";
        export * from "./client";
        """;
    writeFile(outputFolder, INDEX_FILE, contents);
  }

  private String quotedList(List<String> values) {
    return values.stream().map(value -> "\"" + value + "\"").collect(joining(", "));
  }

  private void writeFile(File outputFolder, String filename, String contents) {
    try {
      Files.createDirectories(outputFolder.toPath());
      Files.writeString(outputFolder.toPath().resolve(filename), contents, StandardCharsets.UTF_8);
    } catch (IOException e) {
      throw new IllegalStateException("Unable to write TS bindings file %s".formatted(filename), e);
    }
  }

  private record DtoEventContract(String eventId, Class<?> dtoClass, String prefix, List<String> fields) {
  }
}
