package uk.gov.hmcts.test.config.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.test.model.UserRole;

/**
 * Generated by ccd-definition-converter from AuthorisationCaseField — do not edit by hand.
 */
public class CaseworkerAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_TEST, Permission.C);
        grants.put(UserRole.CASEWORKER_TEST, Permission.R);
        grants.put(UserRole.CASEWORKER_TEST, Permission.U);
        return grants;
    }
}