package uk.gov.hmcts.test.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.test.config.access.CaseworkerAccess;

/**
 * Generated by ccd-definition-converter from CaseField — do not edit by hand.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CaseData {
    @CCD(
            label = "Claimant Name"
    )
    private String claimantName;

    @JsonProperty("some_field_id")
    @CCD(
            label = "Some Field"
    )
    private String someFieldId;

    private List<ListValue<TestAddress>> parties;

    @CCD(
            label = "Notes",
            typeOverride = FieldType.TextArea
    )
    private String notes;

    @CCD(
            label = "Claim Type",
            typeParameterOverride = "ClaimType"
    )
    private String claimType;

    @CCD(
            label = "Rich Field",
            hint = "Enter a value",
            showCondition = "claimantName!=\"\"",
            regex = "[A-Z]+",
            categoryID = "evidence",
            searchable = false,
            retainHiddenValue = true,
            min = 1,
            max = 100,
            access = {CaseworkerAccess.class}
    )
    private String richField;

    @CCD(
            label = "A label",
            typeOverride = FieldType.Label
    )
    private String labelField;
}