package uk.gov.hmcts.test.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@Getter
@AllArgsConstructor
public enum ClaimType implements HasLabel {
    A_CODE("Label for A", "A-CODE"),

    B_CODE("Label for B", "B-CODE");

    private final String label;

    @JsonValue
    private final String code;
}