package uk.gov.hmcts.test.model;

import uk.gov.hmcts.ccd.sdk.api.CCD;

/**
 * Generated by ccd-definition-converter from State — do not edit by hand.
 */
public enum State {
    @CCD(
            label = "Case Open",
            hint = "# ${[CASE_REFERENCE]}"
    )
    Open,

    @CCD(
            label = "Case Closed"
    )
    Closed
}