package uk.gov.hmcts.test.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasRole;

/**
 * Generated by ccd-definition-converter from AuthorisationCaseType/CaseRoles — do not edit by hand.
 */
@Getter
@AllArgsConstructor
public enum UserRole implements HasRole {
    CASEWORKER_TEST("caseworker-test", "CRU"),

    CREATOR("[CREATOR]", "");

    private final String role;

    private final String caseTypePermissions;
}