package uk.gov.hmcts.test.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FixedLists — do not edit by hand.
 */
@ComplexType(
        name = "YesOrNoChoice",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum YesOrNoChoice implements HasLabel {
    YES("Yes"),

    NO("No");

    private final String label;
}