/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ccd.sdk;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.Task;

/**
 * A simple 'hello world' plugin.
 */
public class CcdSdkPlugin implements Plugin<Project> {
    public void apply(Project project) {
        Task generate = project.getTasks().create("generateCCDConfig", ConfigGenerator.class);
        Task javaCompile = project.getTasks().getByName("compileJava");
        generate.dependsOn(javaCompile);
    }
}
