package uk.gov.hmcts.ccd.sdk.converter.emit.config;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Conditionally emits a minimal {@code @SpringBootApplication} entry point into the config
 * package. Only active when {@link uk.gov.hmcts.ccd.sdk.converter.api.ConversionOptions
 * #isEmitApplication()} returns {@code true}.
 *
 * <p><b>Not used for output destined for a service's source tree.</b> A service already has its
 * own {@code @SpringBootApplication}, and the SDK's {@code generateCCDConfig} task requires
 * exactly one such class on the classpath under {@code ccd.rootPackage} — a second one alongside
 * the service's real application class breaks that lookup. The generated {@code CCDConfig} beans
 * live under the service's own base package, so its existing application's component scan
 * discovers them without any extra wiring (see the retrofit/generate-mode docs). This emitter
 * exists only for ad-hoc standalone runs and internal test harnesses (the round-trip tests, which
 * compile generated sources in isolation with no service application to lean on).
 */
public class ApplicationEmitter implements SourceEmitter {

  /**
   * Generates the {@code ConverterGeneratedApplication} class when the option is enabled.
   *
   * @param model the linked case type model (used only for the case type ID in javadoc)
   * @param context packages and options
   * @return a single-element list when {@code emitApplication} is {@code true}; empty otherwise
   */
  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    if (!context.getOptions().isEmitApplication()) {
      return List.of();
    }

    ClassName springBootApplication =
        ClassName.get("org.springframework.boot.autoconfigure", "SpringBootApplication");
    ClassName springApplication =
        ClassName.get("org.springframework.boot", "SpringApplication");

    MethodSpec main = MethodSpec.methodBuilder("main")
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(void.class)
        .addParameter(String[].class, "args")
        .addJavadoc(
            "Application entry point.\n"
                + "\n"
                + "@param args command-line arguments forwarded to Spring Boot\n")
        .addStatement("$T.run($T.class, args)", springApplication,
            ClassName.get(context.configPackage(), "ConverterGeneratedApplication"))
        .build();

    // The SDK generator beans live in uk.gov.hmcts.ccd.sdk(.generator); the generated CCDConfig /
    // Access beans live in the config package. Both must be component-scanned so the standalone run
    // resolves the CCDConfig beans and the CCDDefinitionGenerator. The MODEL package is deliberately
    // NOT scanned: model classes are POJOs the SDK reflects by type (referenced by import from the
    // CCDConfig beans, loaded by the classloader), never Spring-wired. In generate mode the model
    // package holds only generated data classes so scanning it was harmless; in retrofit mode it is
    // the real service package full of @Component/@Service beans (Civil's InterlocutoryJudgementDoc-
    // Mapper etc.) whose own dependencies are not on the scan path, so scanning it made the context
    // fail to start. Dropping it is safe for both modes (the config package is scanned directly, even
    // when it is a sub-package of the model package).
    //
    // Exclude the persistence autoconfigurations. generateCCDConfig only needs the CCDConfig beans
    // and the CCDDefinitionGenerator — never a database. But in retrofit mode this class runs on the
    // real service's classpath (Spring Data JPA, Flyway, a JDBC driver, the service's
    // application.yaml), so Spring Boot would otherwise stand up a DataSource / EntityManagerFactory
    // / Flyway migrator and fail with no database to connect to (Civil: "Driver … claims to not
    // accept jdbcUrl jdbc:postgresql://:/cmc"). The same applies to Spring Security / OAuth2 client
    // autoconfiguration: the service's application.yaml carries client-registration properties, so
    // Spring builds a clientRegistrationRepository whose issuer/redirect URI reads an unresolved
    // ${idam.web.url} placeholder and fails ("Illegal character in path … ${idam.web.url}/o"). The
    // generator authenticates nothing, so those are excluded too. Excluding by name (excludeName, not
    // the typed exclude) keeps the emitter free of a compile dependency on those classes; an exclude
    // of an autoconfiguration not on the classpath is silently ignored, so each is a no-op for a
    // service that does not carry that dependency. Web/servlet autoconfiguration is additionally
    // switched off by running the generated app with WebApplicationType.NONE (the pipeline sets
    // spring.main.web-application-type=none), so no embedded server or web-security chain starts.
    AnnotationSpec springBootApp = AnnotationSpec.builder(springBootApplication)
        .addMember("scanBasePackages", "{$S, $S}",
            "uk.gov.hmcts.ccd.sdk", context.configPackage())
        .addMember("excludeName", "{$S, $S, $S, $S, $S, $S, $S, $S, $S, $S, $S, $S}",
            "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration",
            "org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration",
            "org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration",
            "org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration",
            "org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration",
            "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration",
            "org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration",
            "org.springframework.boot.autoconfigure.security.oauth2.resource.OAuth2ResourceServerAutoConfiguration",
            "org.springframework.boot.autoconfigure.security.oauth2.client.reactive."
                + "ReactiveOAuth2ClientAutoConfiguration",
            "org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration",
            "uk.gov.hmcts.reform.idam.client.IdamClient",
            "uk.gov.hmcts.reform.idam.client.OAuth2Configuration")
        .build();

    TypeSpec appClass = TypeSpec.classBuilder("ConverterGeneratedApplication")
        .addModifiers(Modifier.PUBLIC)
        .addAnnotation(springBootApp)
        .addJavadoc(
            "Generated by ccd-definition-converter — do not edit by hand.\n"
                + "\n"
                + "<p>Minimal Spring Boot entry point for running the CCD config generator\n"
                + "standalone for case type {@code $L}.\n", model.getCaseTypeId())
        .addMethod(main)
        .build();

    JavaFile file = JavaFile.builder(context.configPackage(), appClass)
        .indent("    ")
        .skipJavaLangImports(true)
        .build();

    return List.of(file);
  }
}
