package uk.gov.hmcts.ccd.sdk.converter.emit.config;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Conditionally emits a minimal {@code @SpringBootApplication} entry point into the config
 * package. Only active when {@link uk.gov.hmcts.ccd.sdk.converter.api.ConversionOptions
 * #isEmitApplication()} returns {@code true}.
 *
 * <p><b>Not used for output destined for a service's source tree.</b> A service already has its
 * own {@code @SpringBootApplication}, and the SDK's {@code generateCCDConfig} task requires
 * exactly one such class on the classpath under {@code ccd.rootPackage} — a second one alongside
 * the service's real application class breaks that lookup. The generated {@code CCDConfig} beans
 * live under the service's own base package, so its existing application's component scan
 * discovers them without any extra wiring (see the retrofit/generate-mode docs). This emitter
 * exists only for ad-hoc standalone runs and internal test harnesses (the round-trip tests, which
 * compile generated sources in isolation with no service application to lean on).
 */
public class ApplicationEmitter implements SourceEmitter {

  /**
   * Generates the {@code ConverterGeneratedApplication} class when the option is enabled.
   *
   * @param model the linked case type model (used only for the case type ID in javadoc)
   * @param context packages and options
   * @return a single-element list when {@code emitApplication} is {@code true}; empty otherwise
   */
  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    if (!context.getOptions().isEmitApplication()) {
      return List.of();
    }

    ClassName springBootConfiguration =
        ClassName.get("org.springframework.boot", "SpringBootConfiguration");
    ClassName componentScan =
        ClassName.get("org.springframework.context.annotation", "ComponentScan");
    ClassName componentScans =
        ClassName.get("org.springframework.context.annotation", "ComponentScans");
    ClassName filterType =
        ClassName.get("org.springframework.context.annotation", "FilterType");
    ClassName ccdConfig =
        ClassName.get("uk.gov.hmcts.ccd.sdk.api", "CCDConfig");
    ClassName importAnnotation =
        ClassName.get("org.springframework.context.annotation", "Import");
    ClassName definitionGenerator =
        ClassName.get("uk.gov.hmcts.ccd.sdk", "CCDDefinitionGenerator");
    ClassName springApplication =
        ClassName.get("org.springframework.boot", "SpringApplication");

    MethodSpec main = MethodSpec.methodBuilder("main")
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(void.class)
        .addParameter(String[].class, "args")
        .addJavadoc(
            "Application entry point.\n"
                + "\n"
                + "@param args command-line arguments forwarded to Spring Boot\n")
        .addStatement("$T.run($T.class, args)", springApplication,
            ClassName.get(context.configPackage(), "ConverterGeneratedApplication"))
        .build();

    // The SDK generator beans live in uk.gov.hmcts.ccd.sdk.generator; the generated CCDConfig /
    // Access beans live in the config package. Both must be component-scanned so the standalone run
    // resolves the CCDConfig beans and the generator's writers. The MODEL package is deliberately
    // NOT scanned: model classes are POJOs the SDK reflects by type (referenced by import from the
    // CCDConfig beans, loaded by the classloader), never Spring-wired. In generate mode the model
    // package holds only generated data classes so scanning it was harmless; in retrofit mode it is
    // the real service package full of @Component/@Service beans (Civil's InterlocutoryJudgementDoc-
    // Mapper etc.) whose own dependencies are not on the scan path, so scanning it made the context
    // fail to start. Dropping it is safe for both modes (the config package is scanned directly, even
    // when it is a sub-package of the model package).
    //
    // The config-package scan takes only CCDConfig implementations, with default filters OFF. Naming
    // a package is not enough to bound what a scan picks up, because a service can own beans INSIDE
    // the companion root package: sscs-common declares its model at ...sscs.ccd.domain, so the derived
    // root package is ...sscs.ccd — which also contains the library's own ...sscs.ccd.client.CcdClient
    // and ...sscs.ccd.config. An unfiltered scan instantiated CcdClient and failed the context on its
    // CcdRequestDetails constructor parameter, a bean the service supplies from application config it
    // has no reason to provide for a generation run. Filtering by type rather than by package makes the
    // scan pick up exactly what generation consumes, whatever else happens to share the package —
    // every emitted config class implements CCDConfig, and the access classes are referenced by type
    // from those configs rather than autowired.
    //
    // NO AUTOCONFIGURATION AT ALL — @SpringBootConfiguration + @ComponentScan rather than
    // @SpringBootApplication (which is those two plus @EnableAutoConfiguration).
    // generateCCDConfig needs exactly two things from the context: the generated CCDConfig beans and
    // the SDK's CCDDefinitionGenerator. Both are plain @Component/@Configuration classes with no
    // property injection and no infrastructure dependency (JsonUtils builds its own ObjectMapper),
    // which the round-trip harness proves: GeneratorRunner drives all seven fixtures through a bare
    // AnnotationConfigApplicationContext that only component-scans, with no Boot and no
    // autoconfiguration whatsoever.
    //
    // Autoconfiguration is therefore pure liability in retrofit mode, where this class runs on the
    // real service's full classpath and application.yaml. Every attempt to keep it and exclude the
    // harmful parts by name failed on the NEXT service, because the harmful set is whatever jars that
    // service happens to pin: DataSource/Hibernate/Flyway (Civil: "Driver … claims to not accept
    // jdbcUrl jdbc:postgresql://:/cmc"), Spring Security/OAuth2 client (an unresolved ${idam.web.url}
    // placeholder: "Illegal character in path … ${idam.web.url}/o"), then a THIRD-PARTY
    // autoconfiguration whose own beans are unsatisfiable — probate's lifeevents client demanding a
    // ClientRegistrationRepository that excluding the OAuth2 autoconfiguration had just removed. The
    // blocklist could not converge: naming a third-party class is itself unsafe, since Spring's
    // AutoConfigurationImportSelector.handleInvalidExcludes fails the context outright when an
    // excluded class is on the classpath but is not an autoconfiguration candidate, and whether it
    // counts as one depends on the pinned version (idam-java-client 3.0.5 ships the Boot 3
    // AutoConfiguration.imports entry; 2.1.2 registers only via legacy spring.factories, so naming it
    // hard-failed on prl and worked everywhere else).
    //
    // Importing nothing removes the entire failure class rather than its current instance: no
    // DataSource, no Flyway, no security chain, no third-party client beans, no embedded server —
    // and nothing left for a future service's dependencies to drag in.
    //
    // The scan is uk.gov.hmcts.ccd.sdk.GENERATOR, not the root sdk package, for the same reason:
    // the root package also holds the runtime callback layer (CallbackController, CcdCallbackExecutor)
    // whose constructor takes an @Autowired ObjectMapper. With autoconfiguration gone there is no
    // Jackson bean to satisfy it, so scanning the root package failed the context on probate
    // ("Error creating bean with name 'callbackController' … No qualifying bean of type ObjectMapper").
    // Those beans serve live callback traffic and are irrelevant to a one-shot generation run.
    // CCDDefinitionGenerator itself sits in the ROOT package, so it is @Imported by type rather than
    // reached by the scan — it is a @Configuration class, and its only collaborator
    // (JSONConfigGenerator) is in .generator along with the 24 sheet writers, none of which take
    // anything but each other (JsonUtils builds its own ObjectMapper internally).
    AnnotationSpec bootConfiguration = AnnotationSpec.builder(springBootConfiguration).build();
    AnnotationSpec generatorScan = AnnotationSpec.builder(componentScan)
        .addMember("basePackages", "$S", "uk.gov.hmcts.ccd.sdk.generator")
        .build();
    AnnotationSpec configScan = AnnotationSpec.builder(componentScan)
        .addMember("basePackages", "$S", context.configPackage())
        .addMember("useDefaultFilters", "false")
        .addMember("includeFilters", "@$T.Filter(type = $T.ASSIGNABLE_TYPE, classes = $T.class)",
            componentScan, filterType, ccdConfig)
        .build();
    AnnotationSpec scan = AnnotationSpec.builder(componentScans)
        .addMember("value", "{$L, $L}", generatorScan, configScan)
        .build();
    AnnotationSpec importGenerator = AnnotationSpec.builder(importAnnotation)
        .addMember("value", "$T.class", definitionGenerator)
        .build();

    TypeSpec appClass = TypeSpec.classBuilder("ConverterGeneratedApplication")
        .addModifiers(Modifier.PUBLIC)
        .addAnnotation(bootConfiguration)
        .addAnnotation(scan)
        .addAnnotation(importGenerator)
        .addJavadoc(
            "Generated by ccd-definition-converter — do not edit by hand.\n"
                + "\n"
                + "<p>Minimal Spring Boot entry point for running the CCD config generator\n"
                + "standalone for case type {@code $L}.\n", model.getCaseTypeId())
        .addMethod(main)
        .build();

    JavaFile file = JavaFile.builder(context.configPackage(), appClass)
        .indent("    ")
        .skipJavaLangImports(true)
        .build();

    return List.of(file);
  }
}
