package uk.gov.hmcts.ccd.sdk.converter.emit.config;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.ir.AuthorisationRows;
import uk.gov.hmcts.ccd.sdk.converter.ir.Columns;
import uk.gov.hmcts.ccd.sdk.converter.ir.SheetRow;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.RoleModel;
import uk.gov.hmcts.ccd.sdk.converter.model.SearchFieldModel;
import uk.gov.hmcts.ccd.sdk.converter.model.TabModel;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapAction;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapCategory;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapEntry;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Emits the non-event {@code CCDConfig} classes for the case type, <b>split by concern</b> into
 * separate discoverable beans mirroring the reference services (finding #6) rather than one
 * {@code CoreConfig} monolith:
 * <ul>
 *   <li>{@code <Prefix>CaseType} — case-type/jurisdiction identity, definition flags, banner and
 *       {@code explicitStateGrants()};</li>
 *   <li>{@code <Prefix>Grants} — state grants and per-member complex-type grants;</li>
 *   <li>{@code <Prefix>Tabs} — case-type tabs;</li>
 *   <li>{@code <Prefix>WorkBasket} — work-basket input/result fields;</li>
 *   <li>{@code <Prefix>Search} — search input/result, search-cases, search criteria and search
 *       parties;</li>
 *   <li>{@code <Prefix>NoticeOfChange} — challenge questions;</li>
 *   <li>{@code <Prefix>RoleToAccessProfiles} — role-to-access-profile mappings;</li>
 *   <li>{@code <Prefix>Categories} — document categories.</li>
 * </ul>
 * Each bean is emitted only when its concern carries content ({@code CaseType} always emits). The
 * SDK aggregates every {@code CCDConfig} bean onto one builder before generating, so the split is
 * behaviourally identical to the former single class. Events are handled by
 * {@link EventsConfigEmitter}.
 */
public class CoreConfigEmitter implements SourceEmitter {

  /**
   * Generates the split per-concern config classes.
   *
   * @param model the linked case type model
   * @param context packages and options
   * @return one file per non-empty concern (plus any complex-grant helper classes)
   */
  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    String configPkg = context.configPackage();
    String caseTypeId = model.getCaseTypeId();
    String prefix = Names.toClassName(caseTypeId);

    // In generate mode these resolve to the freshly generated <modelPackage>.{CaseData,State,
    // UserRole}; in retrofit mode caseData/state point at the team's existing classes (EmitContext),
    // so the emitted CCDConfig binds to the model the team's callbacks already use.
    ClassName caseData = context.caseDataClass();
    ClassName state = context.stateClass();
    ClassName userRole = context.userRoleClass();
    ClassName configBuilder = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "ConfigBuilder");
    ClassName permission = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "Permission");
    ClassName ccdConfig = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "CCDConfig");

    ParameterizedTypeName builderType =
        ParameterizedTypeName.get(configBuilder, caseData, state, userRole);
    ParameterizedTypeName configType =
        ParameterizedTypeName.get(ccdConfig, caseData, state, userRole);

    Map<String, String> roleConstants = buildRoleConstants(model);
    List<JavaFile> files = new ArrayList<>();

    // --- CaseType: identity, jurisdiction, definition flags, banner, explicitStateGrants ---
    CodeBlock.Builder caseTypeBody = CodeBlock.builder();
    emitCaseTypeIdentity(model, caseTypeBody);
    files.add(configFile(configPkg, prefix + "CaseType", configType, builderType, caseTypeBody.build(),
        context, caseTypeId, "case-type and jurisdiction identity, definition flags and banner"));

    // --- Grants: state grants + complex-type grants (the latter split into helper classes) ---
    List<TypeSpec> grantHelperClasses = new ArrayList<>();
    List<ClassName> complexGrantHelpers = buildComplexTypeGrantHelpers(
        model, context, caseData, state, userRole, permission, builderType, configPkg,
        grantHelperClasses);
    CodeBlock.Builder grantsBody = CodeBlock.builder();
    emitStateGrants(model, grantsBody, state, userRole, permission, roleConstants, context);
    for (ClassName helper : complexGrantHelpers) {
      grantsBody.addStatement("$T.apply(builder)", helper);
    }
    if (!grantsBody.build().isEmpty()) {
      for (TypeSpec helper : grantHelperClasses) {
        files.add(JavaFile.builder(configPkg, helper).indent("    ")
            .skipJavaLangImports(true).build());
      }
      files.add(configFile(configPkg, prefix + "Grants", configType, builderType,
          grantsBody.build(), context, caseTypeId, "state and complex-type grants"));
    }

    // --- Tabs ---
    CodeBlock.Builder tabsBody = CodeBlock.builder();
    emitTabs(model, tabsBody, caseData, userRole, roleConstants, context);
    addIfPresent(files, configPkg, prefix + "Tabs", configType, builderType, tabsBody.build(),
        context, caseTypeId, "case-type tabs");

    // --- WorkBasket input / result ---
    CodeBlock.Builder workBasketBody = CodeBlock.builder();
    emitSearchBuilder(workBasketBody, "workBasketInputFields", model.getWorkBasketInputFields(),
        userRole, roleConstants, context, "WorkBasketInputFields");
    emitSearchBuilder(workBasketBody, "workBasketResultFields", model.getWorkBasketResultFields(),
        userRole, roleConstants, context, "WorkBasketResultFields");
    addIfPresent(files, configPkg, prefix + "WorkBasket", configType, builderType,
        workBasketBody.build(), context, caseTypeId, "work-basket input and result fields");

    // --- Search input / result, search-cases, search criteria, search parties ---
    CodeBlock.Builder searchBody = CodeBlock.builder();
    emitSearchBuilder(searchBody, "searchInputFields", model.getSearchInputFields(),
        userRole, roleConstants, context, "SearchInputFields");
    emitSearchBuilder(searchBody, "searchResultFields", model.getSearchResultFields(),
        userRole, roleConstants, context, "SearchResultFields");
    emitSearchCasesBuilder(searchBody, model.getSearchCasesResultFields(),
        userRole, roleConstants, context);
    emitSearchCriteria(model, searchBody);
    emitSearchParties(model, searchBody);
    addIfPresent(files, configPkg, prefix + "Search", configType, builderType, searchBody.build(),
        context, caseTypeId, "search input/result, search-cases, criteria and parties");

    // --- Notice of Change ---
    CodeBlock.Builder nocBody = CodeBlock.builder();
    emitNoc(model, nocBody, caseData, userRole, roleConstants, context);
    addIfPresent(files, configPkg, prefix + "NoticeOfChange", configType, builderType,
        nocBody.build(), context, caseTypeId, "Notice of Change challenge questions");

    // --- Role-to-access-profiles ---
    CodeBlock.Builder rtapBody = CodeBlock.builder();
    emitRoleToAccessProfiles(model, rtapBody, userRole, roleConstants, context);
    addIfPresent(files, configPkg, prefix + "RoleToAccessProfiles", configType, builderType,
        rtapBody.build(), context, caseTypeId, "role-to-access-profile mappings");

    // --- Categories ---
    CodeBlock.Builder categoriesBody = CodeBlock.builder();
    emitCategories(model, categoriesBody, userRole, roleConstants, context);
    addIfPresent(files, configPkg, prefix + "Categories", configType, builderType,
        categoriesBody.build(), context, caseTypeId, "document categories");

    return files;
  }

  /**
   * Emits the case-type identity block (always present): the sole {@code caseType(...)} bean.
   */
  private void emitCaseTypeIdentity(CaseTypeModel model, CodeBlock.Builder cb) {
    cb.addStatement("builder.caseType($S, $S, $S)",
        model.getCaseTypeId(), model.getCaseTypeName(), model.getCaseTypeDescription());
    cb.addStatement("builder.jurisdiction($S, $S, $S)",
        model.getJurisdictionId(), model.getJurisdictionName(), model.getJurisdictionDescription());
    // Definition-time flags with no per-environment variation: the CaseType EnableForDeletion and
    // Jurisdiction Shuttered columns are emitted via their (default no-op) builder switches rather
    // than grafted; the generator writes them onto the CaseType/Jurisdiction rows.
    if (model.isEnableForDeletion()) {
      cb.addStatement("builder.enableForDeletion()");
    }
    if (model.isJurisdictionShuttered()) {
      cb.addStatement("builder.jurisdictionShuttered()");
    }
    // CaseType PrintableDocumentsUrl: emitted via the builder switch (default no-op) rather than
    // grafted; the generator writes it onto the CaseType row. Placeholders (${CCD_DEF_*}) are
    // carried verbatim in the string literal, so the migrated service's webhook round-trips.
    if (model.getPrintableDocumentsUrl() != null && !model.getPrintableDocumentsUrl().isEmpty()) {
      cb.addStatement("builder.printableDocumentsUrl($S)", model.getPrintableDocumentsUrl());
    }
    // Stamp JurisdictionID on every generated CaseRoles row when the input carried it on all of
    // them (all-or-nothing switch; see DefaultDefinitionLinker.allCaseRolesCarryJurisdiction).
    if (model.isEmitCaseRoleJurisdiction()) {
      cb.addStatement("builder.emitCaseRoleJurisdiction()");
    }
    // The jurisdiction-wide XUI service-notice banner (one per jurisdiction), reproduced via the
    // builder rather than a whole-sheet passthrough.
    emitBanner(model, cb);
    // No setCallbackHost is emitted: the converter emits no SDK callback wiring at all, so the
    // generator writes no CallBackURL* columns for the callback host to fill; every callback
    // column is instead carried through verbatim via passthrough (see DefaultDefinitionLinker).
    // ConfigBuilderImpl defaults callbackHost to "" and never requires it to be set.
    // A converted config's contract is exact reproduction of the input's AuthorisationCaseState.
    // Without this switch the SDK broadens state permissions by unioning every event's grants
    // (AuthorisationCaseStateGenerator), producing wider rows than the input's hand-tuned ones.
    // <Prefix>Grants reproduces the input rows verbatim and is the sole ACS source.
    cb.addStatement("builder.explicitStateGrants()");
  }

  /** Appends a per-concern config bean file when the concern produced any statements. */
  private void addIfPresent(
      List<JavaFile> files, String configPkg, String className,
      ParameterizedTypeName configType, ParameterizedTypeName builderType, CodeBlock body,
      EmitContext context, String caseTypeId, String concern) {
    if (body.isEmpty()) {
      return;
    }
    files.add(configFile(configPkg, className, configType, builderType, body, context, caseTypeId,
        concern));
  }

  /**
   * Wraps a configure() body in a {@code @Component CCDConfig} bean file.
   */
  private JavaFile configFile(
      String configPkg, String className,
      ParameterizedTypeName configType, ParameterizedTypeName builderType, CodeBlock body,
      EmitContext context, String caseTypeId, String concern) {
    MethodSpec configure = MethodSpec.methodBuilder("configure")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .addParameter(builderType, "builder")
        .addJavadoc("Configures the $L for {@code $L}.\n\n@param builder the config builder\n",
            concern, caseTypeId)
        .addCode(body)
        .build();
    TypeSpec configClass = TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC)
        // @Component so component scanning registers this as a CCDConfig bean for the generator.
        .addAnnotation(ClassName.get("org.springframework.stereotype", "Component"))
        .addSuperinterface(configType)
        .addJavadoc(context.banner(caseTypeId, null) + "\n\n<p>The $L for {@code $L}.\n",
            concern, caseTypeId)
        .addMethod(configure)
        .build();
    return JavaFile.builder(configPkg, configClass)
        .indent("    ")
        .skipJavaLangImports(true)
        .build();
  }

  /**
   * Number of complex-type grants (each a serializable {@code CaseData::getX} lambda) per generated
   * helper class, kept well under the count that would overflow a class's synthesised
   * {@code $deserializeLambda$} bytecode.
   */
  private static final int COMPLEX_GRANTS_PER_HELPER = 120;

  /**
   * Builds the {@code <Prefix>ComplexTypeGrantsNN} helper classes carrying the
   * {@code grantComplexType} calls (split so no class's serializable-lambda bytecode overflows),
   * appending each to {@code helperClasses} and returning the class names in call order for
   * {@code configure()} to invoke.
   */
  private List<ClassName> buildComplexTypeGrantHelpers(
      CaseTypeModel model, EmitContext context, ClassName caseData, ClassName state,
      ClassName userRole, ClassName permission, ParameterizedTypeName builderType,
      String configPkg, List<TypeSpec> helperClasses) {
    List<uk.gov.hmcts.ccd.sdk.converter.model.ComplexTypeAuthModel> grants =
        model.getComplexTypeAuthorisations();
    if (grants == null || grants.isEmpty()) {
      return List.of();
    }
    Map<String, String> roleConstants = buildRoleConstants(model);
    Map<String, uk.gov.hmcts.ccd.sdk.converter.model.FieldModel> membersById =
        new java.util.LinkedHashMap<>();
    for (uk.gov.hmcts.ccd.sdk.converter.model.FieldModel field : model.getCaseFields()) {
      membersById.put(field.getId(), field);
    }
    String prefix = Names.toClassName(model.getCaseTypeId());
    List<ClassName> helpers = new ArrayList<>();
    int index = 0;
    for (int start = 0; start < grants.size(); start += COMPLEX_GRANTS_PER_HELPER) {
      int end = Math.min(start + COMPLEX_GRANTS_PER_HELPER, grants.size());
      CodeBlock.Builder apply = CodeBlock.builder();
      for (uk.gov.hmcts.ccd.sdk.converter.model.ComplexTypeAuthModel grant
          : grants.subList(start, end)) {
        uk.gov.hmcts.ccd.sdk.converter.model.FieldModel member =
            membersById.get(grant.getCaseFieldId());
        String roleConst = roleConstants.get(grant.getRole());
        if (member == null || roleConst == null) {
          missingRoleGap(context, "AuthorisationComplexType",
              grant.getCaseFieldId() + "/" + grant.getListElementCode(), grant.getRole());
          continue;
        }
        CodeBlock permSet = crudToPermissionSet(grant.getCrud(), permission);
        apply.addStatement("builder.grantComplexType($T::get$L, $S, $L, $T.$L)",
            caseData, capitalise(member.getJavaName()), grant.getListElementCode(),
            permSet, userRole, roleConst);
      }
      String helperName = String.format("%sComplexTypeGrants%02d", prefix, ++index);
      TypeSpec helper = TypeSpec.classBuilder(helperName)
          .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
          .addJavadoc(context.banner(model.getCaseTypeId(), null) + "\n\n"
              + "<p>AuthorisationComplexType grants for {@code $L} (part $L).\n",
              model.getCaseTypeId(), index)
          .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
          .addMethod(MethodSpec.methodBuilder("apply")
              .addModifiers(Modifier.STATIC)
              .addParameter(builderType, "builder")
              .addJavadoc("@param builder the config builder\n")
              .addCode(apply.build())
              .build())
          .build();
      helperClasses.add(helper);
      helpers.add(ClassName.get(configPkg, helperName));
    }
    return helpers;
  }

  private Map<String, String> buildRoleConstants(CaseTypeModel model) {
    Map<String, String> index = new java.util.LinkedHashMap<>();
    for (RoleModel role : model.getRoles()) {
      index.put(role.getId(), role.getJavaConstant());
    }
    return index;
  }

  private void missingRoleGap(
      EmitContext context, String sheet, String rowKey, String roleId) {
    context.getGaps().add(GapEntry.builder()
        .sheet(sheet)
        .rowKey(rowKey)
        .column("UserRole")
        .value(roleId)
        .category(GapCategory.UNSUPPORTED_VALUE)
        .action(GapAction.PASSTHROUGH_COLUMN)
        .detail("Role '" + roleId
            + "' not present on the generated UserRole enum; the row is skipped")
        .build());
  }

  private void emitStateGrants(
      CaseTypeModel model, CodeBlock.Builder cb,
      ClassName state, ClassName userRole, ClassName permission,
      Map<String, String> roleConstants, EmitContext context) {
    // Group stateAuthorisations by state+crud → collect roles.
    // Emit each row as a separate grant call.
    List<SheetRow> rows = model.getStateAuthorisations();
    if (rows == null || rows.isEmpty()) {
      return;
    }
    // Build: stateId -> (crud -> [roles])
    Map<String, Map<String, List<String>>> byStateCrud = new java.util.LinkedHashMap<>();
    for (SheetRow row : rows) {
      String stateId = row.getString(Columns.CASE_STATE_ID).orElse(null);
      if (stateId == null) {
        continue;
      }
      // A row grants a single flat role or, via the UserRoles/AccessControl array shorthands,
      // several at once — the same shapes ccd-definition-processor flattens to per-role rows.
      // Expand them so each role gets its state grant.
      for (Map.Entry<String, String> grant : AuthorisationRows.roleGrants(row).entrySet()) {
        byStateCrud
            .computeIfAbsent(stateId, k -> new java.util.LinkedHashMap<>())
            .computeIfAbsent(grant.getValue(), k -> new ArrayList<>())
            .add(grant.getKey());
      }
    }
    for (Map.Entry<String, Map<String, List<String>>> stateEntry : byStateCrud.entrySet()) {
      String stateId = stateEntry.getKey();
      for (Map.Entry<String, List<String>> crudEntry : stateEntry.getValue().entrySet()) {
        String crud = crudEntry.getKey();
        List<String> roleIds = crudEntry.getValue();
        CodeBlock permSet = crudToPermissionSet(crud, permission);
        for (String roleId : roleIds) {
          String roleConst = roleConstants.get(roleId);
          if (roleConst == null) {
            missingRoleGap(context, "AuthorisationCaseState", stateId + "/" + roleId, roleId);
            continue;
          }
          cb.addStatement("builder.grant($T.$L, $L, $T.$L)",
              state, context.stateConstant(stateId), permSet, userRole, roleConst);
        }
      }
    }
  }

  /**
   * Emits {@code builder.banner(enabled, description, url, urlText)} when the input carries a
   * banner. Reproduces the {@code Banner} sheet's single row via the builder (the importer allows
   * exactly one banner per jurisdiction), replacing the former whole-sheet passthrough.
   */
  private void emitBanner(CaseTypeModel model, CodeBlock.Builder cb) {
    if (model.getBanner() == null) {
      return;
    }
    cb.addStatement("builder.banner($L, $S, $S, $S)",
        model.getBanner().isEnabled(),
        nullToEmpty(model.getBanner().getDescription()),
        nullToEmpty(model.getBanner().getUrl()),
        nullToEmpty(model.getBanner().getUrlText()));
  }

  private CodeBlock crudToPermissionSet(String crud, ClassName permission) {
    // Prefer the SDK's Permission.CR/CRU/CRUD set shortcuts (finding #5), falling back to an
    // explicit Set.of(Permission.X, …) for any combination without a named constant.
    return Names.permissionSet(crud, permission);
  }

  private void emitTabs(
      CaseTypeModel model, CodeBlock.Builder cb, ClassName caseData, ClassName userRole,
      Map<String, String> roleConstants, EmitContext context) {
    if (model.getTabs() == null) {
      return;
    }
    // A CaseData member field can be placed on a tab via the typed-getter overloads
    // (Tab.TabBuilder.field(CaseData::getX, showCondition, displayContext)), which carry the
    // DisplayContextParameter the string overloads cannot. Index members by CCD id so a tab field
    // referencing one is emitted through the typed getter; non-members (metadata like [STATE],
    // fields not on CaseData) fall back to the string overloads.
    Map<String, uk.gov.hmcts.ccd.sdk.converter.model.FieldModel> membersById =
        new java.util.LinkedHashMap<>();
    for (uk.gov.hmcts.ccd.sdk.converter.model.FieldModel field : model.getCaseFields()) {
      // Overlay-tagged fields are not emitted onto CaseData (CaseDataEmitter skips them), so a
      // typed getter reference would not compile; treat them as non-members.
      if (field.getOverlayTags() == null || field.getOverlayTags().isEmpty()) {
        membersById.put(field.getId(), field);
      }
    }
    for (TabModel tab : model.getTabs()) {
      // The SDK derives tab display order from the order tabs are declared here, so tabs are
      // emitted in ascending display order (see sortedByDisplayOrder) and there is no
      // displayOrder() builder call.
      cb.add("builder.tab($S, $S)", tab.getTabId(), tab.getLabel());
      if (tab.getShowCondition() != null && !tab.getShowCondition().isEmpty()) {
        cb.add("\n    .showCondition($S)", tab.getShowCondition());
      }
      if (tab.getUserRole() != null && !tab.getUserRole().isEmpty()) {
        String roleConst = roleConstants.get(tab.getUserRole());
        if (roleConst == null) {
          missingRoleGap(context, "CaseTypeTab", tab.getTabId(), tab.getUserRole());
        } else {
          cb.add("\n    .forRoles($T.$L)", userRole, roleConst);
        }
      }
      for (TabModel.TabField field : tab.getFields()) {
        boolean hasShowCondition =
            field.getShowCondition() != null && !field.getShowCondition().isEmpty();
        boolean hasLabel = field.getLabel() != null && !field.getLabel().isEmpty();
        boolean hasDcp = field.getDisplayContextParameter() != null
            && !field.getDisplayContextParameter().isEmpty();
        uk.gov.hmcts.ccd.sdk.converter.model.FieldModel member =
            membersById.get(field.getCaseFieldId());
        if (hasLabel) {
          // label(fieldName, showCondition, label) is the only overload carrying a label, and it
          // rewrites the field to FieldType=Label; there is no typed/DCP label overload, so a
          // labelled tab field stays on the string path (any DisplayContextParameter on it is an
          // unreproducible residual, noted in the fidelity doc).
          cb.add("\n    .label($S, $S, $S)",
              field.getCaseFieldId(), nullToEmpty(field.getShowCondition()), field.getLabel());
        } else if (hasDcp && member != null) {
          // A DisplayContextParameter is the only tab-field attribute the string overloads cannot
          // carry, and only the typed-getter overload field(getter, showCondition, displayContext)
          // does. Use it solely for member fields that actually carry a DCP: the getter resolves
          // back to the CCD id via PropertyUtils (honouring the @JsonProperty the emitter adds for
          // renamed or upper-cased ids), matching the string-id the CaseField row uses. Keeping the
          // cheap string path for the common (DCP-less) case matters — every typed getter is a
          // serializable lambda, and a large tab (ia's overview: 862 fields) would otherwise
          // overflow the class's synthesised $deserializeLambda$ ("code too large").
          String getter = "get" + capitalise(member.getJavaName());
          cb.add("\n    .field($T::$L, $S, $S)", caseData, getter,
              nullToEmpty(field.getShowCondition()), field.getDisplayContextParameter());
        } else if (hasShowCondition) {
          // id + showCondition round-trips through the string overload; a DisplayContextParameter
          // on a non-member field (metadata such as [STATE], or a field not on CaseData) is an
          // unreproducible residual (noted in the fidelity doc).
          cb.add("\n    .field($S, $S)", field.getCaseFieldId(), field.getShowCondition());
        } else {
          cb.add("\n    .field($S)", field.getCaseFieldId());
        }
      }
      cb.addStatement("");
    }
  }

  private void emitSearchBuilder(
      CodeBlock.Builder cb, String builderMethod, List<SearchFieldModel> fields,
      ClassName userRole, Map<String, String> roleConstants, EmitContext context, String sheet) {
    if (fields == null || fields.isEmpty()) {
      return;
    }
    ClassName sortOrder = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "SortOrder");
    cb.add("builder.$L()", builderMethod);
    for (SearchFieldModel field : fields) {
      String label = field.getLabel() != null ? field.getLabel() : "";
      String roleId = field.getUserRole();
      String roleConst = null;
      if (roleId != null && !roleId.isEmpty()) {
        roleConst = roleConstants.get(roleId);
        if (roleConst == null) {
          missingRoleGap(context, sheet, field.getCaseFieldId() + "/" + roleId, roleId);
          continue;
        }
      }
      // The optional columns ListElementCode / FieldShowCondition / ResultsOrdering (and a role
      // scope) are carried through the per-field lambda field(id, label, f -> …); the plain
      // field(id, label[, role]) overloads are used when the row sets none of them, keeping the
      // common case terse. DisplayContextParameter also has a lambda setter.
      boolean hasExtras = notBlank(field.getListElementCode())
          || notBlank(field.getShowCondition())
          || notBlank(field.getResultsOrdering())
          || notBlank(field.getDisplayContextParameter());
      if (hasExtras) {
        CodeBlock.Builder lambda = CodeBlock.builder();
        lambda.add("f -> f");
        if (notBlank(field.getListElementCode())) {
          lambda.add(".listElementCode($S)", field.getListElementCode());
        }
        if (notBlank(field.getShowCondition())) {
          lambda.add(".showCondition($S)", field.getShowCondition());
        }
        if (notBlank(field.getResultsOrdering())) {
          lambda.add(".resultsOrdering($L)", sortOrderExpression(sortOrder, field.getResultsOrdering()));
        }
        if (notBlank(field.getDisplayContextParameter())) {
          lambda.add(".displayContextParameter($S)", field.getDisplayContextParameter());
        }
        if (roleConst != null) {
          lambda.add(".role($T.$L)", userRole, roleConst);
        }
        cb.add("\n    .field($S, $S, $L)", field.getCaseFieldId(), label, lambda.build());
      } else if (roleConst != null) {
        cb.add("\n    .field($S, $S, $T.$L)",
            field.getCaseFieldId(), label, userRole, roleConst);
      } else {
        cb.add("\n    .field($S, $S)", field.getCaseFieldId(), label);
      }
    }
    cb.addStatement("");
  }

  private static boolean notBlank(String s) {
    return s != null && !s.isEmpty();
  }

  /**
   * Maps a CCD {@code ResultsOrdering} value ({@code "<priority>:ASC"}/{@code ":DESC"}) to the
   * {@link uk.gov.hmcts.ccd.sdk.api.SortOrder} constant expression the per-field lambda expects,
   * e.g. {@code "1:ASC"} → {@code SortOrder.FIRST.ASCENDING}. Priorities 1–5 have named constants.
   */
  private CodeBlock sortOrderExpression(ClassName sortOrder, String value) {
    String[] parts = value.split(":");
    String priority = parts.length > 0 ? parts[0].trim() : "1";
    boolean descending = parts.length > 1 && parts[1].trim().equalsIgnoreCase("DESC");
    String ordinal = switch (priority) {
      case "1" -> "FIRST";
      case "2" -> "SECOND";
      case "3" -> "THIRD";
      case "4" -> "FOURTH";
      case "5" -> "FIFTH";
      default -> "FIRST";
    };
    return CodeBlock.of("$T.$L.$L", sortOrder, ordinal, descending ? "DESCENDING" : "ASCENDING");
  }

  private void emitSearchCasesBuilder(
      CodeBlock.Builder cb, List<SearchFieldModel> fields,
      ClassName userRole, Map<String, String> roleConstants, EmitContext context) {
    if (fields == null || fields.isEmpty()) {
      return;
    }
    cb.add("builder.searchCasesFields()");
    for (SearchFieldModel field : fields) {
      String label = field.getLabel() != null ? field.getLabel() : "";
      String roleId = field.getUserRole();
      String roleConst = null;
      if (roleId != null && !roleId.isEmpty()) {
        roleConst = roleConstants.get(roleId);
        if (roleConst == null) {
          missingRoleGap(context, "SearchCasesResultFields",
              field.getCaseFieldId() + "/" + roleId, roleId);
          continue;
        }
      }
      // The optional columns — an AccessProfile/UserRole scope, the UseCase, ListElementCode,
      // ResultsOrdering and DisplayContextParameter — are now all carried through the per-field
      // lambda field(id, label, f -> …) (SearchCases.ResultFieldBuilder), retiring the LEC row
      // passthrough and the FieldShowCondition graft the linker used to record. The plain
      // field(id, label) overload stays the terse common case when a row sets none of them.
      boolean hasExtras = roleConst != null
          || notBlank(field.getUseCase())
          || notBlank(field.getListElementCode())
          || notBlank(field.getResultsOrdering())
          || notBlank(field.getDisplayContextParameter());
      if (hasExtras) {
        CodeBlock.Builder lambda = CodeBlock.builder();
        lambda.add("f -> f");
        if (roleConst != null) {
          lambda.add(".role($T.$L)", userRole, roleConst);
        }
        if (notBlank(field.getUseCase())) {
          lambda.add(".useCase($S)", field.getUseCase());
        }
        if (notBlank(field.getListElementCode())) {
          lambda.add(".listElementCode($S)", field.getListElementCode());
        }
        if (notBlank(field.getResultsOrdering())) {
          lambda.add(".resultsOrdering($S)", field.getResultsOrdering());
        }
        if (notBlank(field.getDisplayContextParameter())) {
          lambda.add(".displayContextParameter($S)", field.getDisplayContextParameter());
        }
        cb.add("\n    .field($S, $S, $L)", field.getCaseFieldId(), label, lambda.build());
      } else {
        cb.add("\n    .field($S, $S)", field.getCaseFieldId(), label);
      }
    }
    cb.addStatement("");
  }

  private static String nullToEmpty(String s) {
    return s != null ? s : "";
  }

  private static String capitalise(String s) {
    if (s == null || s.isEmpty()) {
      return s;
    }
    return Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }

  private void emitNoc(
      CaseTypeModel model, CodeBlock.Builder cb, ClassName caseData, ClassName userRole,
      Map<String, String> roleConstants, EmitContext context) {
    List<SheetRow> questions = model.getChallengeQuestions();
    if (questions == null || questions.isEmpty()) {
      return;
    }
    // Group the ChallengeQuestion rows by their challenge ID (the "ID" column); each row is one
    // question. The SDK's NoticeOfChangeBuilder nests questions under a challenge:
    //   noticeOfChange().challenge(id).question(qId, qText)... .done()
    // ChallengeQuestionGenerator re-derives one ChallengeQuestion.json row per question, so
    // reproducing the challenge/question/answer structure round-trips the sheet.
    Map<String, List<SheetRow>> byChallenge = new java.util.LinkedHashMap<>();
    for (SheetRow row : questions) {
      String challengeId = row.getString(Columns.ID).orElse("");
      byChallenge.computeIfAbsent(challengeId, k -> new ArrayList<>()).add(row);
    }

    cb.add("builder.noticeOfChange()");
    for (Map.Entry<String, List<SheetRow>> entry : byChallenge.entrySet()) {
      cb.add("\n    .challenge($S)", entry.getKey());
      for (SheetRow row : entry.getValue()) {
        String questionId = row.getString(Columns.QUESTION_ID).orElse("");
        String questionText = row.getString(Columns.QUESTION_TEXT).orElse("");
        cb.add("\n        .question($S, $S)", questionId, questionText);
        row.getInteger(Columns.DISPLAY_ORDER).ifPresent(order ->
            cb.add("\n        .displayOrder($L)", order));
        row.getString(Columns.ANSWER_FIELD_TYPE).ifPresent(type ->
            cb.add("\n        .answerFieldType($S)", type));
        emitNocAnswers(row, cb, userRole, roleConstants, context, questionId);
        cb.add("\n        .done()");
      }
    }
    cb.addStatement("");
  }

  /**
   * Emits the {@code answer(roles).field(path)} calls for one challenge question. The Answer
   * column is a comma-separated list of {@code ${path.segments}:[Role]} mappings; each mapping
   * becomes one {@code .answer(UserRole.X).field("path.segments")} pair, whose ordering
   * {@link uk.gov.hmcts.ccd.sdk.generator.ChallengeQuestionGenerator} reproduces verbatim.
   */
  private void emitNocAnswers(
      SheetRow row, CodeBlock.Builder cb, ClassName userRole,
      Map<String, String> roleConstants, EmitContext context, String questionId) {
    String answer = row.getString(Columns.ANSWER).orElse(null);
    if (answer == null || answer.isBlank()) {
      return;
    }
    for (String part : answer.split(",")) {
      String trimmed = part.trim();
      if (trimmed.isEmpty()) {
        continue;
      }
      int colon = trimmed.lastIndexOf(':');
      if (colon < 0) {
        continue;
      }
      String pathToken = trimmed.substring(0, colon).trim();
      String roleToken = trimmed.substring(colon + 1).trim();
      String path = pathToken;
      if (path.startsWith("${") && path.endsWith("}")) {
        path = path.substring(2, path.length() - 1);
      }
      String roleConst = roleConstants.get(roleToken);
      if (roleConst == null) {
        missingRoleGap(context, "ChallengeQuestion", questionId, roleToken);
        continue;
      }
      cb.add("\n        .answer($T.$L)", userRole, roleConst);
      cb.add("\n            .field($S)", path);
    }
  }

  private void emitRoleToAccessProfiles(
      CaseTypeModel model, CodeBlock.Builder cb, ClassName userRole,
      Map<String, String> roleConstants, EmitContext context) {
    List<SheetRow> rows = model.getRoleToAccessProfiles();
    if (rows == null || rows.isEmpty()) {
      return;
    }
    for (SheetRow row : rows) {
      String roleName = row.getString(Columns.ROLE_NAME).orElse(null);
      if (roleName == null) {
        continue;
      }
      // The SDK prepends "idam:" to the RoleName when the mapping is flagged a legacy IDAM role
      // (RoleToAccessProfilesGenerator). Strip that prefix to resolve the UserRole enum constant,
      // and re-apply it via .legacyIdamRole() so the generated RoleName matches the input.
      boolean legacyIdam = roleName.startsWith("idam:");
      String bareRole = legacyIdam ? roleName.substring("idam:".length()) : roleName;
      String roleConst = roleConstants.get(bareRole);
      if (roleConst == null) {
        // An organisational / IDAM role name that is not a registered UserRole constant: emit it
        // verbatim via roleToAccessProfile(String), which produces only the RoleToAccessProfiles
        // row (no UserRole registration, no empty-CRUD AuthorisationCaseType row). Replaces the
        // former row-passthrough.
        cb.add("builder.roleToAccessProfile($S)", bareRole);
      } else {
        cb.add("builder.caseRoleToAccessProfile($T.$L)", userRole, roleConst);
      }
      if (legacyIdam) {
        cb.add("\n    .legacyIdamRole()");
      }

      row.getString(Columns.AUTHORISATION).ifPresent(auth -> {
        for (String part : auth.split(",")) {
          String trimmed = part.trim();
          if (!trimmed.isEmpty()) {
            cb.add("\n    .authorisation($S)", trimmed);
          }
        }
      });
      row.getString(Columns.ACCESS_PROFILES).ifPresent(profiles -> {
        for (String part : profiles.split(",")) {
          String trimmed = part.trim();
          if (!trimmed.isEmpty()) {
            cb.add("\n    .accessProfiles($S)", trimmed);
          }
        }
      });
      row.getString(Columns.CASE_ACCESS_CATEGORIES).ifPresent(cats -> {
        for (String part : cats.split(",")) {
          String trimmed = part.trim();
          if (!trimmed.isEmpty()) {
            cb.add("\n    .caseAccessCategories($S)", trimmed);
          }
        }
      });
      row.getYesNo(Columns.READ_ONLY).ifPresent(val -> {
        if (Boolean.TRUE.equals(val)) {
          cb.add("\n    .readonly()");
        }
      });
      row.getYesNo(Columns.DISABLED).ifPresent(val -> {
        if (Boolean.TRUE.equals(val)) {
          cb.add("\n    .disabled()");
        }
      });
      cb.addStatement("");
    }
  }

  private void emitCategories(
      CaseTypeModel model, CodeBlock.Builder cb, ClassName userRole,
      Map<String, String> roleConstants, EmitContext context) {
    List<SheetRow> rows = model.getCategories();
    if (rows == null || rows.isEmpty()) {
      return;
    }
    // The SDK's categories(caseRole) requires a role argument, but CaseCategory discards it (the
    // generated Categories.json carries no role), so a Category with no AccessProfile in the input
    // is emitted against any available role constant. Real definitions (fpl) carry role-less
    // Category rows, so falling back rather than skipping is required to reproduce them.
    String anyRoleConst = roleConstants.isEmpty()
        ? null : roleConstants.values().iterator().next();
    for (SheetRow row : rows) {
      String accessProfile = row.getString(Columns.ACCESS_PROFILE, Columns.USER_ROLE)
          .orElse(null);
      String roleConst = accessProfile == null ? anyRoleConst : roleConstants.get(accessProfile);
      if (roleConst == null) {
        if (accessProfile != null) {
          missingRoleGap(context, "Categories", accessProfile, accessProfile);
        }
        continue;
      }
      cb.add("builder.categories($T.$L)", userRole, roleConst);
      row.getString(Columns.CATEGORY_ID).ifPresent(id ->
          cb.add("\n    .categoryID($S)", id));
      row.getString(Columns.CATEGORY_LABEL).ifPresent(label ->
          cb.add("\n    .categoryLabel($S)", label));
      row.getInteger(Columns.DISPLAY_ORDER).ifPresent(order ->
          cb.add("\n    .displayOrder($L)", order));
      row.getString(Columns.PARENT_CATEGORY_ID).ifPresent(parentId ->
          cb.add("\n    .parentCategoryID($S)", parentId));
      cb.addStatement("");
    }
  }

  private void emitSearchCriteria(CaseTypeModel model, CodeBlock.Builder cb) {
    List<SheetRow> rows = model.getSearchCriteria();
    if (rows == null || rows.isEmpty()) {
      return;
    }
    for (SheetRow row : rows) {
      String otherCaseRef = row.getString(Columns.OTHER_CASE_REFERENCE).orElse(null);
      if (otherCaseRef == null) {
        continue;
      }
      cb.addStatement(
          "builder.searchCriteria().fields($T.of($T.builder().otherCaseReference($S).build()))",
          List.class,
          ClassName.get("uk.gov.hmcts.ccd.sdk.api", "SearchCriteriaField"),
          otherCaseRef);
    }
  }

  private void emitSearchParties(CaseTypeModel model, CodeBlock.Builder cb) {
    List<SheetRow> rows = model.getSearchParties();
    if (rows == null || rows.isEmpty()) {
      return;
    }
    for (SheetRow row : rows) {
      ClassName spField = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "SearchPartyField");
      cb.add("builder.searchParty().fields($T.of($T.builder()", List.class, spField);
      row.getString(Columns.SEARCH_PARTY_NAME).ifPresent(v ->
          cb.add("\n    .searchPartyName($S)", v));
      row.getString(Columns.SEARCH_PARTY_EMAIL_ADDRESS).ifPresent(v ->
          cb.add("\n    .searchPartyEmailAddress($S)", v));
      row.getString(Columns.SEARCH_PARTY_ADDRESS_LINE_1).ifPresent(v ->
          cb.add("\n    .searchPartyAddressLine1($S)", v));
      row.getString(Columns.SEARCH_PARTY_POST_CODE).ifPresent(v ->
          cb.add("\n    .searchPartyPostCode($S)", v));
      row.getString(Columns.SEARCH_PARTY_DOB).ifPresent(v ->
          cb.add("\n    .searchPartyDOB($S)", v));
      row.getString(Columns.SEARCH_PARTY_DOD).ifPresent(v ->
          cb.add("\n    .searchPartyDOD($S)", v));
      row.getString(Columns.SEARCH_PARTY_COLLECTION_FIELD_NAME).ifPresent(v ->
          cb.add("\n    .searchPartyCollectionFieldName($S)", v));
      cb.addStatement("\n    .build()))");
    }
  }
}
