package uk.gov.hmcts.ccd.sdk.converter.emit.config;

import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import java.util.List;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Emits the {@code EnvironmentFlags} utility class into the model package. The generated
 * class provides a single static method that evaluates a named environment variable
 * (system-property first, then {@code System.getenv}) against an expected value,
 * case-insensitively. Config emitters use this to guard per-environment overlay event
 * registrations at runtime.
 */
public class EnvironmentFlagsEmitter implements SourceEmitter {

  /**
   * Emits the {@code EnvironmentFlags} class into the model package.
   *
   * @param model the linked case type model (not inspected — output is always the same shape)
   * @param context packages and options
   * @return a single-element list containing the generated file
   */
  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    MethodSpec flagMethod = MethodSpec.methodBuilder("flag")
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(boolean.class)
        .addParameter(String.class, "name")
        .addParameter(String.class, "expected")
        .addJavadoc("Evaluates a named environment predicate.\n"
            + "\n"
            + "@param name the system-property or environment-variable name to check\n"
            + "@param expected the value required for the predicate to hold\n"
            + "@return {@code true} when the resolved value equals {@code expected}, "
            + "case-insensitively\n")
        .addStatement(
            "$T value = $T.getProperty(name, $T.getenv().getOrDefault(name, $S))",
            String.class, System.class, System.class, "")
        .addStatement("return expected.equalsIgnoreCase(value)")
        .build();

    MethodSpec constructor = MethodSpec.constructorBuilder()
        .addModifiers(Modifier.PRIVATE)
        .addJavadoc("Utility class — do not instantiate.\n")
        .build();

    TypeSpec flagsClass = TypeSpec.classBuilder("EnvironmentFlags")
        .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
        .addJavadoc(
            "Generated by ccd-definition-converter — do not edit by hand.\n"
                + "\n"
                + "<p>Runtime environment-flag checks used to guard overlay event "
                + "registrations.\n")
        .addMethod(constructor)
        .addMethod(flagMethod)
        .build();

    JavaFile file = JavaFile.builder(context.modelPackage(), flagsClass)
        .indent("    ")
        .skipJavaLangImports(true)
        .build();

    return List.of(file);
  }
}
