package uk.gov.hmcts.ccd.sdk.converter.emit.config;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.ClusteredFieldRef;
import uk.gov.hmcts.ccd.sdk.converter.model.EventComplexTypeGroup;
import uk.gov.hmcts.ccd.sdk.converter.model.EventModel;
import uk.gov.hmcts.ccd.sdk.converter.model.FieldModel;
import uk.gov.hmcts.ccd.sdk.converter.model.PageModel;
import uk.gov.hmcts.ccd.sdk.converter.model.RoleModel;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapAction;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapCategory;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapEntry;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Emits <b>one {@code CCDConfig} class per event</b>, PascalCase-named from the event ID, into
 * {@code <root>.event} — mirroring the one-event-one-class idiom of the reference services
 * (nfdiv/sptribs) so each event is a findable, individually-ownable unit rather than the Nth private
 * method in a numbered grab-bag (finding #1).
 *
 * <p>A <b>multi-page</b> event's wizard pages are split into their own <b>page classes</b> in
 * {@code <root>.event.page}, one per CCD page, referenced from the event class via a static
 * {@code apply(fields)} call (finding #2). This matches both reference teams' page-per-concern
 * decomposition and, because every page's serializable getter lambdas land in that page class's own
 * synthesised {@code $deserializeLambda$}, keeps each class well under the JVM's 64&nbsp;KB bytecode
 * limits. A single page large enough to overflow one method on its own (prl's {@code waManageOrders})
 * falls back to the documented {@code <Page>FieldsN} line-budget split <em>within</em> that page's
 * package — the only place the numbered-fragment form survives.
 *
 * <p>A <b>single-page</b> event carries no page class at all: its one page's field chain is inlined
 * directly into the event class's {@code configure()} method (a page class would be pure
 * indirection for one page). The inlined calls — {@code fields.page(id)}, the optional page label /
 * show condition, then the placements — are byte-for-byte what the page class's {@code apply(fields)}
 * would have run, so the regenerated definition is identical; a case type whose every event is
 * single-page therefore produces no {@code <root>.event.page} package. The overflow split still
 * applies to an oversized single page (fragments only, still no page class).
 */
public class EventsConfigEmitter implements SourceEmitter {

  /**
   * Generates one config class per event, plus a page class per wizard page.
   *
   * @param model the linked case type model
   * @param context packages and options
   * @return one JavaFile per event class and per page class (and per overflow fragment)
   */
  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    List<EventModel> events = model.getEvents();
    if (events == null || events.isEmpty()) {
      return List.of();
    }

    String eventPkg = context.eventPackage();
    String pagePkg = context.pagePackage();

    // Retarget to the team's model/State in retrofit mode (see EmitContext); generate mode keeps
    // the freshly generated <modelPackage>.{CaseData,State,UserRole}.
    ClassName caseData = context.caseDataClass();
    ClassName state = context.stateClass();
    ClassName userRole = context.userRoleClass();
    ClassName permission = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "Permission");
    ClassName ccdConfig = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "CCDConfig");

    ParameterizedTypeName configType =
        ParameterizedTypeName.get(ccdConfig, caseData, state, userRole);

    // Event class names are PascalCased from the (already unique, sanitised) event javaName; page
    // class names are qualified by their owning event's class name. Both are allocated collision-free
    // against a shared used-name set so deterministic derivations never clash.
    Set<String> usedEventNames = new LinkedHashSet<>();
    Set<String> usedPageNames = new LinkedHashSet<>();

    List<JavaFile> files = new ArrayList<>();
    for (EventModel event : events) {
      String eventClassName = uniqueName(Names.toClassName(event.getJavaName()), usedEventNames);

      List<TypeSpec> pageClasses = new ArrayList<>();
      MethodSpec configure = buildConfigure(
          event, model, context, caseData, state, userRole, permission,
          eventClassName, pagePkg, pageClasses, usedPageNames);

      TypeSpec eventClass = TypeSpec.classBuilder(eventClassName)
          .addModifiers(Modifier.PUBLIC)
          // @Component so component scanning registers this as a CCDConfig bean for the generator.
          .addAnnotation(ClassName.get("org.springframework.stereotype", "Component"))
          .addSuperinterface(configType)
          .addJavadoc(
              context.banner(model.getCaseTypeId(), null) + "\n"
                  + "\n"
                  + "<p>Event {@code $L} for case type {@code $L}.\n",
              event.getId(), model.getCaseTypeId())
          .addField(eventIdConstant(event, usedEventNames))
          .addMethod(configure)
          .build();

      files.add(JavaFile.builder(eventPkg, eventClass)
          .indent("    ")
          .skipJavaLangImports(true)
          .build());
      for (TypeSpec pageClass : pageClasses) {
        files.add(JavaFile.builder(pagePkg, pageClass)
            .indent("    ")
            .skipJavaLangImports(true)
            .build());
      }
    }
    return files;
  }

  /**
   * Allocates {@code candidate} collision-free against {@code used}, suffixing {@code 2,3,…}.
   */
  private String uniqueName(String candidate, Set<String> used) {
    String name = candidate;
    int suffix = 2;
    while (!used.add(name)) {
      name = candidate + (suffix++);
    }
    return name;
  }

  /**
   * The event-id string constant declared on the event class (nfdiv idiom: {@code public static
   * final String CREATE_CASE = "createCase";}), referenced by {@code configure()} instead of a raw
   * literal. The constant name is a SCREAMING_SNAKE_CASE form of the event ID, kept collision-free
   * against the shared name set so a case-shift/prefix clash cannot produce a duplicate field.
   */
  private com.palantir.javapoet.FieldSpec eventIdConstant(EventModel event, Set<String> used) {
    return com.palantir.javapoet.FieldSpec.builder(String.class,
            screamingSnake(event.getId()),
            Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
        .initializer("$S", event.getId())
        .addJavadoc("The CCD event ID.\n")
        .build();
  }

  /** SCREAMING_SNAKE_CASE for an event-id constant, e.g. {@code applicant2-request-changes} →
   * {@code APPLICANT_2_REQUEST_CHANGES}, {@code boHandleEvidence} → {@code BO_HANDLE_EVIDENCE}. */
  private String screamingSnake(String id) {
    StringBuilder sb = new StringBuilder();
    char[] chars = id.toCharArray();
    for (int i = 0; i < chars.length; i++) {
      char ch = chars[i];
      if (Character.isLetterOrDigit(ch)) {
        boolean boundary = i > 0 && Character.isUpperCase(ch)
            && (Character.isLowerCase(chars[i - 1]) || Character.isDigit(chars[i - 1]));
        if (boundary && sb.length() > 0 && sb.charAt(sb.length() - 1) != '_') {
          sb.append('_');
        }
        sb.append(Character.toUpperCase(ch));
      } else if (sb.length() > 0 && sb.charAt(sb.length() - 1) != '_') {
        sb.append('_');
      }
    }
    String result = sb.toString();
    if (result.isEmpty() || Character.isDigit(result.charAt(0))) {
      result = "EVENT_" + result;
    }
    return result;
  }

  private MethodSpec buildConfigure(
      EventModel event, CaseTypeModel model, EmitContext context,
      ClassName caseData, ClassName state, ClassName userRole, ClassName permission,
      String eventClassName, String pagePkg, List<TypeSpec> pageClasses, Set<String> usedPageNames) {

    ParameterizedTypeName builderType =
        ParameterizedTypeName.get(
            ClassName.get("uk.gov.hmcts.ccd.sdk.api", "ConfigBuilder"),
            caseData, state, userRole);

    MethodSpec.Builder configure = MethodSpec.methodBuilder("configure")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .addParameter(builderType, "builder");

    if (event.getOverlayCondition() != null) {
      ClassName envFlags = ClassName.get(context.modelPackage(), "EnvironmentFlags");
      // Non-negated: register only when the flag matches, so skip when it does not.
      // Negated: register only when the flag does not match, so skip when it does.
      CodeBlock guard = event.getOverlayCondition().isNegated()
          ? CodeBlock.of("if ($T.flag($S, $S)) return",
              envFlags,
              event.getOverlayCondition().getEnvVar(),
              event.getOverlayCondition().getExpectedValue())
          : CodeBlock.of("if (!$T.flag($S, $S)) return",
              envFlags,
              event.getOverlayCondition().getEnvVar(),
              event.getOverlayCondition().getExpectedValue());
      configure
          .addJavadoc(
              "Registers overlay event {@code $L} (active when $L=$L).\n\n"
                  + "@param builder the config builder\n",
              event.getId(),
              event.getOverlayCondition().getEnvVar(),
              event.getOverlayCondition().getExpectedValue())
          .addStatement(guard);
    } else {
      configure.addJavadoc("Registers event {@code $L}.\n\n@param builder the config builder\n",
          event.getId());
    }

    configure.addCode(buildEventBody(
        event, model, context, caseData, state, userRole, permission,
        eventClassName, pagePkg, pageClasses, usedPageNames));
    return configure.build();
  }

  /**
   * The generic type of the {@code fields} builder returned by {@code builder.event(id)….fields()},
   * used to type the parameter of a page class's {@code apply(fields)} method.
   */
  private static ParameterizedTypeName fieldsBuilderType(
      ClassName caseData, ClassName state, ClassName userRole) {
    ClassName fieldCollectionBuilder = ClassName.get(
        "uk.gov.hmcts.ccd.sdk.api", "FieldCollection", "FieldCollectionBuilder");
    ClassName eventBuilder = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "Event", "EventBuilder");
    return ParameterizedTypeName.get(fieldCollectionBuilder, caseData, state,
        ParameterizedTypeName.get(eventBuilder, caseData, userRole, state));
  }

  private CodeBlock buildEventBody(
      EventModel event, CaseTypeModel model, EmitContext context,
      ClassName caseData, ClassName state, ClassName userRole, ClassName permission,
      String eventClassName, String pagePkg, List<TypeSpec> pageClasses, Set<String> usedPageNames) {

    // builder.event(CONSTANT) chain, up to and including .explicitGrants() and the varargs grants.
    CodeBlock.Builder headerBuilder = CodeBlock.builder();
    headerBuilder.add("builder.event($L)", screamingSnake(event.getId()));
    headerBuilder.add("\n    .").add(buildStateTargeting(event, state, context));
    headerBuilder.add("\n    .name($S)", event.getName());
    // A present-but-empty/blank Description (as distinct from an absent one) must still be
    // emitted explicitly: EventBuilder.name() defaults description to name whenever description
    // is null, so skipping an empty description here would let that default silently overwrite
    // authored blank text. Only a description that equals the name is skipped, relying on that
    // same default rather than emitting a redundant explicit call.
    if (event.getDescription() != null && !event.getDescription().equals(event.getName())) {
      headerBuilder.add("\n    .description($S)", event.getDescription());
    }
    if (event.getDisplayOrder() != null) {
      headerBuilder.add("\n    .displayOrder($L)", event.getDisplayOrder());
    }
    if (event.getShowCondition() != null && !event.getShowCondition().isEmpty()) {
      headerBuilder.add("\n    .showCondition($S)", event.getShowCondition());
    }
    if (Boolean.TRUE.equals(event.getShowSummary())) {
      headerBuilder.add("\n    .showSummary()");
    } else if (Boolean.FALSE.equals(event.getShowSummary())) {
      headerBuilder.add("\n    .showSummary(false)");
    }
    if (Boolean.TRUE.equals(event.getShowEventNotes())) {
      headerBuilder.add("\n    .showEventNotes()");
    }
    if (event.getEndButtonLabel() != null && !event.getEndButtonLabel().isEmpty()
        && !event.getEndButtonLabel().equals("Save and continue")) {
      headerBuilder.add("\n    .endButtonLabel($S)", event.getEndButtonLabel());
    }
    if (Boolean.TRUE.equals(event.getPublish())) {
      headerBuilder.add("\n    .publishToCamunda()");
    }
    if (Boolean.TRUE.equals(event.getSignificant())) {
      // CaseEvent SignificantEvent flag, emitted via the builder rather than the CaseEvent graft.
      headerBuilder.add("\n    .significant()");
    }
    if (Boolean.TRUE.equals(event.getCanSaveDraft())) {
      // CaseEvent CanSaveDraft flag, emitted via the builder rather than a residual/graft. The
      // importer only allows this on create events (no pre-state); the input already respects that.
      headerBuilder.add("\n    .canSaveDraft()");
    }
    if (event.getTtlIncrement() != null) {
      headerBuilder.add("\n    .ttlIncrement($L)", event.getTtlIncrement());
    }

    // Explicit grants on every event. A converted config must reproduce the input's
    // AuthorisationCaseField grants EXACTLY, so an event's role grants must NOT cascade onto the
    // fields it places on a page. Without .explicitGrants() the SDK's AuthorisationCaseFieldGenerator
    // derives each field's CRUD from the union of the grants of every event that shows it (widening
    // R->CRUD, CRU->CRUD via the mutable-list D injection, etc.); with it, non-immutable fields
    // derive their CRUD solely from their @CCD(access=...) classes (see AccessClassComputer), which
    // the converter sizes to the input. Immutable fields (Label/READONLY) still receive CR — that
    // residual is the maintainer-accepted IMMUTABLE_FIELD_CR difference.
    headerBuilder.add("\n    .explicitGrants()");

    // Grants: the role/CRUD matrix as varargs-role .grant(permSet, A, B, …) — one call per distinct
    // permission set (finding #11) — inlined directly on the event, matching how the reference teams
    // write it (nfdiv's .grant(CREATE_READ_UPDATE, SOLICITOR, CASE_WORKER)).
    Map<String, String> roleConstants = buildRoleConstants(model);
    Map<String, String> resolvableGrants = resolvableGrants(event, roleConstants);
    // Any grant naming an unknown role is dropped with a gap (it is excluded from resolvableGrants).
    if (event.getGrants() != null) {
      for (Map.Entry<String, String> entry : event.getGrants().entrySet()) {
        if (!roleConstants.containsKey(entry.getKey())) {
          context.getGaps().add(GapEntry.builder()
              .sheet("AuthorisationCaseEvent")
              .rowKey(event.getId() + "/" + entry.getKey())
              .column("UserRole")
              .value(entry.getKey())
              .category(GapCategory.UNSUPPORTED_VALUE)
              .action(GapAction.PASSTHROUGH_COLUMN)
              .detail("Event '" + event.getId() + "' grants role '" + entry.getKey()
                  + "' not present on the generated UserRole enum; the grant is skipped")
              .build());
        }
      }
    }
    appendVarargsGrants(headerBuilder, resolvableGrants, roleConstants, userRole, permission);
    CodeBlock header = headerBuilder.build();

    CodeBlock.Builder cb = CodeBlock.builder();
    List<PageModel> pages = event.getPages();
    boolean hasPages = pages != null && !pages.isEmpty();

    // Callbacks (about-to-start/about-to-submit/submitted, their retry policies and per-page
    // mid-event URLs) are never emitted as SDK wiring: the converter carries every CallBackURL*
    // and RetriesTimeout* column through verbatim passthrough (see DefaultDefinitionLinker) so the
    // original endpoints are reproduced byte-for-byte and the migrated service keeps serving them
    // unchanged. Adopting the SDK's in-process callbacks is a later, per-event step.

    if (!hasPages) {
      cb.add("$L", header);
      cb.addStatement("");
      return cb.build();
    }

    // The header chain terminates at .fields(); the resulting FieldCollectionBuilder is stored in
    // `fields` and each page is applied to it in turn. Every .page()/.field() call returns the same
    // builder, so the placement order is identical whether the calls are inlined here or run from a
    // page class's apply(fields). `var` avoids naming the deeply-nested FieldCollectionBuilder<…>
    // generic type explicitly.
    cb.add("var fields = $L", header);
    cb.add("\n    .fields()");
    cb.addStatement("");

    if (pages.size() == 1) {
      // Single-page event: inline the page's header (page id, optional label / show condition) and
      // its field chain directly into configure() rather than splitting it into its own page class.
      // A page class earns its keep only when an event has several pages to separate; for one page
      // the class is pure indirection. The emitted calls are identical to what the page class's
      // apply(fields) would have run, so the regenerated definition is byte-identical, and no empty
      // <root>.event.page package is created for a case type whose every event is single-page.
      emitInlinePage(cb, pages.get(0), event, model, context, caseData, state, userRole,
          pagePkg, eventClassName, pageClasses, usedPageNames);
      return cb.build();
    }

    // Multi-page event: split each page into its own page class under <root>.event.page (finding
    // #2), spreading each page's serializable getter lambdas into its own class so no one class
    // approaches the JVM's 64 KB per-method / $deserializeLambda$ bytecode limits.
    for (PageModel page : pages) {
      String pageClassName = uniqueName(
          pageClassName(eventClassName, page), usedPageNames);
      buildPageClass(
          pageClassName, page, event, model, context, caseData, state, userRole, pagePkg,
          pageClasses);
      cb.addStatement("$T.apply(fields)", ClassName.get(pagePkg, pageClassName));
    }
    return cb.build();
  }

  /**
   * Inlines a single-page event's placements into its {@code configure()} method, operating on the
   * local {@code fields} builder. Emits the page header ({@code fields.page(id)}, the optional page
   * label / show condition) and the page's field placements directly — no page class. The one
   * exception is a single page whose placement count exceeds {@link #FIELDS_PER_HELPER}: even then
   * the event has no <em>page</em> class, but the placements are split across {@code <Page>FieldsN}
   * fragment classes (in the page package, appended to {@code pageClasses}) invoked in order, so no
   * single method exceeds the bytecode cap. This mirrors the documented overflow split (finding #2)
   * without reintroducing the one-page page class.
   */
  private void emitInlinePage(
      CodeBlock.Builder cb, PageModel page, EventModel event, CaseTypeModel model,
      EmitContext context, ClassName caseData, ClassName state, ClassName userRole, String pagePkg,
      String eventClassName, List<TypeSpec> pageClasses, Set<String> usedPageNames) {

    emitPageHeader(cb, page);
    int fieldCount = page.getFields() == null ? 0 : page.getFields().size();
    if (fieldCount <= FIELDS_PER_HELPER) {
      emitPageFields(cb, page.getFields(), model, caseData, context, event);
      return;
    }

    // Documented overflow: too many placements for configure()'s own bytecode budget. Split them
    // across FieldsN fragment classes and invoke each inline; the fragment names are derived from
    // the page-class name this event would otherwise have used, kept collision-free.
    String base = uniqueName(pageClassName(eventClassName, page), usedPageNames);
    ParameterizedTypeName fieldsType = fieldsBuilderType(caseData, state, userRole);
    List<List<PageModel.PageField>> groups = groupFields(page.getFields());
    for (int i = 0; i < groups.size(); i++) {
      CodeBlock.Builder fragBody = CodeBlock.builder();
      emitPageFields(fragBody, groups.get(i), model, caseData, context, event);
      String fragName = base + "Fields" + (i + 1);
      pageClasses.add(TypeSpec.classBuilder(fragName)
          .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
          .addJavadoc(context.banner(model.getCaseTypeId(), null) + "\n\n"
              + "<p>Field placements for page {@code $L} of event {@code $L} (part $L of $L).\n",
              page.getPageId(), event.getId(), i + 1, groups.size())
          .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
          .addMethod(MethodSpec.methodBuilder("apply")
              .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
              .addParameter(fieldsType, "fields")
              .addJavadoc("@param fields the event's field-collection builder\n")
              .addCode(fragBody.build())
              .build())
          .build());
      cb.addStatement("$T.apply(fields)", ClassName.get(pagePkg, fragName));
    }
  }

  /**
   * The page class name for a wizard page: the owning event class name plus a page token derived
   * from the CCD page ID. A numeric page ID ({@code "1"}, {@code "2.0"}) reads best as
   * {@code <Event>Page1}; a semantic ID ({@code "SDO"}, {@code "selectHearing"}) as
   * {@code <Event><Page>Page} (e.g. {@code CreateSdoOrderTypePage}).
   */
  private String pageClassName(String eventClassName, PageModel page) {
    String pageId = page.getPageId() == null ? "" : page.getPageId();
    String token = Names.toClassName(pageId);
    boolean numericLead = token.isEmpty() || Character.isDigit(token.charAt(0));
    if (numericLead) {
      return eventClassName + "Page" + token.replaceAll("[^A-Za-z0-9]", "");
    }
    return eventClassName + token + "Page";
  }

  /**
   * Page-field count above which a single page's field placements are split out of its
   * {@code apply(fields)} method into {@code <Page>FieldsN.apply(fields)} helper classes. A single
   * page that places many hundreds of fields (prl's waManageOrders) overflows the JVM's 64&nbsp;KB
   * per-method bytecode limit; each fragment handles a slice so no one method exceeds it. This is the
   * <em>only</em> place the numbered-fragment form survives (documented overflow, finding #2).
   */
  private static final int FIELDS_PER_HELPER = 120;

  /**
   * Builds one page class: a {@code final} class with a private ctor and a
   * {@code static apply(FieldCollectionBuilder)} that emits {@code fields.page(id)}, the optional
   * page label / show condition, and the page's field placements. When the page alone exceeds
   * {@link #FIELDS_PER_HELPER}, its placements are split across {@code <Page>FieldsN} fragment
   * classes invoked in order. The page class and any fragment classes are appended to
   * {@code pageClasses}.
   */
  private void buildPageClass(
      String pageClassName, PageModel page, EventModel event, CaseTypeModel model,
      EmitContext context, ClassName caseData, ClassName state, ClassName userRole, String pagePkg,
      List<TypeSpec> pageClasses) {

    ParameterizedTypeName fieldsType = fieldsBuilderType(caseData, state, userRole);
    CodeBlock.Builder apply = CodeBlock.builder();
    emitPageHeader(apply, page);

    int weight = pageWeight(page, model, event);
    if (weight <= FIELDS_PER_HELPER) {
      emitPageFields(apply, page.getFields(), model, caseData, context, event);
    } else {
      // Documented overflow: split this single page's placements across FieldsN fragment classes so
      // each fragment's serializable getter lambdas stay under the bytecode cap. A COMPLEX field that
      // carries derived CaseEventToComplexTypes member overrides emits one lambda per member, so it
      // counts for its member total, not one, when budgeting the split (fpl's amendChildren places
      // ~16 complex fields of ~27 members each on one page).
      List<List<PageModel.PageField>> groups = groupFields(page.getFields(), model, event);
      for (int i = 0; i < groups.size(); i++) {
        CodeBlock.Builder fragBody = CodeBlock.builder();
        emitPageFields(fragBody, groups.get(i), model, caseData, context, event);
        String fragName = pageClassName + "Fields" + (i + 1);
        pageClasses.add(TypeSpec.classBuilder(fragName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addJavadoc(context.banner(model.getCaseTypeId(), null) + "\n\n"
                + "<p>Field placements for page {@code $L} of event {@code $L} (part $L of $L).\n",
                page.getPageId(), event.getId(), i + 1, groups.size())
            .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
            .addMethod(MethodSpec.methodBuilder("apply")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(fieldsType, "fields")
                .addJavadoc("@param fields the event's field-collection builder\n")
                .addCode(fragBody.build())
                .build())
            .build());
        apply.addStatement("$T.apply(fields)", ClassName.get(pagePkg, fragName));
      }
    }

    pageClasses.add(TypeSpec.classBuilder(pageClassName)
        .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
        .addJavadoc(context.banner(model.getCaseTypeId(), null) + "\n\n"
            + "<p>Wizard page {@code $L} of event {@code $L}.\n",
            page.getPageId(), event.getId())
        .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
        .addMethod(MethodSpec.methodBuilder("apply")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(fieldsType, "fields")
            .addJavadoc("Applies this page's fields to the event.\n\n"
                + "@param fields the event's field-collection builder\n")
            .addCode(apply.build())
            .build())
        .build());
  }

  /**
   * The lambda weight of a whole page: the sum of every field's {@link #fieldWeight}. Drives whether
   * the page's placements are split across fragment classes to stay under the JVM's per-method
   * bytecode cap.
   */
  private int pageWeight(PageModel page, CaseTypeModel model, EventModel event) {
    if (page.getFields() == null) {
      return 0;
    }
    int weight = 0;
    for (PageModel.PageField field : page.getFields()) {
      weight += fieldWeight(field, model, event);
    }
    return weight;
  }

  /**
   * The lambda weight of one field placement: 1 for an ordinary field, or 1 plus the derived
   * complex-member count for a COMPLEX field that carries {@code CaseEventToComplexTypes} member
   * overrides (each member emits its own serializable getter lambda inside the complex block).
   */
  private int fieldWeight(PageModel.PageField field, CaseTypeModel model, EventModel event) {
    if (field.getDisplayContext() != null
        && "COMPLEX".equalsIgnoreCase(field.getDisplayContext().trim())
        && model.getEventComplexTypeGroups() != null) {
      EventComplexTypeGroup group =
          model.getEventComplexTypeGroups().get(event.getId() + "\u001f" + field.getCaseFieldId());
      if (group != null) {
        return 1 + group.getMembers().size();
      }
    }
    return 1;
  }

  /**
   * Groups a page's fields into runs whose cumulative {@link #fieldWeight} stays at or below
   * {@link #FIELDS_PER_HELPER}, so each generated fragment method stays under the bytecode limit. A
   * single field heavier than the budget on its own (a COMPLEX field with very many derived members)
   * still occupies its own group rather than being split mid-field.
   */
  private List<List<PageModel.PageField>> groupFields(
      List<PageModel.PageField> fields, CaseTypeModel model, EventModel event) {
    List<List<PageModel.PageField>> groups = new ArrayList<>();
    List<PageModel.PageField> current = new ArrayList<>();
    int currentWeight = 0;
    for (PageModel.PageField field : fields) {
      int weight = fieldWeight(field, model, event);
      if (!current.isEmpty() && currentWeight + weight > FIELDS_PER_HELPER) {
        groups.add(current);
        current = new ArrayList<>();
        currentWeight = 0;
      }
      current.add(field);
      currentWeight += weight;
    }
    if (!current.isEmpty()) {
      groups.add(current);
    }
    return groups;
  }

  /**
   * Emits a page's {@code fields.page(id)} call and its optional page label / show condition.
   *
   * @param cb the code block being built (a page class's apply method)
   * @param page the page to emit
   */
  private void emitPageHeader(CodeBlock.Builder cb, PageModel page) {
    // Pages always emit page(id) — never page(id, callback). A page's mid-event callback URL is
    // carried through verbatim on the CaseEventToFields passthrough graft (CallBackURLMidEvent),
    // not registered as SDK wiring.
    cb.addStatement("fields.page($S)", page.getPageId());
    if (page.getLabel() != null && !page.getLabel().isEmpty()) {
      cb.addStatement("fields.pageLabel($S)", page.getLabel());
    }
    if (page.getShowCondition() != null && !page.getShowCondition().isEmpty()) {
      cb.addStatement("fields.showCondition($S)", page.getShowCondition());
    }
  }

  /**
   * Emits the field references for one wizard page. Fields folded into a {@code @JsonUnwrapped}
   * cluster are placed inside a {@code .complex(CaseData::getParent) … .done()} block (grouping
   * consecutive members of the same parent), matching how the SDK re-flattens them; ordinary
   * fields are placed directly, deriving the getter from the field's sanitised
   * {@code javaName} rather than its raw CCD id; Label fields (not CaseData members) are
   * emitted as {@code .label(id, text)}; fields absent from the model are recorded as a gap
   * and skipped rather than emitting a broken reference.
   *
   * @param cb the code block being built
   * @param fields the page's fields in order
   * @param model the case type model (supplies the clustered-field reference map and fields)
   * @param caseData the CaseData class name
   * @param emitContext packages and options (supplies the gap collector)
   * @param event the event the page belongs to, for gap reporting
   */
  private void emitPageFields(
      CodeBlock.Builder cb, List<PageModel.PageField> fields, CaseTypeModel model,
      ClassName caseData, EmitContext emitContext, EventModel event) {
    Map<String, ClusteredFieldRef> refs = model.getClusteredFieldRefs() == null
        ? Map.of() : model.getClusteredFieldRefs();
    java.util.Set<String> unplaceable = model.getUnplaceableFieldIds() == null
        ? java.util.Set.of() : model.getUnplaceableFieldIds();
    Map<String, FieldModel> fieldsById = new java.util.LinkedHashMap<>();
    for (FieldModel field : model.getCaseFields()) {
      fieldsById.put(field.getId(), field);
    }
    String modelPkg = caseData.packageName();
    // Each field is emitted as its own `fields.<method>(...)` statement rather than one long
    // chained expression, to keep each apply method under the JVM's 64 KB per-method bytecode
    // limit. A run of clustered members sharing a parent is emitted as a single
    // `fields.complex(parent)....done()` statement (clusters are small), matching how the SDK
    // re-flattens @JsonUnwrapped families.
    String openParent = null;
    CodeBlock.Builder cluster = null;
    for (PageModel.PageField field : fields) {
      String builderMethod = displayContextToMethod(field.getDisplayContext());
      if (unplaceable.contains(field.getCaseFieldId())) {
        // Bug4 (retrofit): the field is reached through a @JsonUnwrapped parent whose getter the
        // model suppresses (@Getter(AccessLevel.NONE), no correctly-named accessor), so no compilable
        // typed method reference exists and the SDK has no public string-id overload for event
        // fields. Flush any open cluster, skip the placement, and record a gap; the field's per-field
        // CaseEventToFields metadata is carried by the column passthrough instead.
        if (openParent != null) {
          cb.addStatement("$L", cluster.add(".done()").build());
          openParent = null;
          cluster = null;
        }
        emitContext.getGaps().add(GapEntry.builder()
            .sheet("CaseEventToFields")
            .rowKey(event.getId() + "/" + field.getCaseFieldId())
            .column("CaseFieldID")
            .value(field.getCaseFieldId())
            .category(GapCategory.UNSUPPORTED_VALUE)
            .action(GapAction.PASSTHROUGH_COLUMN)
            .detail("Event '" + event.getId() + "' page places field '" + field.getCaseFieldId()
                + "' reached through a @JsonUnwrapped parent whose getter the model suppresses with "
                + "@Getter(AccessLevel.NONE) and has no correctly-named accessor; no compilable typed "
                + "getter reference exists, so the placement is skipped and the row's per-field "
                + "metadata is carried by the CaseEventToFields column passthrough")
            .build());
        continue;
      }
      ClusteredFieldRef ref = refs.get(field.getCaseFieldId());
      if (ref != null) {
        // As for the direct-field path below, honour an input ShowSummaryChangeOption=N by
        // selecting the *NoSummary builder variant (the SDK otherwise defaults the flag to Y).
        String clusterMethod = Boolean.FALSE.equals(field.getShowSummary())
            ? builderMethod + "NoSummary" : builderMethod;
        // The cluster type is a generated complex type in modelPkg (generate mode) or, in retrofit
        // mode, the team's own @JsonUnwrapped parent type, which may live in another package.
        String clusterPkg = ref.getClusterTypePackage() != null
            ? ref.getClusterTypePackage() : modelPkg;
        if (ref.getParentHops() != null && !ref.getParentHops().isEmpty()) {
          // Nested @JsonUnwrapped chain (retrofit): the leaf is reached through more than one
          // .complex() hop, so it cannot share a sibling's single .complex(parent) group. Flush any
          // open single-level cluster and emit the full nested chain as its own statement.
          if (openParent != null) {
            cb.addStatement("$L", cluster.add(".done()").build());
            openParent = null;
            cluster = null;
          }
          CodeBlock.Builder nested = CodeBlock.builder();
          nested.add("fields.complex($T::$L)", caseData, ref.getParentGetter());
          String innerPkg = clusterPkg;
          String innerType = ref.getClusterType();
          for (ClusteredFieldRef.Hop hop : ref.getParentHops()) {
            nested.add("\n    .complex($T::$L)", ClassName.get(innerPkg, innerType), hop.getGetter());
            innerType = hop.getType();
            innerPkg = hop.getTypePackage() != null ? hop.getTypePackage() : modelPkg;
          }
          nested.add("\n    .$L($T::$L)", clusterMethod,
              ClassName.get(innerPkg, innerType), ref.getMemberGetter());
          nested.add(fieldMetadataChain(field));
          nested.add(publishChain(field, event));
          // One .done() to close the leaf's enclosing block plus one per hop back to CaseData.
          for (int i = 0; i <= ref.getParentHops().size(); i++) {
            nested.add(".done()");
          }
          cb.addStatement("$L", nested.build());
          continue;
        }
        if (!ref.getParentGetter().equals(openParent)) {
          if (openParent != null) {
            cb.addStatement("$L", cluster.add(".done()").build());
          }
          cluster = CodeBlock.builder();
          cluster.add("fields.complex($T::$L)", caseData, ref.getParentGetter());
          openParent = ref.getParentGetter();
        }
        cluster.add("\n    .$L($T::$L)", clusterMethod,
            ClassName.get(clusterPkg, ref.getClusterType()), ref.getMemberGetter());
        cluster.add(fieldMetadataChain(field));
        // Per-field Publish/PublishAs override the event's publishToCamunda() cascade; chain onto
        // the just-added member so the generated CaseEventToFields.Publish matches the input.
        cluster.add(publishChain(field, event));
        continue;
      }
      if (openParent != null) {
        cb.addStatement("$L", cluster.add(".done()").build());
        openParent = null;
        cluster = null;
      }
      FieldModel fieldModel = fieldsById.get(field.getCaseFieldId());
      if (fieldModel == null) {
        emitContext.getGaps().add(GapEntry.builder()
            .sheet("CaseEventToFields")
            .rowKey(event.getId() + "/" + field.getCaseFieldId())
            .column("CaseFieldID")
            .value(field.getCaseFieldId())
            .category(GapCategory.UNSUPPORTED_VALUE)
            .action(GapAction.PASSTHROUGH_COLUMN)
            .detail("Event '" + event.getId() + "' page references field '"
                + field.getCaseFieldId()
                + "' not present on CaseData; the CaseEventToFields row is passed through")
            .build());
        continue;
      }
      if (fieldModel.getOverlayTags() != null && !fieldModel.getOverlayTags().isEmpty()) {
        // The field is overlay-only AND its suffix has no configured predicate, so it is neither a
        // CaseData member nor a gated member (a gated field has its overlay tags cleared and a
        // @CCD(gate) set, and is placed normally below). CaseDataEmitter does not emit it onto
        // CaseData, so a CaseData::getX reference here would not compile; skip the placement and
        // record the gap rather than emitting a broken reference. Overlay fields with a configured
        // predicate now round-trip as generation-time gated members (see FieldModel.gate).
        emitContext.getGaps().add(GapEntry.builder()
            .sheet("CaseEventToFields")
            .rowKey(event.getId() + "/" + field.getCaseFieldId())
            .column("CaseFieldID")
            .value(field.getCaseFieldId())
            .category(GapCategory.UNSUPPORTED_VALUE)
            .action(GapAction.OMITTED_FAIL)
            .detail("Event '" + event.getId() + "' page places overlay-only field '"
                + field.getCaseFieldId() + "' (overlay " + fieldModel.getOverlayTags()
                + ") whose suffix has no configured environment predicate, so it is neither a"
                + " CaseData member nor a gated member; its placement is not reproduced")
            .build());
        continue;
      }
      if ("Label".equals(fieldModel.getFieldType())) {
        // Label fields are real CaseData members (see CaseDataEmitter); reference them as
        // readonly (immutable, like the SDK's own .label()) so the field appears on the event
        // without the generator inventing a CaseField row that omits the input's metadata. Honour
        // the input's ShowSummaryChangeOption via the NoSummary variant when it is N.
        String labelMethod = Boolean.FALSE.equals(field.getShowSummary())
            ? "readonlyNoSummary" : "readonly";
        // A Label field is non-COMPLEX, so the SDK cascades a publishing event's Publish=Y onto it;
        // chain publish(false) when the input did not publish it (matching the retired cascade rule).
        CodeBlock.Builder labelStmt = CodeBlock.builder();
        labelStmt.add("fields.$L($T::get$L)", labelMethod, caseData,
            capitalise(fieldModel.getJavaName()));
        labelStmt.add(fieldMetadataChain(field));
        labelStmt.add(publishChain(field, event));
        cb.addStatement("$L", labelStmt.build());
        continue;
      }
      if (field.getDisplayContext() != null
          && "COMPLEX".equalsIgnoreCase(field.getDisplayContext().trim())) {
        // A complex-typed field placed on a page: the SDK renders DisplayContext=COMPLEX via a
        // .complex(getter) block. When the CaseEventToComplexTypes sheet carries per-member event
        // overrides for this (event, field) that the linker could derive, the block gains those
        // members as .optional/.mandatory/.readonly(Type::getMember) calls (with .eventLabel /
        // .eventHint / .fieldShowCondition / .pageId); otherwise the block stays empty. Honour the
        // input's ShowSummaryChangeOption via the two-arg complex(getter, summary) overload when it
        // is N (the SDK otherwise defaults ShowSummaryChangeOption to Y).
        EventComplexTypeGroup group = model.getEventComplexTypeGroups() == null
            ? null
            : model.getEventComplexTypeGroups().get(event.getId() + "\u001f" + field.getCaseFieldId());
        CodeBlock.Builder complexStmt = CodeBlock.builder();
        if (Boolean.FALSE.equals(field.getShowSummary())) {
          complexStmt.add("fields.complex($T::get$L, false)", caseData,
              capitalise(fieldModel.getJavaName()));
        } else {
          complexStmt.add("fields.complex($T::get$L)", caseData,
              capitalise(fieldModel.getJavaName()));
        }
        if (group != null) {
          complexStmt.add(complexMemberChains(group, emitContext));
        }
        complexStmt.add(".done()");
        // The .complex(...).done() call returns the FieldCollectionBuilder, so the fluent
        // lastField() metadata setters act on the complex field just placed — emit its per-field
        // CaseEventToFields metadata as Java rather than via the retired column graft.
        complexStmt.add(fieldMetadataChain(field));
        cb.addStatement("$L", complexStmt.build());
        continue;
      }
      // The SDK field builder defaults ShowSummaryChangeOption to Y; when the input explicitly
      // sets it to N, select the *NoSummary builder variant so the regenerated value matches.
      String method = Boolean.FALSE.equals(field.getShowSummary())
          ? builderMethod + "NoSummary" : builderMethod;
      String getter = "get" + capitalise(fieldModel.getJavaName());
      // Per-field CaseEventToFields metadata via the fluent lastField()-style FieldCollectionBuilder
      // setters, available after EVERY placement call (optional/mandatory/readonly and their
      // *NoSummary variants all return the FieldCollectionBuilder): FieldShowCondition,
      // CaseEventFieldLabel/Hint, DisplayContextParameter, DefaultValue, RetainHiddenValue,
      // ShowSummaryContentOption and NullifyByDefault. Emitting them here retires the per-field
      // CaseEventToFields column graft entirely for placed fields (see
      // DefaultDefinitionLinker.buildEventFieldColumnPassthrough, now callback-only).
      CodeBlock.Builder stmt = CodeBlock.builder();
      stmt.add("fields.$L($T::$L)", method, caseData, getter);
      stmt.add(fieldMetadataChain(field));
      stmt.add(publishChain(field, event));
      cb.addStatement("$L", stmt.build());
    }
    if (openParent != null) {
      cb.addStatement("$L", cluster.add(".done()").build());
    }
  }

  /**
   * A {@code .publish(false)}/{@code .publish(true)}/{@code .publishAs(...)} chain for a field whose
   * per-field {@code Publish}/{@code PublishAs} overrides the event's {@code publishToCamunda()}
   * cascade, or an empty block when the field matches the event default.
   *
   * <p>{@code Publish} and {@code PublishAs} are unrelated columns to the definition-store importer
   * ({@code EventCaseFieldParser}/{@code PublishFieldsValidator} read and validate them
   * independently — a row may carry {@code PublishAs} while {@code Publish} is {@code N} or absent),
   * so {@code publishAs(...)} is emitted purely for the alias and never implies {@code publish}. An
   * explicit {@code publish(flag)} is always emitted alongside it whenever the field's resolved
   * publish intent (input {@code Publish=Y} → published; anything else → not) differs from the
   * event-level default — this is what the retired {@code PUBLISH_CASCADE} rule used to forgive.
   *
   * @param field the page field
   * @param event the owning event (its publish flag is the field default)
   * @return the chained publish call(s), possibly empty
   */
  private CodeBlock publishChain(PageModel.PageField field, EventModel event) {
    CodeBlock.Builder cb = CodeBlock.builder();
    boolean eventPublishes = Boolean.TRUE.equals(event.getPublish());
    boolean fieldPublishes = Boolean.TRUE.equals(field.getPublish());
    if (notBlank(field.getPublishAs())) {
      cb.add("\n    .publishAs($S)", field.getPublishAs());
    }
    if (fieldPublishes != eventPublishes) {
      cb.add("\n    .publish($L)", fieldPublishes);
    }
    return cb.build();
  }

  /**
   * The fluent per-field {@code CaseEventToFields} metadata chain appended after a field placement.
   * Every setter is a {@code lastField()}-style {@code FieldCollectionBuilder} call usable after any
   * placement context (including {@code readonly}/{@code *NoSummary}), so all of these are emitted as
   * Java rather than grafted: {@code FieldShowCondition}, {@code CaseEventFieldLabel/Hint},
   * {@code DisplayContextParameter}, {@code DefaultValue} (raw string), {@code RetainHiddenValue},
   * {@code ShowSummaryContentOption} and {@code NullifyByDefault}. An empty chain when the field sets
   * none of them, keeping the terse common case unchanged.
   *
   * @param field the page field
   * @return the chained metadata calls, possibly empty
   */
  private CodeBlock fieldMetadataChain(PageModel.PageField field) {
    CodeBlock.Builder cb = CodeBlock.builder();
    if (notBlank(field.getShowCondition())) {
      cb.add("\n    .fieldShowCondition($S)", field.getShowCondition());
    }
    if (notBlank(field.getLabel())) {
      cb.add("\n    .caseEventFieldLabel($S)", field.getLabel());
    }
    if (notBlank(field.getHint())) {
      cb.add("\n    .caseEventFieldHint($S)", field.getHint());
    }
    if (notBlank(field.getDisplayContextParameter())) {
      cb.add("\n    .displayContextParameter($S)", field.getDisplayContextParameter());
    }
    if (notBlank(field.getDefaultValue())) {
      cb.add("\n    .defaultValue($S)", field.getDefaultValue());
    }
    if (Boolean.TRUE.equals(field.getRetainHiddenValue())) {
      cb.add("\n    .retainHiddenValue()");
    }
    if (field.getShowSummaryContentOption() != null) {
      cb.add("\n    .showSummaryContentOption($L)", field.getShowSummaryContentOption());
    }
    if (Boolean.TRUE.equals(field.getNullifyByDefault())) {
      cb.add("\n    .nullifyByDefault()");
    }
    return cb.build();
  }

  private static boolean notBlank(String s) {
    return s != null && !s.isEmpty();
  }

  /**
   * The per-member override calls emitted inside a complex field's {@code fields.complex(getter)}
   * block for a derived {@code CaseEventToComplexTypes} group: each member descends through its
   * {@code .complex(hop)} chain (for a dotted {@code ListElementCode}), places the leaf via
   * {@code .optional/.mandatory/.readonly(Type::getMember)}, carries its event-scoped
   * {@code .eventLabel/.eventHint/.fieldShowCondition/.pageId}, then pops every hop it opened with
   * {@code .done()} so the next member starts back at the root complex level. The enclosing block's
   * own {@code .done()} is emitted by the caller.
   *
   * <p>The columns these calls reproduce ({@code DisplayContext}, {@code ListElementCode},
   * {@code EventElementLabel}, {@code EventHintText}, {@code FieldShowCondition}, {@code PageID}) are
   * exactly those the linker leaves out of the companion graft; the row's {@code ID},
   * {@code FieldDisplayOrder} and any exotic tail are grafted back over the generated rows (see
   * {@code DefaultDefinitionLinker.buildEventToComplexTypesPassthrough}).
   *
   * @param group the resolved member overrides for one complex field on one event
   * @param context the emit context (for the model package the generated complex types live in)
   * @return the chained member-override calls
   */
  private CodeBlock complexMemberChains(EventComplexTypeGroup group, EmitContext context) {
    CodeBlock.Builder cb = CodeBlock.builder();
    for (EventComplexTypeGroup.Member member : group.getMembers()) {
      for (EventComplexTypeGroup.Hop hop : member.getHops()) {
        cb.add("\n    .complex($T::$L)",
            typeName(hop.getDeclaringType(), context), hop.getGetter());
      }
      cb.add("\n    .$L($T::$L)", member.getContextMethod(),
          typeName(member.getLeafType(), context), member.getLeafGetter());
      if (notBlank(member.getShowCondition())) {
        cb.add("\n    .fieldShowCondition($S)", member.getShowCondition());
      }
      if (notBlank(member.getEventLabel())) {
        cb.add("\n    .eventLabel($S)", member.getEventLabel());
      }
      if (notBlank(member.getEventHint())) {
        cb.add("\n    .eventHint($S)", member.getEventHint());
      }
      if (notBlank(member.getPageId())) {
        cb.add("\n    .pageId($S)", member.getPageId());
      }
      // Pop each nested .complex(hop) opened for this member, back to the root complex level.
      for (int i = 0; i < member.getHops().size(); i++) {
        cb.add(".done()");
      }
    }
    return cb.build();
  }

  /**
   * The {@code ClassName} for an {@link EventComplexTypeGroup.TypeRef}: the fully-qualified SDK
   * predefined type, or a generated complex type by simple name in the model package.
   */
  private ClassName typeName(EventComplexTypeGroup.TypeRef ref, EmitContext context) {
    if (ref.getPredefinedFqn() != null) {
      return ClassName.bestGuess(ref.getPredefinedFqn());
    }
    return ClassName.get(context.modelPackage(), ref.getSimpleName());
  }

  private CodeBlock buildStateTargeting(EventModel event, ClassName state, EmitContext context) {
    List<String> preStates = event.getPreStates();
    String postState = event.getPostState();
    boolean hasPost = postState != null && !postState.isEmpty() && !"*".equals(postState);
    // Map each CCD state ID to the enum constant to reference: identity in generate mode, but a
    // reused team State enum may name its constant differently from the CCD ID (retrofit).
    String post = hasPost ? context.stateConstant(postState) : postState;

    if (preStates == null || preStates.isEmpty()) {
      // No pre-condition state: an event that creates the case in its post-state, or — when
      // there is no post-state either — one available in every state.
      if (hasPost) {
        return CodeBlock.of("initialState($T.$L)", state, post);
      }
      return CodeBlock.of("forAllStates()");
    }

    if (preStates.size() == 1 && "*".equals(preStates.get(0))) {
      if (!hasPost) {
        return CodeBlock.of("forAllStates()");
      }
      // A transition from any state into a fixed post-state, using the SDK's
      // forStateTransition(EnumSet from, S to) overload.
      return CodeBlock.of("forStateTransition($T.allOf($T.class), $T.$L)",
          ClassName.get("java.util", "EnumSet"), state, state, post);
    }

    if (preStates.size() == 1) {
      String pre = context.stateConstant(preStates.get(0));
      if (!hasPost || preStates.get(0).equals(postState)) {
        return CodeBlock.of("forState($T.$L)", state, pre);
      }
      return CodeBlock.of("forStateTransition($T.$L, $T.$L)", state, pre, state, post);
    }

    // Multiple pre-states.
    CodeBlock.Builder args = CodeBlock.builder();
    for (int i = 0; i < preStates.size(); i++) {
      if (i > 0) {
        args.add(", ");
      }
      args.add("$T.$L", state, context.stateConstant(preStates.get(i)));
    }
    if (hasPost) {
      // A transition from any of several pre-states into a fixed post-state. forStates() sets
      // the post-state equal to the pre-state set, which the generator renders as '*' (a
      // multi-element post set), so use the EnumSet-from overload that fixes a single
      // post-state — even when that state is itself one of the pre-states.
      return CodeBlock.of("forStateTransition($T.of($L), $T.$L)",
          ClassName.get("java.util", "EnumSet"), args.build(), state, post);
    }
    return CodeBlock.of("forStates($L)", args.build());
  }

  private String displayContextToMethod(String displayContext) {
    if (displayContext == null) {
      return "optional";
    }
    return switch (displayContext.toUpperCase()) {
      case "MANDATORY" -> "mandatory";
      case "READONLY" -> "readonly";
      case "HIDDEN" -> "optional";
      default -> "optional";
    };
  }

  private String capitalise(String s) {
    if (s == null || s.isEmpty()) {
      return s;
    }
    return Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }

  /**
   * Appends the varargs {@code .grant(permSet, UserRole.A, UserRole.B, …)} chain for a grant map,
   * one call per distinct CRUD set with all roles that share it (finding #11). Roles are ordered by
   * their constant name for determinism, and the permission set uses the SDK's Permission.CR/CRU/CRUD
   * shortcuts where one matches (finding #5).
   */
  private void appendVarargsGrants(
      CodeBlock.Builder cb, Map<String, String> grants, Map<String, String> roleConstants,
      ClassName userRole, ClassName permission) {
    Map<String, List<String>> byCrud = new LinkedHashMap<>();
    for (Map.Entry<String, String> entry : grants.entrySet()) {
      byCrud.computeIfAbsent(entry.getValue(), k -> new ArrayList<>()).add(entry.getKey());
    }
    for (Map.Entry<String, List<String>> entry : byCrud.entrySet()) {
      List<String> roleConsts = new ArrayList<>();
      for (String roleId : entry.getValue()) {
        roleConsts.add(roleConstants.get(roleId));
      }
      roleConsts.sort(Comparator.naturalOrder());
      CodeBlock.Builder roles = CodeBlock.builder();
      for (int i = 0; i < roleConsts.size(); i++) {
        roles.add(i == 0 ? "$T.$L" : ", $T.$L", userRole, roleConsts.get(i));
      }
      CodeBlock permSet = crudToPermissionSet(entry.getKey(), permission);
      cb.add("\n    .grant($L, $L)", permSet, roles.build());
    }
  }

  /**
   * The grant map an event actually contributes: role ID to CRUD, keeping only roles that resolve
   * to a generated UserRole constant (unknown roles are skipped with a gap at emit time).
   */
  private Map<String, String> resolvableGrants(EventModel event, Map<String, String> roleConstants) {
    Map<String, String> grants = new LinkedHashMap<>();
    if (event.getGrants() == null) {
      return grants;
    }
    for (Map.Entry<String, String> entry : event.getGrants().entrySet()) {
      if (roleConstants.containsKey(entry.getKey())) {
        grants.put(entry.getKey(), entry.getValue());
      }
    }
    return grants;
  }

  private CodeBlock crudToPermissionSet(String crud, ClassName permission) {
    // Prefer the SDK's Permission.CR/CRU/CRUD set shortcuts (finding #5), falling back to an
    // explicit Set.of(Permission.X, …) for any combination without a named constant.
    return Names.permissionSet(crud, permission);
  }

  private Map<String, String> buildRoleConstants(CaseTypeModel model) {
    Map<String, String> index = new java.util.LinkedHashMap<>();
    for (RoleModel role : model.getRoles()) {
      index.put(role.getId(), role.getJavaConstant());
    }
    return index;
  }
}
