package uk.gov.hmcts.ccd.sdk.converter.emit.config;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.lang.model.element.Modifier;
import uk.gov.hmcts.ccd.sdk.converter.api.EmitContext;
import uk.gov.hmcts.ccd.sdk.converter.api.SourceEmitter;
import uk.gov.hmcts.ccd.sdk.converter.model.CaseTypeModel;
import uk.gov.hmcts.ccd.sdk.converter.model.ClusteredFieldRef;
import uk.gov.hmcts.ccd.sdk.converter.model.EventModel;
import uk.gov.hmcts.ccd.sdk.converter.model.FieldModel;
import uk.gov.hmcts.ccd.sdk.converter.model.PageModel;
import uk.gov.hmcts.ccd.sdk.converter.model.RoleModel;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapAction;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapCategory;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapEntry;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Emits one or more {@code CCDConfig} classes, each containing up to
 * {@code options.eventsPerConfig} event-registration methods. Large case types split across
 * multiple numbered classes ({@code …EventsConfig01}, {@code …EventsConfig02}, …) to keep
 * class sizes manageable.
 */
public class EventsConfigEmitter implements SourceEmitter {

  /**
   * Generates the events config class (or classes) for the case type.
   *
   * @param model the linked case type model
   * @param context packages and options
   * @return one JavaFile per generated class
   */
  @Override
  public List<JavaFile> emit(CaseTypeModel model, EmitContext context) {
    List<EventModel> events = model.getEvents();
    if (events == null || events.isEmpty()) {
      return List.of();
    }

    int chunkSize = context.getOptions().getEventsPerConfig();
    // Group events into config classes, capped both by event count (eventsPerConfig) and by a
    // budget on serializable method references (CaseData::getX getters). Every
    // TypedPropertyGetter is a Serializable lambda, so javac synthesises one $deserializeLambda$
    // method per class covering ALL of a class's lambdas; a class with too many field references
    // (fpl's manageOrders/reviewCMO events carry 80-160 each) overflows that single synthetic
    // method's 64 KB bytecode limit ("code too large"). Splitting on the lambda budget keeps it
    // safely under the cap while still honouring eventsPerConfig as the upper bound.
    List<List<EventModel>> chunks = chunkEvents(events, chunkSize);
    boolean multiChunk = chunks.size() > 1;

    String configPkg = context.configPackage();
    String prefix = Names.toClassName(model.getCaseTypeId());

    // Retarget to the team's model/State in retrofit mode (see EmitContext); generate mode keeps
    // the freshly generated <modelPackage>.{CaseData,State,UserRole}.
    ClassName caseData = context.caseDataClass();
    ClassName state = context.stateClass();
    ClassName userRole = context.userRoleClass();
    ClassName configBuilder = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "ConfigBuilder");
    ClassName permission = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "Permission");
    ClassName ccdConfig = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "CCDConfig");

    ParameterizedTypeName builderType =
        ParameterizedTypeName.get(configBuilder, caseData, state, userRole);
    ParameterizedTypeName configType =
        ParameterizedTypeName.get(ccdConfig, caseData, state, userRole);

    List<JavaFile> files = new ArrayList<>();

    // Plan shared grant helpers: a grant map (role -> CRUD) used by GRANT_HELPER_MIN_EVENTS or more
    // events is factored into a named private-static helper method on a per-case-type grants class,
    // so the identical role matrix is written once (finding #11). The plan maps each qualifying
    // grant-map signature to its deterministic helper method name; the helper class is emitted once.
    Map<String, String> grantHelperNames = planGrantHelpers(events, model);
    ClassName grantHelperClass = grantHelperNames.isEmpty()
        ? null : ClassName.get(configPkg, prefix + "EventGrants");

    for (int chunkIdx = 0; chunkIdx < chunks.size(); chunkIdx++) {
      List<EventModel> chunk = chunks.get(chunkIdx);

      String className = multiChunk
          ? String.format("%sEventsConfig%02d", prefix, chunkIdx + 1)
          : prefix + "EventsConfig";

      List<MethodSpec> eventMethods = new ArrayList<>();
      List<MethodSpec> registrationMethods = new ArrayList<>();
      List<TypeSpec> fieldHelperClasses = new ArrayList<>();
      for (EventModel event : chunk) {
        List<MethodSpec> methods = buildEventMethods(
            event, model, context, caseData, state, userRole, permission, configPkg,
            fieldHelperClasses, grantHelperNames, grantHelperClass);
        // The first returned method is the event-registration entry point invoked by configure();
        // any further methods are page-emitting helpers it calls.
        registrationMethods.add(methods.get(0));
        eventMethods.addAll(methods);
      }

      MethodSpec configure = buildConfigure(chunk, builderType, registrationMethods);

      TypeSpec configClass = TypeSpec.classBuilder(className)
          .addModifiers(Modifier.PUBLIC)
          // @Component so component scanning registers this as a CCDConfig bean for the generator.
          .addAnnotation(ClassName.get("org.springframework.stereotype", "Component"))
          .addSuperinterface(configType)
          .addJavadoc(
              context.banner(model.getCaseTypeId(), null) + "\n"
                  + "\n"
                  + "<p>$L of $L event(s) for {@code $L} (config class $L of $L).\n",
              chunk.size(), events.size(), model.getCaseTypeId(),
              chunkIdx + 1, chunks.size())
          .addMethod(configure)
          .addMethods(eventMethods)
          .build();

      // Each large event's field placements live in their own top-level helper classes (see
      // buildEventMethods): javac synthesises one $deserializeLambda$ per class covering every
      // serializable getter lambda it declares, so a single event with hundreds of field getters
      // must spread them across classes to keep that synthetic method under the 64 KB bytecode cap.
      for (TypeSpec helper : fieldHelperClasses) {
        files.add(JavaFile.builder(configPkg, helper)
            .indent("    ")
            .skipJavaLangImports(true)
            .build());
      }

      files.add(JavaFile.builder(configPkg, configClass)
          .indent("    ")
          .skipJavaLangImports(true)
          .build());
    }

    if (grantHelperClass != null) {
      files.add(JavaFile.builder(configPkg,
              buildGrantHelperClass(grantHelperClass.simpleName(), grantHelperNames, model,
                  caseData, state, userRole, permission, context))
          .indent("    ")
          .skipJavaLangImports(true)
          .build());
    }

    return files;
  }

  /**
   * Events sharing an identical grant map must number at least this many before the map is factored
   * into a named shared helper method; below it, inlining the varargs grant on each event reads
   * more directly than a helper call (finding #11).
   */
  private static final int GRANT_HELPER_MIN_EVENTS = 3;

  /**
   * Plans the shared grant helpers: counts how many events carry each distinct grant map (role ->
   * CRUD), and assigns a deterministic helper-method name to every map used by at least
   * {@link #GRANT_HELPER_MIN_EVENTS} events. Returns grant-map signature to helper method name, in
   * descending usage order (ties broken by signature) so naming is stable across runs.
   *
   * @param events the case type's events
   * @param model the case type model (for resolving role IDs to constants)
   * @return the grant-map signature to helper-method-name map (empty when nothing qualifies)
   */
  private Map<String, String> planGrantHelpers(List<EventModel> events, CaseTypeModel model) {
    Map<String, String> roleConstants = buildRoleConstants(model);
    // Count events per grant-map signature, ignoring grants that name an unknown role (those are
    // dropped with a gap at emit time, so they must not contribute to a shared helper's identity).
    Map<String, Integer> counts = new java.util.TreeMap<>();
    Map<String, Map<String, String>> mapsBySignature = new java.util.TreeMap<>();
    for (EventModel event : events) {
      Map<String, String> grants = resolvableGrants(event, roleConstants);
      if (grants.isEmpty()) {
        continue;
      }
      String signature = grantSignature(grants);
      counts.merge(signature, 1, Integer::sum);
      mapsBySignature.putIfAbsent(signature, grants);
    }
    List<String> qualifying = new ArrayList<>();
    for (Map.Entry<String, Integer> entry : counts.entrySet()) {
      if (entry.getValue() >= GRANT_HELPER_MIN_EVENTS) {
        qualifying.add(entry.getKey());
      }
    }
    // Most-used first (ties by signature — the TreeMap iteration order) so the highest-value shared
    // matrix gets the plainest name; deterministic regardless of event order.
    qualifying.sort(Comparator.<String>comparingInt(s -> -counts.get(s)).thenComparing(s -> s));
    Map<String, String> names = new LinkedHashMap<>();
    Set<String> used = new LinkedHashSet<>();
    for (String signature : qualifying) {
      String base = grantHelperName(mapsBySignature.get(signature), roleConstants);
      String name = base;
      int suffix = 2;
      while (!used.add(name)) {
        name = base + (suffix++);
      }
      names.put(signature, name);
    }
    return names;
  }

  /**
   * The grant map an event actually contributes: role ID to CRUD, keeping only roles that resolve
   * to a generated UserRole constant (unknown roles are skipped with a gap at emit time).
   */
  private Map<String, String> resolvableGrants(EventModel event, Map<String, String> roleConstants) {
    Map<String, String> grants = new LinkedHashMap<>();
    if (event.getGrants() == null) {
      return grants;
    }
    for (Map.Entry<String, String> entry : event.getGrants().entrySet()) {
      if (roleConstants.containsKey(entry.getKey())) {
        grants.put(entry.getKey(), entry.getValue());
      }
    }
    return grants;
  }

  /** A stable signature of a grant map (role -> CRUD), independent of insertion order. */
  private String grantSignature(Map<String, String> grants) {
    StringBuilder sb = new StringBuilder();
    for (Map.Entry<String, String> entry : new java.util.TreeMap<>(grants).entrySet()) {
      sb.append(entry.getKey()).append('=').append(entry.getValue()).append(';');
    }
    return sb.toString();
  }

  /**
   * A deterministic helper-method name for a shared grant map, derived from its role constants and
   * CRUD (e.g. {@code {caseworker=CRU}} -> {@code caseworkerCruGrants}). Falls back to a digest when
   * the derived name would be unwieldy.
   */
  private String grantHelperName(Map<String, String> grants, Map<String, String> roleConstants) {
    java.util.TreeMap<String, String> sorted = new java.util.TreeMap<>(grants);
    StringBuilder sb = new StringBuilder();
    for (Map.Entry<String, String> entry : sorted.entrySet()) {
      String roleConst = roleConstants.getOrDefault(entry.getKey(), entry.getKey());
      String token = camelToken(roleConst) + crudToken(entry.getValue());
      sb.append(sb.length() == 0 ? lowerFirst(token) : token);
    }
    String candidate = sb + "Grants";
    if (candidate.length() <= 70) {
      return candidate;
    }
    Map.Entry<String, String> first = sorted.firstEntry();
    String firstToken = camelToken(roleConstants.getOrDefault(first.getKey(), first.getKey()))
        + crudToken(first.getValue());
    return lowerFirst(firstToken) + "Plus" + (sorted.size() - 1) + "RolesGrants";
  }

  /**
   * A CONSTANT_CASE role token turned into a PascalCase word: {@code CASE_WORKER} -> {@code CaseWorker}.
   */
  private String camelToken(String constant) {
    String[] parts = constant.split("[^A-Za-z0-9]+");
    StringBuilder sb = new StringBuilder();
    for (String part : parts) {
      if (!part.isEmpty()) {
        sb.append(Character.toUpperCase(part.charAt(0)));
        if (part.length() > 1) {
          sb.append(part.substring(1).toLowerCase());
        }
      }
    }
    return sb.toString();
  }

  /**
   * A CRUD string as a title-case token: {@code CRU} -> {@code Cru}, {@code R} -> {@code R}.
   */
  private String crudToken(String crud) {
    if (crud == null || crud.isEmpty()) {
      return "";
    }
    String lower = crud.toLowerCase();
    return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
  }

  private String lowerFirst(String s) {
    return s.isEmpty() ? s : Character.toLowerCase(s.charAt(0)) + s.substring(1);
  }

  /**
   * Builds the {@code <Prefix>EventGrants} helper class: one {@code static <name>(EventBuilder)}
   * method per shared grant map, each applying the map's varargs grants to the passed event builder.
   * Invoked from every event that carries that exact grant map (finding #11).
   */
  private TypeSpec buildGrantHelperClass(
      String className, Map<String, String> grantHelperNames, CaseTypeModel model,
      ClassName caseData, ClassName state, ClassName userRole, ClassName permission,
      EmitContext context) {
    Map<String, String> roleConstants = buildRoleConstants(model);
    ClassName eventBuilder = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "Event", "EventBuilder");
    ParameterizedTypeName builderType =
        ParameterizedTypeName.get(eventBuilder, caseData, userRole, state);

    // Recover each signature's grant map from its representative event so the helper body can be
    // rebuilt; the signature encodes role=CRUD pairs directly.
    TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
        .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
        .addJavadoc(context.banner(model.getCaseTypeId(), null) + "\n\n"
            + "<p>Shared event grant matrices for {@code $L}: each method applies a role/permission\n"
            + "set reused across three or more events.\n", model.getCaseTypeId())
        .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build());

    for (Map.Entry<String, String> entry : grantHelperNames.entrySet()) {
      Map<String, String> grants = parseGrantSignature(entry.getKey());
      CodeBlock.Builder body = CodeBlock.builder();
      body.add("return event");
      appendVarargsGrants(body, grants, roleConstants, userRole, permission);
      body.add(";\n");
      classBuilder.addMethod(MethodSpec.methodBuilder(entry.getValue())
          .addModifiers(Modifier.STATIC)
          .returns(builderType)
          .addParameter(builderType, "event")
          .addJavadoc("@param event the event builder to apply the shared grants to\n"
              + "@return the same event builder, for chaining\n")
          .addCode(body.build())
          .build());
    }
    return classBuilder.build();
  }

  /**
   * Reverses {@link #grantSignature}: parses {@code role=CRUD;role=CRUD;} into an ordered map.
   */
  private Map<String, String> parseGrantSignature(String signature) {
    Map<String, String> grants = new LinkedHashMap<>();
    for (String part : signature.split(";")) {
      if (part.isEmpty()) {
        continue;
      }
      int eq = part.indexOf('=');
      grants.put(part.substring(0, eq), part.substring(eq + 1));
    }
    return grants;
  }

  /**
   * Appends the varargs {@code .grant(permSet, UserRole.A, UserRole.B, …)} chain for a grant map,
   * one call per distinct CRUD set with all roles that share it (finding #11). Roles are ordered by
   * their constant name for determinism.
   */
  private void appendVarargsGrants(
      CodeBlock.Builder cb, Map<String, String> grants, Map<String, String> roleConstants,
      ClassName userRole, ClassName permission) {
    Map<String, List<String>> byCrud = new LinkedHashMap<>();
    for (Map.Entry<String, String> entry : grants.entrySet()) {
      byCrud.computeIfAbsent(entry.getValue(), k -> new ArrayList<>()).add(entry.getKey());
    }
    for (Map.Entry<String, List<String>> entry : byCrud.entrySet()) {
      List<String> roleConsts = new ArrayList<>();
      for (String roleId : entry.getValue()) {
        roleConsts.add(roleConstants.get(roleId));
      }
      roleConsts.sort(Comparator.naturalOrder());
      CodeBlock.Builder roles = CodeBlock.builder();
      for (int i = 0; i < roleConsts.size(); i++) {
        roles.add(i == 0 ? "$T.$L" : ", $T.$L", userRole, roleConsts.get(i));
      }
      CodeBlock permSet = crudToPermissionSet(entry.getKey(), permission);
      cb.add("\n    .grant($L, $L)", permSet, roles.build());
    }
  }

  /**
   * Serializable method references per config class above which a new class is started. Each such
   * reference contributes a case to javac's synthesised per-class {@code $deserializeLambda$}
   * method; keeping the total well under a class's lambda count bounds that method's bytecode
   * below the 64&nbsp;KB limit. 300 leaves generous headroom (the synthetic method is a small
   * switch per lambda).
   */
  private static final int LAMBDA_BUDGET_PER_CONFIG = 300;

  /**
   * Splits the events into config-class chunks, honouring {@code eventsPerConfig} as an upper
   * bound while also starting a new chunk once the accumulated serializable-method-reference count
   * would exceed {@link #LAMBDA_BUDGET_PER_CONFIG}. A single event always occupies at least one
   * chunk even if its own reference count exceeds the budget.
   *
   * @param events the events in declaration order
   * @param maxEvents the maximum events per config class
   * @return the ordered list of event chunks
   */
  private List<List<EventModel>> chunkEvents(List<EventModel> events, int maxEvents) {
    List<List<EventModel>> chunks = new ArrayList<>();
    List<EventModel> current = new ArrayList<>();
    int lambdas = 0;
    for (EventModel event : events) {
      int cost = estimateLambdas(event);
      if (!current.isEmpty()
          && (current.size() >= maxEvents || lambdas + cost > LAMBDA_BUDGET_PER_CONFIG)) {
        chunks.add(current);
        current = new ArrayList<>();
        lambdas = 0;
      }
      current.add(event);
      lambdas += cost;
    }
    if (!current.isEmpty()) {
      chunks.add(current);
    }
    return chunks;
  }

  /**
   * Rough count of the serializable method references an event's generated method will emit: one
   * per page field (the {@code CaseData::getX} getter). Only the relative magnitude matters for
   * chunking.
   *
   * @param event the event
   * @return an estimate of the serializable lambdas the event contributes
   */
  private int estimateLambdas(EventModel event) {
    int count = 0;
    if (event.getPages() != null) {
      for (PageModel page : event.getPages()) {
        if (page.getFields() != null) {
          count += page.getFields().size();
        }
      }
    }
    return count;
  }

  private MethodSpec buildConfigure(
      List<EventModel> chunk, ParameterizedTypeName builderType,
      List<MethodSpec> eventMethods) {
    CodeBlock.Builder cb = CodeBlock.builder();
    for (MethodSpec method : eventMethods) {
      cb.addStatement("$N(builder)", method);
    }
    return MethodSpec.methodBuilder("configure")
        .addAnnotation(Override.class)
        .addModifiers(Modifier.PUBLIC)
        .addParameter(builderType, "builder")
        .addJavadoc(
            "Registers all events handled by this config class.\n"
                + "\n"
                + "@param builder the config builder\n")
        .addCode(cb.build())
        .build();
  }

  /**
   * Page-field count above which a single event's field placements are split out of the event
   * method into {@code <event>_fieldsN(fields)} helper methods. A single event method that places
   * many hundreds of fields (prl's waManageOrders: 574 across ~25 pages) overflows the JVM's 64 KB
   * per-method bytecode limit; each helper handles a slice of pages so no one method exceeds it.
   */
  private static final int FIELDS_PER_HELPER = 120;

  private List<MethodSpec> buildEventMethods(
      EventModel event, CaseTypeModel model, EmitContext context,
      ClassName caseData, ClassName state, ClassName userRole, ClassName permission,
      String configPkg, List<TypeSpec> fieldHelperClasses,
      Map<String, String> grantHelperNames, ClassName grantHelperClass) {

    CodeBlock body = buildEventBody(
        event, model, context, caseData, state, userRole, permission, configPkg,
        fieldHelperClasses, grantHelperNames, grantHelperClass);

    MethodSpec.Builder method = MethodSpec.methodBuilder(event.getJavaName())
        .addModifiers(Modifier.PRIVATE)
        .addParameter(
            ParameterizedTypeName.get(
                ClassName.get("uk.gov.hmcts.ccd.sdk.api", "ConfigBuilder"),
                caseData, state, userRole),
            "builder");

    if (event.getOverlayCondition() != null) {
      ClassName envFlags = ClassName.get(context.modelPackage(), "EnvironmentFlags");
      // Non-negated: register only when the flag matches, so skip when it does not.
      // Negated: register only when the flag does not match, so skip when it does.
      CodeBlock guard = event.getOverlayCondition().isNegated()
          ? CodeBlock.of("if ($T.flag($S, $S)) return",
              envFlags,
              event.getOverlayCondition().getEnvVar(),
              event.getOverlayCondition().getExpectedValue())
          : CodeBlock.of("if (!$T.flag($S, $S)) return",
              envFlags,
              event.getOverlayCondition().getEnvVar(),
              event.getOverlayCondition().getExpectedValue());
      method
          .addJavadoc(
              "Registers overlay event {@code $L} (active when $L=$L).\n\n"
                  + "@param builder the config builder\n",
              event.getId(),
              event.getOverlayCondition().getEnvVar(),
              event.getOverlayCondition().getExpectedValue())
          .addStatement(guard);
    } else {
      method.addJavadoc("Registers event {@code $L}.\n\n@param builder the config builder\n",
          event.getId());
    }

    return List.of(method.addCode(body).build());
  }

  /**
   * The generic type of the {@code fields} builder returned by {@code builder.event(id)….fields()},
   * used to type the parameter of a split-out page-emitting helper method.
   */
  private static ParameterizedTypeName fieldsBuilderType(
      ClassName caseData, ClassName state, ClassName userRole) {
    ClassName fieldCollectionBuilder = ClassName.get(
        "uk.gov.hmcts.ccd.sdk.api", "FieldCollection", "FieldCollectionBuilder");
    ClassName eventBuilder = ClassName.get("uk.gov.hmcts.ccd.sdk.api", "Event", "EventBuilder");
    return ParameterizedTypeName.get(fieldCollectionBuilder, caseData, state,
        ParameterizedTypeName.get(eventBuilder, caseData, userRole, state));
  }

  private CodeBlock buildEventBody(
      EventModel event, CaseTypeModel model, EmitContext context,
      ClassName caseData, ClassName state, ClassName userRole, ClassName permission,
      String configPkg, List<TypeSpec> fieldHelperClasses,
      Map<String, String> grantHelperNames, ClassName grantHelperClass) {

    // builder.event(id) chain, up to and including .explicitGrants(). Built as its own expression so
    // it can be wrapped in a shared grant-helper call (finding #11) before the .fields()/statement
    // continuation.
    CodeBlock.Builder headerBuilder = CodeBlock.builder();
    headerBuilder.add("builder.event($S)", event.getId());
    headerBuilder.add("\n    .").add(buildStateTargeting(event, state, context));
    headerBuilder.add("\n    .name($S)", event.getName());
    if (event.getDescription() != null && !event.getDescription().isEmpty()
        && !event.getDescription().equals(event.getName())) {
      headerBuilder.add("\n    .description($S)", event.getDescription());
    }
    if (event.getDisplayOrder() != null) {
      headerBuilder.add("\n    .displayOrder($L)", event.getDisplayOrder());
    }
    if (event.getShowCondition() != null && !event.getShowCondition().isEmpty()) {
      headerBuilder.add("\n    .showCondition($S)", event.getShowCondition());
    }
    if (Boolean.TRUE.equals(event.getShowSummary())) {
      headerBuilder.add("\n    .showSummary()");
    } else if (Boolean.FALSE.equals(event.getShowSummary())) {
      headerBuilder.add("\n    .showSummary(false)");
    }
    if (Boolean.TRUE.equals(event.getShowEventNotes())) {
      headerBuilder.add("\n    .showEventNotes()");
    }
    if (event.getEndButtonLabel() != null && !event.getEndButtonLabel().isEmpty()
        && !event.getEndButtonLabel().equals("Save and continue")) {
      headerBuilder.add("\n    .endButtonLabel($S)", event.getEndButtonLabel());
    }
    if (Boolean.TRUE.equals(event.getPublish())) {
      headerBuilder.add("\n    .publishToCamunda()");
    }
    if (Boolean.TRUE.equals(event.getSignificant())) {
      // CaseEvent SignificantEvent flag, emitted via the builder rather than the CaseEvent graft.
      headerBuilder.add("\n    .significant()");
    }
    if (Boolean.TRUE.equals(event.getCanSaveDraft())) {
      // CaseEvent CanSaveDraft flag, emitted via the builder rather than a residual/graft. The
      // importer only allows this on create events (no pre-state); the input already respects that.
      headerBuilder.add("\n    .canSaveDraft()");
    }
    if (event.getTtlIncrement() != null) {
      headerBuilder.add("\n    .ttlIncrement($L)", event.getTtlIncrement());
    }

    // Explicit grants on every event. A converted config must reproduce the input's
    // AuthorisationCaseField grants EXACTLY, so an event's role grants must NOT cascade onto the
    // fields it places on a page. Without .explicitGrants() the SDK's AuthorisationCaseFieldGenerator
    // derives each field's CRUD from the union of the grants of every event that shows it (widening
    // R->CRUD, CRU->CRUD via the mutable-list D injection, etc.); with it, non-immutable fields
    // derive their CRUD solely from their @CCD(access=...) classes (see AccessClassComputer), which
    // the converter sizes to the input. Immutable fields (Label/READONLY) still receive CR — that
    // residual is the maintainer-accepted IMMUTABLE_FIELD_CR difference.
    headerBuilder.add("\n    .explicitGrants()");

    // Grants. The role/CRUD matrix is emitted as varargs-role .grant(permSet, A, B, …) — one call
    // per distinct permission set (finding #11) — either inline or, when this exact grant map is
    // shared by three or more events, via a single named shared-helper call that wraps the header.
    Map<String, String> roleConstants = buildRoleConstants(model);
    Map<String, String> resolvableGrants = resolvableGrants(event, roleConstants);
    // Any grant naming an unknown role is dropped with a gap (it is excluded from resolvableGrants
    // and from the shared-helper plan, so both paths agree).
    if (event.getGrants() != null) {
      for (Map.Entry<String, String> entry : event.getGrants().entrySet()) {
        if (!roleConstants.containsKey(entry.getKey())) {
          context.getGaps().add(GapEntry.builder()
              .sheet("AuthorisationCaseEvent")
              .rowKey(event.getId() + "/" + entry.getKey())
              .column("UserRole")
              .value(entry.getKey())
              .category(GapCategory.UNSUPPORTED_VALUE)
              .action(GapAction.PASSTHROUGH_COLUMN)
              .detail("Event '" + event.getId() + "' grants role '" + entry.getKey()
                  + "' not present on the generated UserRole enum; the grant is skipped")
              .build());
        }
      }
    }

    String helperName = resolvableGrants.isEmpty()
        ? null : grantHelperNames.get(grantSignature(resolvableGrants));
    CodeBlock header;
    if (helperName != null && grantHelperClass != null) {
      // Shared grant matrix: wrap the header expression in the helper call, which applies the
      // varargs grants and returns the same EventBuilder for the .fields()/statement continuation.
      header = CodeBlock.of("$T.$L($L)", grantHelperClass, helperName, headerBuilder.build());
    } else {
      appendVarargsGrants(headerBuilder, resolvableGrants, roleConstants, userRole, permission);
      header = headerBuilder.build();
    }

    CodeBlock.Builder cb = CodeBlock.builder();
    boolean hasPages = event.getPages() != null && !event.getPages().isEmpty();
    if (hasPages) {
      // `var` avoids naming the deeply-nested FieldCollectionBuilder<…> generic type explicitly.
      cb.add("var fields = ");
    }
    cb.add("$L", header);

    // Callbacks (about-to-start/about-to-submit/submitted, their retry policies and per-page
    // mid-event URLs) are never emitted as SDK wiring: the converter carries every CallBackURL*
    // and RetriesTimeout* column through verbatim passthrough (see DefaultDefinitionLinker) so the
    // original endpoints are reproduced byte-for-byte and the migrated service keeps serving them
    // unchanged. Adopting the SDK's in-process callbacks is a later, per-event step (delete that
    // event's passthrough graft and register a handler).

    // Fields / pages. When there are pages the header chain (captured above) terminates at
    // .fields() and is stored in `fields`; each page and field call is then emitted as its own
    // statement rather than one long method-chain expression. A single event can carry well over a
    // hundred field references (fpl's manageOrders), and expressing them as one chained statement
    // overflows the JVM's 64 KB per-method bytecode limit ("code too large"). Every .page()/
    // .field() call returns the same builder, so splitting into statements is behaviourally
    // identical to the chain.
    if (hasPages) {
      cb.add("\n    .fields()");
      cb.addStatement("");
      // A single event method that emits every page/field inline can overflow the JVM's 64 KB
      // per-method limit (prl's waManageOrders places 574 fields). When the event is large, split
      // page emission into `<event>_fieldsN(fields)` helpers, each covering a run of pages whose
      // field count stays under FIELDS_PER_HELPER; the event method then just calls them in order.
      int totalFields = 0;
      for (PageModel page : event.getPages()) {
        totalFields += page.getFields() == null ? 0 : page.getFields().size();
      }
      if (totalFields <= FIELDS_PER_HELPER) {
        for (PageModel page : event.getPages()) {
          emitPage(cb, page, model, caseData, context, event);
        }
        return cb.build();
      }

      ParameterizedTypeName fieldsType = fieldsBuilderType(caseData, state, userRole);
      List<List<PageModel>> pageGroups = groupPages(event.getPages());
      String prefix = Names.toClassName(model.getCaseTypeId());
      for (int i = 0; i < pageGroups.size(); i++) {
        CodeBlock.Builder helperBody = CodeBlock.builder();
        for (PageModel page : pageGroups.get(i)) {
          emitPage(helperBody, page, model, caseData, context, event);
        }
        // Each page-group is a separate top-level class so its serializable getter lambdas land in
        // that class's own $deserializeLambda$, keeping every synthetic method under the bytecode
        // cap. The event method calls the static apply(fields) of each in order.
        String helperClassName =
            prefix + "Event_" + event.getJavaName() + "_Fields" + (i + 1);
        TypeSpec helperClass = TypeSpec.classBuilder(helperClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addJavadoc(context.banner(model.getCaseTypeId(), null) + "\n\n"
                + "<p>Field placements for event {@code $L} (part $L of $L).\n",
                event.getId(), i + 1, pageGroups.size())
            .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
            .addMethod(MethodSpec.methodBuilder("apply")
                .addModifiers(Modifier.STATIC)
                .addParameter(fieldsType, "fields")
                .addJavadoc("@param fields the event's field-collection builder\n")
                .addCode(helperBody.build())
                .build())
            .build();
        fieldHelperClasses.add(helperClass);
        cb.addStatement("$T.apply(fields)", ClassName.get(configPkg, helperClassName));
      }
      return cb.build();
    }

    cb.addStatement("");
    return cb.build();
  }

  /**
   * Groups an event's pages into runs whose cumulative field count stays under
   * {@link #FIELDS_PER_HELPER}, so each generated helper method stays under the bytecode limit. A
   * single page always occupies at least one group even if it alone exceeds the budget.
   *
   * @param pages the event's pages in order
   * @return the ordered page groups
   */
  private List<List<PageModel>> groupPages(List<PageModel> pages) {
    List<List<PageModel>> groups = new ArrayList<>();
    List<PageModel> current = new ArrayList<>();
    int count = 0;
    for (PageModel page : pages) {
      int fieldCount = page.getFields() == null ? 0 : page.getFields().size();
      if (!current.isEmpty() && count + fieldCount > FIELDS_PER_HELPER) {
        groups.add(current);
        current = new ArrayList<>();
        count = 0;
      }
      current.add(page);
      count += fieldCount;
    }
    if (!current.isEmpty()) {
      groups.add(current);
    }
    return groups;
  }

  /**
   * Emits one wizard page: its {@code fields.page(...)} call, optional page label / show condition,
   * and the page's field placements.
   *
   * @param cb the code block being built (an event method or a page-helper method)
   * @param page the page to emit
   * @param model the case type model
   * @param caseData the CaseData class name
   * @param context packages and options
   * @param event the event the page belongs to
   */
  private void emitPage(
      CodeBlock.Builder cb, PageModel page, CaseTypeModel model, ClassName caseData,
      EmitContext context, EventModel event) {
    // Pages always emit page(id) — never page(id, callback). A page's mid-event callback URL is
    // carried through verbatim on the CaseEventToFields passthrough graft (CallBackURLMidEvent),
    // not registered as SDK wiring.
    cb.addStatement("fields.page($S)", page.getPageId());
    if (page.getLabel() != null && !page.getLabel().isEmpty()) {
      cb.addStatement("fields.pageLabel($S)", page.getLabel());
    }
    if (page.getShowCondition() != null && !page.getShowCondition().isEmpty()) {
      cb.addStatement("fields.showCondition($S)", page.getShowCondition());
    }
    emitPageFields(cb, page.getFields(), model, caseData, context, event);
  }

  /**
   * Emits the field references for one wizard page. Fields folded into a {@code @JsonUnwrapped}
   * cluster are placed inside a {@code .complex(CaseData::getParent) … .done()} block (grouping
   * consecutive members of the same parent), matching how the SDK re-flattens them; ordinary
   * fields are placed directly, deriving the getter from the field's sanitised
   * {@code javaName} rather than its raw CCD id; Label fields (not CaseData members) are
   * emitted as {@code .label(id, text)}; fields absent from the model are recorded as a gap
   * and skipped rather than emitting a broken reference.
   *
   * @param cb the code block being built
   * @param fields the page's fields in order
   * @param model the case type model (supplies the clustered-field reference map and fields)
   * @param caseData the CaseData class name
   * @param emitContext packages and options (supplies the gap collector)
   * @param event the event the page belongs to, for gap reporting
   */
  private void emitPageFields(
      CodeBlock.Builder cb, List<PageModel.PageField> fields, CaseTypeModel model,
      ClassName caseData, EmitContext emitContext, EventModel event) {
    Map<String, ClusteredFieldRef> refs = model.getClusteredFieldRefs() == null
        ? Map.of() : model.getClusteredFieldRefs();
    java.util.Set<String> unplaceable = model.getUnplaceableFieldIds() == null
        ? java.util.Set.of() : model.getUnplaceableFieldIds();
    Map<String, FieldModel> fieldsById = new java.util.LinkedHashMap<>();
    for (FieldModel field : model.getCaseFields()) {
      fieldsById.put(field.getId(), field);
    }
    String modelPkg = caseData.packageName();
    // Each field is emitted as its own `fields.<method>(...)` statement rather than one long
    // chained expression, to keep each event method under the JVM's 64 KB per-method bytecode
    // limit. A run of clustered members sharing a parent is emitted as a single
    // `fields.complex(parent)....done()` statement (clusters are small), matching how the SDK
    // re-flattens @JsonUnwrapped families.
    String openParent = null;
    CodeBlock.Builder cluster = null;
    for (PageModel.PageField field : fields) {
      String builderMethod = displayContextToMethod(field.getDisplayContext());
      if (unplaceable.contains(field.getCaseFieldId())) {
        // Bug4 (retrofit): the field is reached through a @JsonUnwrapped parent whose getter the
        // model suppresses (@Getter(AccessLevel.NONE), no correctly-named accessor), so no compilable
        // typed method reference exists and the SDK has no public string-id overload for event
        // fields. Flush any open cluster, skip the placement, and record a gap; the field's per-field
        // CaseEventToFields metadata is carried by the column passthrough instead.
        if (openParent != null) {
          cb.addStatement("$L", cluster.add(".done()").build());
          openParent = null;
          cluster = null;
        }
        emitContext.getGaps().add(GapEntry.builder()
            .sheet("CaseEventToFields")
            .rowKey(event.getId() + "/" + field.getCaseFieldId())
            .column("CaseFieldID")
            .value(field.getCaseFieldId())
            .category(GapCategory.UNSUPPORTED_VALUE)
            .action(GapAction.PASSTHROUGH_COLUMN)
            .detail("Event '" + event.getId() + "' page places field '" + field.getCaseFieldId()
                + "' reached through a @JsonUnwrapped parent whose getter the model suppresses with "
                + "@Getter(AccessLevel.NONE) and has no correctly-named accessor; no compilable typed "
                + "getter reference exists, so the placement is skipped and the row's per-field "
                + "metadata is carried by the CaseEventToFields column passthrough")
            .build());
        continue;
      }
      ClusteredFieldRef ref = refs.get(field.getCaseFieldId());
      if (ref != null) {
        // As for the direct-field path below, honour an input ShowSummaryChangeOption=N by
        // selecting the *NoSummary builder variant (the SDK otherwise defaults the flag to Y).
        String clusterMethod = Boolean.FALSE.equals(field.getShowSummary())
            ? builderMethod + "NoSummary" : builderMethod;
        // The cluster type is a generated complex type in modelPkg (generate mode) or, in retrofit
        // mode, the team's own @JsonUnwrapped parent type, which may live in another package.
        String clusterPkg = ref.getClusterTypePackage() != null
            ? ref.getClusterTypePackage() : modelPkg;
        if (ref.getParentHops() != null && !ref.getParentHops().isEmpty()) {
          // Nested @JsonUnwrapped chain (retrofit): the leaf is reached through more than one
          // .complex() hop, so it cannot share a sibling's single .complex(parent) group. Flush any
          // open single-level cluster and emit the full nested chain as its own statement.
          if (openParent != null) {
            cb.addStatement("$L", cluster.add(".done()").build());
            openParent = null;
            cluster = null;
          }
          CodeBlock.Builder nested = CodeBlock.builder();
          nested.add("fields.complex($T::$L)", caseData, ref.getParentGetter());
          String innerPkg = clusterPkg;
          String innerType = ref.getClusterType();
          for (ClusteredFieldRef.Hop hop : ref.getParentHops()) {
            nested.add("\n    .complex($T::$L)", ClassName.get(innerPkg, innerType), hop.getGetter());
            innerType = hop.getType();
            innerPkg = hop.getTypePackage() != null ? hop.getTypePackage() : modelPkg;
          }
          nested.add("\n    .$L($T::$L)", clusterMethod,
              ClassName.get(innerPkg, innerType), ref.getMemberGetter());
          nested.add(fieldMetadataChain(field));
          nested.add(publishChain(field, event));
          // One .done() to close the leaf's enclosing block plus one per hop back to CaseData.
          for (int i = 0; i <= ref.getParentHops().size(); i++) {
            nested.add(".done()");
          }
          cb.addStatement("$L", nested.build());
          continue;
        }
        if (!ref.getParentGetter().equals(openParent)) {
          if (openParent != null) {
            cb.addStatement("$L", cluster.add(".done()").build());
          }
          cluster = CodeBlock.builder();
          cluster.add("fields.complex($T::$L)", caseData, ref.getParentGetter());
          openParent = ref.getParentGetter();
        }
        cluster.add("\n    .$L($T::$L)", clusterMethod,
            ClassName.get(clusterPkg, ref.getClusterType()), ref.getMemberGetter());
        cluster.add(fieldMetadataChain(field));
        // Per-field Publish/PublishAs override the event's publishToCamunda() cascade; chain onto
        // the just-added member so the generated CaseEventToFields.Publish matches the input.
        cluster.add(publishChain(field, event));
        continue;
      }
      if (openParent != null) {
        cb.addStatement("$L", cluster.add(".done()").build());
        openParent = null;
        cluster = null;
      }
      FieldModel fieldModel = fieldsById.get(field.getCaseFieldId());
      if (fieldModel == null) {
        emitContext.getGaps().add(GapEntry.builder()
            .sheet("CaseEventToFields")
            .rowKey(event.getId() + "/" + field.getCaseFieldId())
            .column("CaseFieldID")
            .value(field.getCaseFieldId())
            .category(GapCategory.UNSUPPORTED_VALUE)
            .action(GapAction.PASSTHROUGH_COLUMN)
            .detail("Event '" + event.getId() + "' page references field '"
                + field.getCaseFieldId()
                + "' not present on CaseData; the CaseEventToFields row is passed through")
            .build());
        continue;
      }
      if (fieldModel.getOverlayTags() != null && !fieldModel.getOverlayTags().isEmpty()) {
        // The field is overlay-only AND its suffix has no configured predicate, so it is neither a
        // CaseData member nor a gated member (a gated field has its overlay tags cleared and a
        // @CCD(gate) set, and is placed normally below). CaseDataEmitter does not emit it onto
        // CaseData, so a CaseData::getX reference here would not compile; skip the placement and
        // record the gap rather than emitting a broken reference. Overlay fields with a configured
        // predicate now round-trip as generation-time gated members (see FieldModel.gate).
        emitContext.getGaps().add(GapEntry.builder()
            .sheet("CaseEventToFields")
            .rowKey(event.getId() + "/" + field.getCaseFieldId())
            .column("CaseFieldID")
            .value(field.getCaseFieldId())
            .category(GapCategory.UNSUPPORTED_VALUE)
            .action(GapAction.OMITTED_FAIL)
            .detail("Event '" + event.getId() + "' page places overlay-only field '"
                + field.getCaseFieldId() + "' (overlay " + fieldModel.getOverlayTags()
                + ") whose suffix has no configured environment predicate, so it is neither a"
                + " CaseData member nor a gated member; its placement is not reproduced")
            .build());
        continue;
      }
      if ("Label".equals(fieldModel.getFieldType())) {
        // Label fields are real CaseData members (see CaseDataEmitter); reference them as
        // readonly (immutable, like the SDK's own .label()) so the field appears on the event
        // without the generator inventing a CaseField row that omits the input's metadata. Honour
        // the input's ShowSummaryChangeOption via the NoSummary variant when it is N.
        String labelMethod = Boolean.FALSE.equals(field.getShowSummary())
            ? "readonlyNoSummary" : "readonly";
        // A Label field is non-COMPLEX, so the SDK cascades a publishing event's Publish=Y onto it;
        // chain publish(false) when the input did not publish it (matching the retired cascade rule).
        CodeBlock.Builder labelStmt = CodeBlock.builder();
        labelStmt.add("fields.$L($T::get$L)", labelMethod, caseData,
            capitalise(fieldModel.getJavaName()));
        labelStmt.add(fieldMetadataChain(field));
        labelStmt.add(publishChain(field, event));
        cb.addStatement("$L", labelStmt.build());
        continue;
      }
      if (field.getDisplayContext() != null
          && "COMPLEX".equalsIgnoreCase(field.getDisplayContext().trim())) {
        // A complex-typed field placed on a page with no per-member overrides: the SDK renders
        // DisplayContext=COMPLEX only via a .complex(getter) block, so emit an empty one. Honour
        // the input's ShowSummaryChangeOption via the two-arg complex(getter, summary) overload
        // when it is N (the SDK otherwise defaults ShowSummaryChangeOption to Y).
        CodeBlock.Builder complexStmt = CodeBlock.builder();
        if (Boolean.FALSE.equals(field.getShowSummary())) {
          complexStmt.add("fields.complex($T::get$L, false).done()", caseData,
              capitalise(fieldModel.getJavaName()));
        } else {
          complexStmt.add("fields.complex($T::get$L).done()", caseData,
              capitalise(fieldModel.getJavaName()));
        }
        // The .complex(...).done() call returns the FieldCollectionBuilder, so the fluent
        // lastField() metadata setters act on the complex field just placed — emit its per-field
        // CaseEventToFields metadata as Java rather than via the retired column graft.
        complexStmt.add(fieldMetadataChain(field));
        cb.addStatement("$L", complexStmt.build());
        continue;
      }
      // The SDK field builder defaults ShowSummaryChangeOption to Y; when the input explicitly
      // sets it to N, select the *NoSummary builder variant so the regenerated value matches.
      String method = Boolean.FALSE.equals(field.getShowSummary())
          ? builderMethod + "NoSummary" : builderMethod;
      String getter = "get" + capitalise(fieldModel.getJavaName());
      // Per-field CaseEventToFields metadata via the fluent lastField()-style FieldCollectionBuilder
      // setters, available after EVERY placement call (optional/mandatory/readonly and their
      // *NoSummary variants all return the FieldCollectionBuilder): FieldShowCondition,
      // CaseEventFieldLabel/Hint, DisplayContextParameter, DefaultValue, RetainHiddenValue,
      // ShowSummaryContentOption and NullifyByDefault. Emitting them here retires the per-field
      // CaseEventToFields column graft entirely for placed fields (see
      // DefaultDefinitionLinker.buildEventFieldColumnPassthrough, now callback-only).
      CodeBlock.Builder stmt = CodeBlock.builder();
      stmt.add("fields.$L($T::$L)", method, caseData, getter);
      stmt.add(fieldMetadataChain(field));
      stmt.add(publishChain(field, event));
      cb.addStatement("$L", stmt.build());
    }
    if (openParent != null) {
      cb.addStatement("$L", cluster.add(".done()").build());
    }
  }

  /**
   * A {@code .publish(false)}/{@code .publish(true)}/{@code .publishAs(...)} chain for a field whose
   * per-field {@code Publish}/{@code PublishAs} overrides the event's {@code publishToCamunda()}
   * cascade, or an empty block when the field matches the event default. {@code publishAs(...)}
   * implies publish, so it is emitted alone when set; otherwise an explicit {@code publish(flag)} is
   * emitted only when it differs from the event-level publish flag.
   *
   * @param field the page field
   * @param event the owning event (its publish flag is the field default)
   * @return the chained publish call(s), possibly empty
   */
  private CodeBlock publishChain(PageModel.PageField field, EventModel event) {
    CodeBlock.Builder cb = CodeBlock.builder();
    if (notBlank(field.getPublishAs())) {
      // PublishAs implies publish(true) and is emitted alone.
      cb.add("\n    .publishAs($S)", field.getPublishAs());
      return cb.build();
    }
    // The SDK's CaseEventToFieldsGenerator cascades the event's publishToCamunda() flag onto every
    // non-complex field unless the field carries an explicit publish(...). The input's per-field
    // intent is: Publish=Y → published; anything else (N or absent) → not published (this is what
    // the retired PUBLISH_CASCADE rule forgave — an absent/N field on a publishing event). So emit
    // an explicit publish(flag) whenever the field's desired value differs from the event default,
    // which for a publishing event means publish(false) on every field the input did not publish.
    boolean eventPublishes = Boolean.TRUE.equals(event.getPublish());
    boolean fieldPublishes = Boolean.TRUE.equals(field.getPublish());
    if (fieldPublishes != eventPublishes) {
      cb.add("\n    .publish($L)", fieldPublishes);
    }
    return cb.build();
  }

  /**
   * The fluent per-field {@code CaseEventToFields} metadata chain appended after a field placement.
   * Every setter is a {@code lastField()}-style {@code FieldCollectionBuilder} call usable after any
   * placement context (including {@code readonly}/{@code *NoSummary}), so all of these are emitted as
   * Java rather than grafted: {@code FieldShowCondition}, {@code CaseEventFieldLabel/Hint},
   * {@code DisplayContextParameter}, {@code DefaultValue} (raw string), {@code RetainHiddenValue},
   * {@code ShowSummaryContentOption} and {@code NullifyByDefault}. An empty chain when the field sets
   * none of them, keeping the terse common case unchanged.
   *
   * @param field the page field
   * @return the chained metadata calls, possibly empty
   */
  private CodeBlock fieldMetadataChain(PageModel.PageField field) {
    CodeBlock.Builder cb = CodeBlock.builder();
    if (notBlank(field.getShowCondition())) {
      cb.add("\n    .fieldShowCondition($S)", field.getShowCondition());
    }
    if (notBlank(field.getLabel())) {
      cb.add("\n    .caseEventFieldLabel($S)", field.getLabel());
    }
    if (notBlank(field.getHint())) {
      cb.add("\n    .caseEventFieldHint($S)", field.getHint());
    }
    if (notBlank(field.getDisplayContextParameter())) {
      cb.add("\n    .displayContextParameter($S)", field.getDisplayContextParameter());
    }
    if (notBlank(field.getDefaultValue())) {
      cb.add("\n    .defaultValue($S)", field.getDefaultValue());
    }
    if (Boolean.TRUE.equals(field.getRetainHiddenValue())) {
      cb.add("\n    .retainHiddenValue()");
    }
    if (field.getShowSummaryContentOption() != null) {
      cb.add("\n    .showSummaryContentOption($L)", field.getShowSummaryContentOption());
    }
    if (Boolean.TRUE.equals(field.getNullifyByDefault())) {
      cb.add("\n    .nullifyByDefault()");
    }
    return cb.build();
  }

  private static boolean notBlank(String s) {
    return s != null && !s.isEmpty();
  }

  private static CodeBlock literalOrNull(String s) {
    return notBlank(s) ? CodeBlock.of("$S", s) : CodeBlock.of("null");
  }

  private CodeBlock buildStateTargeting(EventModel event, ClassName state, EmitContext context) {
    List<String> preStates = event.getPreStates();
    String postState = event.getPostState();
    boolean hasPost = postState != null && !postState.isEmpty() && !"*".equals(postState);
    // Map each CCD state ID to the enum constant to reference: identity in generate mode, but a
    // reused team State enum may name its constant differently from the CCD ID (retrofit).
    String post = hasPost ? context.stateConstant(postState) : postState;

    if (preStates == null || preStates.isEmpty()) {
      // No pre-condition state: an event that creates the case in its post-state, or — when
      // there is no post-state either — one available in every state.
      if (hasPost) {
        return CodeBlock.of("initialState($T.$L)", state, post);
      }
      return CodeBlock.of("forAllStates()");
    }

    if (preStates.size() == 1 && "*".equals(preStates.get(0))) {
      if (!hasPost) {
        return CodeBlock.of("forAllStates()");
      }
      // A transition from any state into a fixed post-state, using the SDK's
      // forStateTransition(EnumSet from, S to) overload.
      return CodeBlock.of("forStateTransition($T.allOf($T.class), $T.$L)",
          ClassName.get("java.util", "EnumSet"), state, state, post);
    }

    if (preStates.size() == 1) {
      String pre = context.stateConstant(preStates.get(0));
      if (!hasPost || preStates.get(0).equals(postState)) {
        return CodeBlock.of("forState($T.$L)", state, pre);
      }
      return CodeBlock.of("forStateTransition($T.$L, $T.$L)", state, pre, state, post);
    }

    // Multiple pre-states.
    CodeBlock.Builder args = CodeBlock.builder();
    for (int i = 0; i < preStates.size(); i++) {
      if (i > 0) {
        args.add(", ");
      }
      args.add("$T.$L", state, context.stateConstant(preStates.get(i)));
    }
    if (hasPost) {
      // A transition from any of several pre-states into a fixed post-state. forStates() sets
      // the post-state equal to the pre-state set, which the generator renders as '*' (a
      // multi-element post set), so use the EnumSet-from overload that fixes a single
      // post-state — even when that state is itself one of the pre-states.
      return CodeBlock.of("forStateTransition($T.of($L), $T.$L)",
          ClassName.get("java.util", "EnumSet"), args.build(), state, post);
    }
    return CodeBlock.of("forStates($L)", args.build());
  }

  private String displayContextToMethod(String displayContext) {
    if (displayContext == null) {
      return "optional";
    }
    return switch (displayContext.toUpperCase()) {
      case "MANDATORY" -> "mandatory";
      case "READONLY" -> "readonly";
      case "HIDDEN" -> "optional";
      default -> "optional";
    };
  }

  private String capitalise(String s) {
    if (s == null || s.isEmpty()) {
      return s;
    }
    return Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }

  private CodeBlock crudToPermissionSet(String crud, ClassName permission) {
    List<String> perms = new ArrayList<>();
    for (char ch : crud.toUpperCase().toCharArray()) {
      switch (ch) {
        case 'C' -> perms.add("C");
        case 'R' -> perms.add("R");
        case 'U' -> perms.add("U");
        case 'D' -> perms.add("D");
        default -> { /* ignore unknown chars */ }
      }
    }
    if (perms.size() == 1) {
      return CodeBlock.of("$T.of($T.$L)", java.util.Set.class, permission, perms.get(0));
    }
    StringBuilder sb = new StringBuilder("$T.of(");
    for (int i = 0; i < perms.size(); i++) {
      if (i > 0) {
        sb.append(", ");
      }
      sb.append("$T.$L");
    }
    sb.append(")");
    Object[] args = new Object[1 + perms.size() * 2];
    args[0] = java.util.Set.class;
    for (int i = 0; i < perms.size(); i++) {
      args[1 + i * 2] = permission;
      args[2 + i * 2] = perms.get(i);
    }
    return CodeBlock.of(sb.toString(), args);
  }

  private Map<String, String> buildRoleConstants(CaseTypeModel model) {
    Map<String, String> index = new java.util.LinkedHashMap<>();
    for (RoleModel role : model.getRoles()) {
      index.put(role.getId(), role.getJavaConstant());
    }
    return index;
  }
}
