package uk.gov.hmcts.ccd.sdk.converter.emit.config;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Name-conversion helpers shared by the config emitters.
 */
final class Names {

  private Names() {
  }

  /**
   * Renders a CRUD letter string as the tersest {@code Permission}-set expression the SDK exposes.
   *
   * <p>The SDK's {@link uk.gov.hmcts.ccd.sdk.api.Permission} publishes exactly three set shortcuts —
   * {@code CR}, {@code CRU} and {@code CRUD} — so when the (order-normalised) CRUD string is one of
   * those, the matching {@code Permission.CRUD}-style constant is emitted, exactly as the reference
   * services write it (nfdiv's {@code CREATE_READ_UPDATE} re-export resolves to these). Any other
   * combination ({@code R}, {@code RU}, {@code CRD}, …) has no named constant, so it falls back to an
   * explicit {@code Set.of(Permission.X, …)} in canonical C-R-U-D order.
   *
   * @param crud the CRUD letters (any order/case)
   * @param permission the {@code Permission} enum class name
   * @return the permission-set expression
   */
  static CodeBlock permissionSet(String crud, ClassName permission) {
    // Collect the distinct CRUD letters in canonical C-R-U-D order so a named constant (CR/CRU/CRUD)
    // is matched regardless of the input string's order or duplicates.
    List<String> perms = new ArrayList<>();
    String upper = crud == null ? "" : crud.toUpperCase();
    for (char letter : new char[] {'C', 'R', 'U', 'D'}) {
      if (upper.indexOf(letter) >= 0) {
        perms.add(String.valueOf(letter));
      }
    }
    String key = String.join("", perms);
    if (key.equals("CR") || key.equals("CRU") || key.equals("CRUD")) {
      return CodeBlock.of("$T.$L", permission, key);
    }
    StringBuilder sb = new StringBuilder("$T.of(");
    Object[] args = new Object[1 + perms.size() * 2];
    args[0] = java.util.Set.class;
    for (int i = 0; i < perms.size(); i++) {
      sb.append(i == 0 ? "$T.$L" : ", $T.$L");
      args[1 + i * 2] = permission;
      args[2 + i * 2] = perms.get(i);
    }
    sb.append(")");
    return CodeBlock.of(sb.toString(), args);
  }

  /**
   * Converts a CCD case-type ID to a Java class-name prefix.
   *
   * <p>Strips non-alphanumeric characters and capitalises the first letter of each run of
   * word characters, so {@code "my-case-type"} becomes {@code "MyCaseType"}.
   *
   * @param caseTypeId the raw CCD case type ID
   * @return a Java-safe UpperCamelCase class name prefix
   */
  static String toClassName(String caseTypeId) {
    if (caseTypeId == null || caseTypeId.isEmpty()) {
      return "Unknown";
    }
    String[] parts = caseTypeId.split("[^a-zA-Z0-9]+");
    StringBuilder sb = new StringBuilder();
    for (String part : parts) {
      if (!part.isEmpty()) {
        sb.append(Character.toUpperCase(part.charAt(0)));
        if (part.length() > 1) {
          sb.append(part.substring(1));
        }
      }
    }
    String result = sb.toString();
    return result.isEmpty() ? "Unknown" : result;
  }

  /**
   * Converts a method name candidate to a safe Java identifier.
   *
   * <p>Replaces leading digits and non-alphanumeric characters so the result is always a
   * valid Java method name.
   *
   * @param raw the raw name (event ID or similar)
   * @return a Java-safe lowerCamelCase method name
   */
  static String toMethodName(String raw) {
    if (raw == null || raw.isEmpty()) {
      return "unknown";
    }
    String safe = raw.replaceAll("[^a-zA-Z0-9_]", "_");
    if (Character.isDigit(safe.charAt(0))) {
      safe = "event" + safe;
    }
    return safe;
  }
}
