package uk.gov.hmcts.ccd.sdk.converter.emit.config;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Name-conversion helpers shared by the config emitters.
 */
final class Names {

  private Names() {
  }

  /**
   * Converts a CCD case-type ID to a Java class-name prefix.
   *
   * <p>Strips non-alphanumeric characters and capitalises the first letter of each run of
   * word characters, so {@code "my-case-type"} becomes {@code "MyCaseType"}.
   *
   * @param caseTypeId the raw CCD case type ID
   * @return a Java-safe UpperCamelCase class name prefix
   */
  static String toClassName(String caseTypeId) {
    if (caseTypeId == null || caseTypeId.isEmpty()) {
      return "Unknown";
    }
    String[] parts = caseTypeId.split("[^a-zA-Z0-9]+");
    StringBuilder sb = new StringBuilder();
    for (String part : parts) {
      if (!part.isEmpty()) {
        sb.append(Character.toUpperCase(part.charAt(0)));
        if (part.length() > 1) {
          sb.append(part.substring(1));
        }
      }
    }
    String result = sb.toString();
    return result.isEmpty() ? "Unknown" : result;
  }

  /**
   * Converts a method name candidate to a safe Java identifier.
   *
   * <p>Replaces leading digits and non-alphanumeric characters so the result is always a
   * valid Java method name.
   *
   * @param raw the raw name (event ID or similar)
   * @return a Java-safe lowerCamelCase method name
   */
  static String toMethodName(String raw) {
    if (raw == null || raw.isEmpty()) {
      return "unknown";
    }
    String safe = raw.replaceAll("[^a-zA-Z0-9_]", "_");
    if (Character.isDigit(safe.charAt(0))) {
      safe = "event" + safe;
    }
    return safe;
  }
}
