/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.hmcts;

import org.junit.Test;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;


public class AppTest {
    @Test public void testGenerateConfigCompiles() {
      CCDConfig<?, ?, ?> config;
    }
}
