package uk.gov.hmcts.ccd.sdk.converter.roundtrip;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import uk.gov.hmcts.ccd.sdk.converter.api.ConversionOptions;
import uk.gov.hmcts.ccd.sdk.converter.ir.DefinitionIr;
import uk.gov.hmcts.ccd.sdk.converter.model.OverlayCondition;
import uk.gov.hmcts.ccd.sdk.converter.model.gap.GapCollector;
import uk.gov.hmcts.ccd.sdk.converter.reader.JsonDefinitionReader;
import uk.gov.hmcts.ccd.sdk.diff.ComparisonResult;
import uk.gov.hmcts.ccd.sdk.diff.NormalisingCcdConfigComparator;

/**
 * Final stage of the phase-3 retrofit-verify pipeline (see {@code bin/retrofit-verify}): diff a
 * CCD definition JSON tree freshly generated by the retrofitted service's own {@code gCC} build
 * against the team's hand-authored definition repo.
 *
 * <p>It reuses the exact machinery the in-process round-trip gate uses, so a retrofit that passes
 * here clears the same bar as a generated model:
 * <ul>
 *   <li>the converter's {@link JsonDefinitionReader} + {@link ExpectedDefinitionBuilder} aggregate
 *       the definition repo with the same overlay/env handling as {@code RoundTripTest} (rather
 *       than duplicating that logic);</li>
 *   <li>{@link NormalisingCcdConfigComparator} applies the same documented normalisation rules to
 *       both sides and reports the residual, unexplained differences.</li>
 * </ul>
 *
 * <p>Unlike the in-JVM gate, the "actual" side is <em>not</em> generated here — it is produced
 * outside this process by running {@code generateCCDConfig} inside the copied, patched service
 * build (which owns the team's full compile classpath, solving the classpath problem of
 * proposal §5). This CLI only reads that output directory back and compares.
 *
 * <p>Invoked from Gradle:
 * <pre>
 *   ./gradlew -p sdk :ccd-definition-converter:retrofitVerify --args='\
 *       --definition &lt;definition-dir&gt; --case-type CIVIL \
 *       --generated-dir &lt;gCC-output-root&gt; --env CCD_DEF_ENV=nonprod'
 * </pre>
 * Exit code is 0 when the definitions are semantically equivalent, 1 when residual diffs remain,
 * and 2 on a usage/IO error. The residual summary is printed to stdout regardless so the
 * orchestration script can surface it.
 */
public final class RetrofitVerifyCli {

  private RetrofitVerifyCli() {
  }

  public static void main(String[] args) {
    System.exit(run(args));
  }

  static int run(String[] args) {
    Args parsed;
    try {
      parsed = Args.parse(args);
    } catch (IllegalArgumentException e) {
      System.err.println("retrofit-verify: " + e.getMessage());
      System.err.println(usage());
      return 2;
    }

    // The overlay suffixes must mirror the ones the definition repo's own xlsx build applies, so
    // the expected side keeps exactly the fragment set a real build of this environment would.
    Map<String, OverlayCondition> overlays = new LinkedHashMap<>();
    overlays.put("prod", OverlayCondition.parse("CCD_DEF_ENV:prod"));
    overlays.put("nonprod", OverlayCondition.parse("!CCD_DEF_ENV:prod"));
    parsed.overlaySuffixes.forEach((suffix, spec) -> overlays.put(suffix, OverlayCondition.parse(spec)));

    ConversionOptions options = ConversionOptions.builder()
        .inputs(parsed.definitions)
        .caseTypeId(parsed.caseType)
        .modelPackage("uk.gov.hmcts")
        .overlaySuffixes(overlays)
        .build();

    // Resolve the generated case-type directory: gCC writes <configDir>/<caseType>, but allow the
    // caller to point straight at the case-type dir too.
    Path generated = parsed.generatedDir;
    Path caseTypeDir = generated.resolve(parsed.caseType);
    Path actualDir = Files.isDirectory(caseTypeDir) ? caseTypeDir : generated;
    if (!Files.isDirectory(actualDir)) {
      System.err.println("retrofit-verify: generated definition directory not found: " + generated
          + " (looked for a " + parsed.caseType + "/ subdir or the dir itself)");
      return 2;
    }

    DefinitionIr ir = new JsonDefinitionReader().read(options, new GapCollector());
    Map<String, List<Map<String, Object>>> expected =
        ExpectedDefinitionBuilder.build(ir, parsed.caseType, options, parsed.env);
    Map<String, List<Map<String, Object>>> actual =
        NormalisingCcdConfigComparator.aggregateDirectory(actualDir.toFile());

    ComparisonResult result = NormalisingCcdConfigComparator.compare(expected, actual);
    printSummary(parsed, actualDir, expected, actual, result);
    return result.matches() ? 0 : 1;
  }

  private static void printSummary(
      Args parsed,
      Path actualDir,
      Map<String, List<Map<String, Object>>> expected,
      Map<String, List<Map<String, Object>>> actual,
      ComparisonResult result) {
    System.out.println();
    System.out.println("=== retrofit-verify: " + parsed.caseType + " ===");
    System.out.println("  definition repo : " + parsed.definitions);
    System.out.println("  generated dir   : " + actualDir);
    System.out.println("  env             : " + parsed.env);
    System.out.println("  expected sheets : " + expected.size()
        + " (" + rowCount(expected) + " rows)");
    System.out.println("  actual sheets   : " + actual.size()
        + " (" + rowCount(actual) + " rows)");
    if (result.matches()) {
      System.out.println("  RESULT          : SEMANTICALLY EQUIVALENT (0 residual diffs)");
      return;
    }
    List<String> failures = result.getFailures();
    System.out.println("  RESULT          : " + failures.size() + " residual diff line(s)");
    System.out.println();
    System.out.println("Top residual categories (by sheet):");
    categorise(failures).forEach((sheet, count) ->
        System.out.printf("  %6d  %s%n", count, sheet));
    System.out.println();
    System.out.println("Residual diff lines:");
    for (String failure : failures) {
      System.out.println("  - " + failure);
    }
  }

  private static long rowCount(Map<String, List<Map<String, Object>>> sheets) {
    return sheets.values().stream().mapToLong(List::size).sum();
  }

  /** Buckets each failure line by the sheet name it starts with, most-frequent first. */
  private static Map<String, Long> categorise(List<String> failures) {
    Map<String, Long> counts = new LinkedHashMap<>();
    for (String failure : failures) {
      String sheet = failure.contains(":") ? failure.substring(0, failure.indexOf(':')).trim()
          : failure;
      counts.merge(sheet, 1L, Long::sum);
    }
    return counts.entrySet().stream()
        .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
        .collect(LinkedHashMap::new, (m, e) -> m.put(e.getKey(), e.getValue()), Map::putAll);
  }

  private static String usage() {
    return "usage: retrofit-verify --definition <dir> [--definition <dir>...] "
        + "--case-type <ID> --generated-dir <dir> [--env KEY=VALUE...] "
        + "[--overlay-suffix suffix=[!]ENV_VAR:value...]";
  }

  /** Parsed command-line arguments. */
  private static final class Args {
    private final List<Path> definitions = new ArrayList<>();
    private String caseType;
    private Path generatedDir;
    private final Map<String, String> env = new LinkedHashMap<>();
    private final Map<String, String> overlaySuffixes = new LinkedHashMap<>();

    static Args parse(String[] argv) {
      Args a = new Args();
      for (int i = 0; i < argv.length; i++) {
        String flag = argv[i];
        switch (flag) {
          case "--definition" -> a.definitions.add(Path.of(requireValue(argv, ++i, flag)));
          case "--case-type" -> a.caseType = requireValue(argv, ++i, flag);
          case "--generated-dir" -> a.generatedDir = Path.of(requireValue(argv, ++i, flag));
          case "--env" -> putKeyValue(a.env, requireValue(argv, ++i, flag), flag);
          case "--overlay-suffix" -> putKeyValue(a.overlaySuffixes, requireValue(argv, ++i, flag), flag);
          default -> throw new IllegalArgumentException("unknown argument: " + flag);
        }
      }
      if (a.definitions.isEmpty()) {
        throw new IllegalArgumentException("--definition is required");
      }
      if (a.caseType == null || a.caseType.isBlank()) {
        throw new IllegalArgumentException("--case-type is required");
      }
      if (a.generatedDir == null) {
        throw new IllegalArgumentException("--generated-dir is required");
      }
      for (Path definition : a.definitions) {
        if (!Files.isDirectory(definition)) {
          throw new IllegalArgumentException("--definition is not a directory: " + definition);
        }
      }
      return a;
    }

    private static void putKeyValue(Map<String, String> target, String pair, String flag) {
      int eq = pair.indexOf('=');
      if (eq < 1) {
        throw new IllegalArgumentException(flag + " expects KEY=VALUE but got: " + pair);
      }
      target.put(pair.substring(0, eq), pair.substring(eq + 1));
    }

    private static String requireValue(String[] argv, int index, String flag) {
      if (index >= argv.length) {
        throw new IllegalArgumentException(flag + " requires a value");
      }
      return argv[index];
    }
  }
}
