package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import static org.assertj.core.api.Assertions.assertThat;

import com.palantir.javapoet.JavaFile;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import javax.tools.Diagnostic;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;

/**
 * In-memory compile smoke test for emitted sources.
 *
 * <p>Compiles all generated {@link JavaFile} objects using the system Java compiler with
 * {@code -proc:none} against the test classpath augmented with the Lombok jar (needed because
 * Lombok annotations appear in generated imports even though no processing is applied).
 * Asserts that no diagnostics of {@link Diagnostic.Kind#ERROR} severity are produced.
 *
 * <p>Generated by ccd-definition-converter from CompileSmokeTest — do not edit by hand.
 */
final class CompileSmokeTest {

  private CompileSmokeTest() {
  }

  /**
   * Asserts that the given files compile without errors using the system Java compiler.
   *
   * @param files the generated JavaFile instances to compile
   */
  static void assertCompilesClean(List<JavaFile> files) {
    JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
    if (compiler == null) {
      // Running on a JRE-only distribution — skip the compile check
      return;
    }

    DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
    StandardJavaFileManager stdFm = compiler.getStandardFileManager(diagnostics, null, null);

    List<JavaFileObject> sources = new ArrayList<>();
    for (JavaFile jf : files) {
      sources.add(new StringJavaFileObject(
          jf.packageName() + "." + jf.typeSpec().name(),
          jf.toString()));
    }

    String classpath = buildClasspath();
    String lombokJar = findLombokJar();
    // Include Lombok as annotation processor so enum constructors are generated;
    // without this the enum constant bodies cannot resolve.
    List<String> opts;
    if (lombokJar != null) {
      opts = List.of(
          "-classpath", classpath,
          "-processorpath", lombokJar,
          "-source", "21",
          "-target", "21");
    } else {
      opts = List.of(
          "-classpath", classpath,
          "-proc:none",
          "-source", "21",
          "-target", "21");
    }

    JavaCompiler.CompilationTask task = compiler.getTask(null, stdFm, diagnostics, opts, null,
        sources);
    task.call();

    List<Diagnostic<? extends JavaFileObject>> errors = diagnostics.getDiagnostics().stream()
        .filter(dd -> dd.getKind() == Diagnostic.Kind.ERROR)
        .toList();

    assertThat(errors)
        .as("Expected zero compile errors but got:\n%s", formatDiagnostics(errors))
        .isEmpty();
  }

  /**
   * Builds a classpath string that includes the test classpath plus the Lombok jar, which
   * is needed so the compiler resolves {@code lombok.*} annotation type imports without error.
   *
   * @return the classpath string
   */
  private static String buildClasspath() {
    String base = System.getProperty("java.class.path");
    String lombokJar = findLombokJar();
    if (lombokJar == null) {
      return base;
    }
    return base + File.pathSeparator + lombokJar;
  }

  /**
   * Locates the Lombok jar on the annotation processor classpath by scanning the Gradle
   * cache or the module system.
   *
   * @return absolute path to lombok-*.jar, or null if not found
   */
  private static String findLombokJar() {
    try {
      // Try to locate lombok via ClassLoader — it won't be loadable, but the location
      // of the jar can sometimes be inferred from the annotation processor classpath
      // which the freefair plugin places as a system property.
      String apClasspath = System.getProperty("lombok.jar");
      if (apClasspath != null && !apClasspath.isEmpty()) {
        return apClasspath;
      }

      // Search the Gradle cache under the home dir
      Path gradleCache = Path.of(System.getProperty("user.home"), ".gradle",
          "caches", "modules-2", "files-2.1", "org.projectlombok", "lombok");
      if (Files.exists(gradleCache)) {
        return Files.walk(gradleCache)
            .filter(p -> p.getFileName().toString().matches("lombok-[0-9].*\\.jar"))
            .filter(p -> !p.toString().contains("sources") && !p.toString().contains("javadoc"))
            .map(Path::toString)
            .findFirst()
            .orElse(null);
      }
    } catch (IOException ex) {
      // Ignore — best effort
    }
    return null;
  }

  private static String formatDiagnostics(List<Diagnostic<? extends JavaFileObject>> diagnostics) {
    StringBuilder sb = new StringBuilder();
    for (Diagnostic<? extends JavaFileObject> dd : diagnostics) {
      sb.append(dd.getKind()).append(": ").append(dd.getMessage(null)).append("\n");
    }
    return sb.toString();
  }
}
