package uk.gov.hmcts.ccd.sdk.converter.emit.model;

import java.net.URI;
import javax.tools.SimpleJavaFileObject;

/**
 * An in-memory {@link javax.tools.JavaFileObject} backed by a source string.
 *
 * <p>Used by {@link CompileSmokeTest} to compile generated sources without writing to disk.
 *
 * <p>Generated by ccd-definition-converter from StringJavaFileObject — do not edit by hand.
 */
final class StringJavaFileObject extends SimpleJavaFileObject {

  private final String source;

  /**
   * Creates an in-memory file object for the named class backed by the given source string.
   *
   * @param className the fully-qualified class name
   * @param source the Java source text
   */
  StringJavaFileObject(String className, String source) {
    super(URI.create("string:///" + className.replace('.', '/') + Kind.SOURCE.extension),
        Kind.SOURCE);
    this.source = source;
  }

  @Override
  public CharSequence getCharContent(boolean ignoreEncodingErrors) {
    return source;
  }
}
