plugins {
    id 'java-platform'
}

dependencies {
    constraints {
        api project(':ccd-config-generator')
        api project(':decentralised-runtime')
        api project(':ccd-data-migration-support')
        api project(':ccd-runtime-indexing')
        api project(':ccd-servicebus-support')
        api project(':task-management')
        api project(':docweave')
    }
}

publishing {
    publications {
        bom(MavenPublication) {
            from components.javaPlatform
        }
    }
}
