package uk.gov.hmcts.ccd.sdk.type;

public enum FieldType {
  Unspecified,
  Email,
  PhoneUK,
  Date,
  Document,
  Schedule,
  TextArea,
  FixedList,
  FixedRadioList,
  YesOrNo,
  Address,
  CaseLink,
  CaseLocation,
  OrderSummary,
  MultiSelectList,
  Collection,
  Label,
  CasePaymentHistoryViewer,
  DynamicRadioList,
  DynamicMultiSelectList,
  Flags,
  FlagLauncher,
  FlagType,
  FlagDetail,
  ComponentLauncher,
  SearchCriteria,
  TTL
}
