/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ccd.sdk;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple functional test for the 'ccd.sdk.greeting' plugin.
 */
public class CcdSdkPluginFunctionalTest {
    @Test public void canRunTask() throws IOException {
        // Setup the test build
        File projectDir = new File("../service");

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();


        runner.withPluginClasspath();
        runner.withArguments("generateCCDConfig");
        runner.withProjectDir(projectDir);

        BuildResult result = runner.build();

        // Verify the result
        assertTrue(result.getOutput().contains("Hello from alex 'ccd.sdk.greeting'"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
