/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ccd.sdk;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'ccd.sdk.greeting' plugin.
 */
public class CcdSdkPluginTest {
    @Test public void pluginRegistersATask() {
//        // Create a test project and apply the plugin
//        Project project = ProjectBuilder.builder().build();
//        project.getPlugins().apply("ccd.sdk.greeting");
//
//        // Verify the result
//        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
