name: NFDiv Check

on:
  push:
  pull_request:

jobs:
  nfdiv-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run nfdiv:check
        run: ./gradlew nfdiv:check -i
