name: PCS Check

on:
  push:
  pull_request:

jobs:
  pcs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run pcs:check
        run: ./gradlew pcs:check -i

  pcs-semantic-diff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
          fetch-depth: 0
          submodules: recursive
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          path: pr
          fetch-depth: 0
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Generate base CCD config
        working-directory: base
        run: ./gradlew pcs:generateCCDConfig -i
      - name: Generate PR CCD config
        working-directory: pr
        run: ./gradlew pcs:generateCCDConfig -i
      - name: Compare CCD configuration outputs
        working-directory: pr
        run: |
          python scripts/ccd_diff.py \
            ../base/test-projects/pcs-api/build/definitions \
            test-projects/pcs-api/build/definitions
