name: PCS Check

on:
  push:
  pull_request:

jobs:
  pcs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run pcs:check
        run: ./gradlew pcs:check -i
